export const clubsBatch = [
  // ===== England (Northern Europe) =====
  { id: 1, short_name: "Sheffield FC", founded_year: 1857, description: "The world's oldest football club, founded in Sheffield and still playing there.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "FIFA officially recognises it as the oldest football club still in existence." },
  { id: 2, short_name: "Hallam FC", founded_year: 1860, description: "One of the oldest football clubs, from the Sheffield suburb of Crosspool.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Plays on the world's oldest football ground, Sandygate." },
  { id: 3, short_name: "Notts County", founded_year: 1862, description: "The oldest professional football club in the world, based in Nottingham.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Juventus adopted Notts County's black and white stripes in 1903." },
  { id: 4, short_name: "Stoke City", founded_year: 1863, description: "One of the oldest professional clubs, founded by railway workers in Stoke-on-Trent.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Claims to be the second-oldest professional football club in the world." },
  { id: 5, short_name: "Wrexham", founded_year: 1864, description: "The oldest football club in Wales, from the border town of Wrexham.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Now famously co-owned by actors Ryan Reynolds and Rob McElhenney." },
  { id: 6, short_name: "Nottingham Forest", founded_year: 1865, description: "A historic English club that won back-to-back European Cups under Brian Clough.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Won the European Cup just three seasons after promotion to the top flight." },
  { id: 7, short_name: "Queen's Park", founded_year: 1867, description: "Scotland's oldest football club, playing at Glasgow's Hampden Park.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Hampden Park once held a crowd of 149,000 for a Scotland–England match." },
  { id: 8, short_name: "Sheffield Wednesday", founded_year: 1867, description: "A proud Sheffield club that dominated early English football.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Named after the Wednesday cricket club whose members had that day off work." },
  { id: 9, short_name: "Rangers", founded_year: 1872, description: "Glasgow giants and one of the most decorated clubs in world football.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Holds the world record for domestic league titles won by a single club." },
  { id: 10, short_name: "Aston Villa", founded_year: 1874, description: "A Birmingham club and European Cup winner, a founding member of the Football League.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Won the European Cup in 1982, just three years after returning to the top flight." },
  { id: 11, short_name: "Hearts", founded_year: 1874, description: "An Edinburgh football club and one of Scotland's oldest.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Named after a dance hall, the Heart of Midlothian, where its founders met." },
  { id: 12, short_name: "Bolton Wanderers", founded_year: 1874, description: "A Lancashire club and a founding member of the Football League.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Won the FA Cup four times in the 1920s." },
  { id: 13, short_name: "Hibernian", founded_year: 1875, description: "An Edinburgh club founded by Irish immigrants, whose name comes from the Latin for Ireland.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "The first British club to play in the European Cup, in 1955." },
  { id: 14, short_name: "Blackburn Rovers", founded_year: 1875, description: "A Lancashire club that won the Premier League in 1995.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Won three consecutive FA Cups in the 1880s." },
  { id: 15, short_name: "Wolverhampton Wanderers", founded_year: 1877, description: "A Midlands club known as Wolves, founders of the Football League.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Wolves' floodlit friendlies against Honvéd in 1954 inspired the European Cup." },
  { id: 16, short_name: "Everton", founded_year: 1878, description: "A Liverpool club that has played more top-flight seasons than any other English club.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Everton have contested over 120 top-flight seasons, more than any other club." },
  { id: 17, short_name: "Manchester United", founded_year: 1878, description: "One of the world's most famous clubs, formed by railway workers in Newton Heath.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Began as Newton Heath LYR, playing in green and gold halves." },
  { id: 18, short_name: "Fulham", founded_year: 1879, description: "London's oldest professional football club, based at Craven Cottage.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Craven Cottage's Cottage pavilion dates from 1905 and still stands." },
  { id: 19, short_name: "Sunderland", founded_year: 1879, description: "A North-East club nicknamed the Black Cats, six-time English champions.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Sunderland's 19th-century 'Team of All Talents' won three league titles in four years." },
  { id: 20, short_name: "Preston North End", founded_year: 1880, description: "A Lancashire club and the first 'Double' winners in English football.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "The 1888-89 'Invincibles' won the league unbeaten and the FA Cup without conceding a goal." },
  { id: 21, short_name: "Manchester City", founded_year: 1880, description: "Founded as St Mark's church team, now a global football powerhouse.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Began in east Manchester to curb local gang violence among workers' children." },
  { id: 22, short_name: "Tottenham Hotspur", founded_year: 1882, description: "A North London club formed by grammar school boys, the first British club to win a European trophy.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Won the 1963 Cup Winners' Cup, the first British side to lift a European trophy." },
  { id: 23, short_name: "Burnley", founded_year: 1882, description: "A Lancashire club that won the league as recently as 1960.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "In 1960 Burnley were champions with a squad of just 16 players." },
  { id: 24, short_name: "Derby County", founded_year: 1884, description: "A Midlands club and founding member of the Football League.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Won two league titles under Brian Clough in the 1970s." },
  { id: 25, short_name: "Leicester City", founded_year: 1884, description: "A Midlands club that stunned the world by winning the Premier League in 2016.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Won the 2015-16 Premier League at pre-season odds of 5000/1." },
  { id: 26, short_name: "Southampton", founded_year: 1885, description: "A South Coast club founded as St Mary's Young Men's Association.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "The 'Saints' nickname comes directly from its church origins at St Mary's." },
  { id: 27, short_name: "Arsenal", founded_year: 1886, description: "A North London club founded by munitions workers in Woolwich, 13-time English champions.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Founded as Dial Square by workers at the Royal Arsenal." },
  { id: 28, short_name: "Celtic", founded_year: 1887, description: "A Glasgow club founded to raise money for the city's Irish immigrant community.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "The 1967 'Lisbon Lions' were the first British club to win the European Cup, all born within 30 miles of Glasgow." },
  { id: 29, short_name: "West Ham United", founded_year: 1895, description: "An East London club founded as Thames Ironworks FC by shipyard workers.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "The club crest still features crossed riveting hammers, a nod to its ironworks roots." },
  { id: 30, short_name: "Liverpool", founded_year: 1892, description: "One of the most successful clubs in world football, founded after a rent dispute at Anfield.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Created when Everton left Anfield and owner John Houlding started a new club." },
  { id: 31, short_name: "Newcastle United", founded_year: 1892, description: "A passionate North-East club that plays at the iconic St James' Park.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Formed by the merger of two rival East End and West End clubs." },
  { id: 32, short_name: "Chelsea", founded_year: 1905, description: "A West London club now among the most decorated in English football.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Founded at The Rising Sun pub and elected to the League the same year." },
  { id: 33, short_name: "Leeds United", founded_year: 1919, description: "A Yorkshire club with a huge following, revived under Marcelo Bielsa and beyond.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Formed after the previous Leeds City club was expelled from the League." },
  { id: 34, short_name: "Cliftonville", founded_year: 1879, description: "The oldest football club in Northern Ireland, from north Belfast.", countries: "GB", sport: "football", region: "Northern Europe", fun_fact: "Won the very first Irish Cup in 1881." },
  { id: 35, short_name: "Bohemians", founded_year: 1890, description: "The oldest football club in the Republic of Ireland, based in Dublin.", countries: "IE", sport: "football", region: "Northern Europe", fun_fact: "The only club to have played in every season of the League of Ireland." },
  { id: 36, short_name: "Shelbourne", founded_year: 1895, description: "A Dublin club and one of the most successful in Irish football history.", countries: "IE", sport: "football", region: "Northern Europe", fun_fact: "Reached the Champions League first qualifying round in 2004." },
  { id: 37, short_name: "Shamrock Rovers", founded_year: 1901, description: "The most successful club in Irish football, from the Dublin suburb of Milltown.", countries: "IE", sport: "football", region: "Northern Europe", fun_fact: "The first Irish club to reach the group stage of a European competition, in 2011." },

  // ===== France & Monaco (Western Europe) =====
  { id: 38, short_name: "Le Havre AC", founded_year: 1872, description: "The oldest football club in France, from the port city of Le Havre.", countries: "FR", sport: "football", region: "Western Europe", fun_fact: "Founded by English residents and originally played a mix of football and rugby." },
  { id: 39, short_name: "Girondins de Bordeaux", founded_year: 1881, description: "A French club founded as a gymnastics and sports society.", countries: "FR", sport: "football", region: "Western Europe", fun_fact: "Won six Ligue 1 titles in the 20th century." },
  { id: 40, short_name: "Olympique de Marseille", founded_year: 1899, description: "France's most passionately supported club, from the Mediterranean port city.", countries: "FR", sport: "football", region: "Western Europe", fun_fact: "The only French club to win the Champions League, in 1993." },
  { id: 41, short_name: "Stade Rennais", founded_year: 1901, description: "A Breton club from the city of Rennes.", countries: "FR", sport: "football", region: "Western Europe", fun_fact: "Produced the teenage Ousmane Dembélé before he moved to Dortmund." },
  { id: 42, short_name: "RC Lens", founded_year: 1906, description: "A passionate Northern French club with a close-knit mining-town fanbase.", countries: "FR", sport: "football", region: "Western Europe", fun_fact: "Stade Bollaert is built on a slag heap left by the region's old coal mines." },
  { id: 43, short_name: "RC Strasbourg", founded_year: 1906, description: "An Alsace club from the city of Strasbourg, near the German border.", countries: "FR", sport: "football", region: "Western Europe", fun_fact: "The only club to have won titles in both French and German football." },
  { id: 44, short_name: "Stade de Reims", founded_year: 1931, description: "A Champagne-region club that reached two European Cup finals in the 1950s.", countries: "FR", sport: "football", region: "Western Europe", fun_fact: "Lost the 1956 European Cup final to Real Madrid, the tournament's very first final." },
  { id: 45, short_name: "AS Saint-Étienne", founded_year: 1933, description: "A former powerhouse of French football, from the industrial city of Saint-Étienne.", countries: "FR", sport: "football", region: "Western Europe", fun_fact: "Won ten Ligue 1 titles, more than any other French club." },
  { id: 46, short_name: "AS Monaco", founded_year: 1924, description: "A club from the tiny principality of Monaco that plays in the French league.", countries: "MC", sport: "football", region: "Western Europe", fun_fact: "Won eight Ligue 1 titles despite coming from a country smaller than most stadiums' car parks." },
  { id: 47, short_name: "Olympique Lyonnais", founded_year: 1950, description: "A French club that dominated Ligue 1 with seven consecutive titles.", countries: "FR", sport: "football", region: "Western Europe", fun_fact: "Won seven straight Ligue 1 titles from 2002 to 2008, a national record." },
  { id: 48, short_name: "Paris Saint-Germain", founded_year: 1970, description: "The club of the French capital, now among the richest in the world.", countries: "FR", sport: "football", region: "Western Europe", fun_fact: "Formed by the merger of Paris FC and Stade Saint-Germain." },

  // ===== Germany (Western Europe) =====
  { id: 49, short_name: "Hamburger SV", founded_year: 1887, description: "A North German club with deep roots, based in Hamburg.", countries: "DE", sport: "football", region: "Western Europe", fun_fact: "Was the only club to play every Bundesliga season until its first relegation in 2018." },
  { id: 50, short_name: "Hertha BSC", founded_year: 1892, description: "A Berlin club named after a steamship, based at the Olympiastadion.", countries: "DE", sport: "football", region: "Western Europe", fun_fact: "The blue and white colours come from a steamship named Hertha." },
  { id: 51, short_name: "VfB Stuttgart", founded_year: 1893, description: "A Baden-Württemberg club and a founding member of the Bundesliga.", countries: "DE", sport: "football", region: "Western Europe", fun_fact: "Founded as a rugby club before football took over." },
  { id: 52, short_name: "Werder Bremen", founded_year: 1899, description: "A North German club from Bremen, famous for its long Bundesliga tenure.", countries: "DE", sport: "football", region: "Western Europe", fun_fact: "Its name comes from a word for 'river peninsula', the meadow where the founders first played." },
  { id: 53, short_name: "Eintracht Frankfurt", founded_year: 1899, description: "A Hesse club from Frankfurt, known for its passionate supporters.", countries: "DE", sport: "football", region: "Western Europe", fun_fact: "Lost the 1960 European Cup final 7-3 to Real Madrid, one of the greatest finals ever." },
  { id: 54, short_name: "Bayern Munich", founded_year: 1900, description: "Germany's most successful club and a global football giant.", countries: "DE", sport: "football", region: "Western Europe", fun_fact: "Has won the Bundesliga more times than all other clubs combined would need many lifetimes." },
  { id: 55, short_name: "1. FC Nürnberg", founded_year: 1900, description: "A Franconian club that was Germany's dominant side in the 1920s.", countries: "DE", sport: "football", region: "Western Europe", fun_fact: "Won nine German championships, mostly before the Bundesliga era." },
  { id: 56, short_name: "FC Schalke 04", founded_year: 1904, description: "A Ruhr Valley club from Gelsenkirchen, known for its working-class fanbase.", countries: "DE", sport: "football", region: "Western Europe", fun_fact: "The '04' in its name refers to its founding year, 1904." },
  { id: 57, short_name: "1. FSV Mainz 05", founded_year: 1905, description: "A Rhineland-Palatinate club where Jürgen Klopp began his managerial career.", countries: "DE", sport: "football", region: "Western Europe", fun_fact: "Klopp's Mainz side was promoted to the Bundesliga for the first time in 2004." },
  { id: 58, short_name: "Borussia Dortmund", founded_year: 1909, description: "A Ruhr Valley giant with one of the loudest stadiums in world football.", countries: "DE", sport: "football", region: "Western Europe", fun_fact: "The Signal Iduna Park 'Yellow Wall' is the largest standing terrace in European football." },
  { id: 59, short_name: "FC St. Pauli", founded_year: 1910, description: "A Hamburg club famous for its punk-inspired, politically engaged fan culture.", countries: "DE", sport: "football", region: "Western Europe", fun_fact: "Its skull-and-crossbones logo was adopted by fans in the 1980s." },
  { id: 60, short_name: "1. FC Köln", founded_year: 1948, description: "A Rhineland club and founding member of the Bundesliga.", countries: "DE", sport: "football", region: "Western Europe", fun_fact: "A live goat named Hennes serves as the club mascot." },

  // ===== Netherlands & Belgium (Western Europe) =====
  { id: 61, short_name: "Sparta Rotterdam", founded_year: 1888, description: "The oldest professional football club in the Netherlands, from Rotterdam.", countries: "NL", sport: "football", region: "Western Europe", fun_fact: "Won six Dutch championships in the early 20th century." },
  { id: 62, short_name: "Willem II", founded_year: 1896, description: "A Tilburg club named after the Dutch king, with three league titles.", countries: "NL", sport: "football", region: "Western Europe", fun_fact: "Named after King Willem II of the Netherlands." },
  { id: 63, short_name: "Ajax", founded_year: 1900, description: "An Amsterdam club and one of the most famous academies in world football.", countries: "NL", sport: "football", region: "Western Europe", fun_fact: "Produced Cruyff, Van Basten, Bergkamp and a generation of 'Total Football' stars." },
  { id: 64, short_name: "Feyenoord", founded_year: 1908, description: "A Rotterdam club with a huge working-class following.", countries: "NL", sport: "football", region: "Western Europe", fun_fact: "The first Dutch club to win the European Cup, in 1970." },
  { id: 65, short_name: "PSV Eindhoven", founded_year: 1913, description: "An Eindhoven club founded for the workers of the Philips electronics company.", countries: "NL", sport: "football", region: "Western Europe", fun_fact: "Founded to celebrate the centenary of Dutch independence from France." },
  { id: 66, short_name: "Royal Antwerp", founded_year: 1880, description: "Belgium's oldest football club, from the port city of Antwerp.", countries: "BE", sport: "football", region: "Western Europe", fun_fact: "The first Belgian club to reach a European final, in 1993." },
  { id: 67, short_name: "Club Brugge", founded_year: 1891, description: "A Flemish club from Bruges and one of Belgium's most successful.", countries: "BE", sport: "football", region: "Western Europe", fun_fact: "Reached the 1978 European Cup final, losing to Liverpool." },
  { id: 68, short_name: "Standard Liège", founded_year: 1898, description: "A Walloon club from Liège with a famously fervent support.", countries: "BE", sport: "football", region: "Western Europe", fun_fact: "Won ten Belgian league titles in the 20th century." },
  { id: 69, short_name: "RSC Anderlecht", founded_year: 1908, description: "Belgium's most successful club, from the Brussels commune of Anderlecht.", countries: "BE", sport: "football", region: "Western Europe", fun_fact: "Won two European Cup Winners' Cups in 1976 and 1978." },

  // ===== Switzerland (Western Europe) =====
  { id: 70, short_name: "FC St. Gallen", founded_year: 1879, description: "The oldest football club in continental Europe, from St. Gallen.", countries: "CH", sport: "football", region: "Western Europe", fun_fact: "Founded by an English theology student living in Switzerland." },
  { id: 71, short_name: "FC Basel", founded_year: 1893, description: "A Northwestern Swiss club and one of the country's most successful.", countries: "CH", sport: "football", region: "Western Europe", fun_fact: "Famously knocked Manchester United out of the Champions League group stage in 2011." },

  // ===== Italy (Southern Europe) =====
  { id: 72, short_name: "Genoa CFC", founded_year: 1893, description: "Italy's oldest football club, founded by Englishmen as a cricket and athletics club.", countries: "IT", sport: "football", region: "Southern Europe", fun_fact: "Won nine Italian championships, the first four of them consecutively from 1898." },
  { id: 73, short_name: "Udinese", founded_year: 1896, description: "A North-Eastern Italian club from Udine, founded as a gymnastics and fencing society.", countries: "IT", sport: "football", region: "Southern Europe", fun_fact: "The club's first ever match was against a team from visiting sailors." },
  { id: 74, short_name: "Juventus", founded_year: 1897, description: "Italy's most successful club, founded by students in Turin.", countries: "IT", sport: "football", region: "Southern Europe", fun_fact: "Adopted its black and white stripes from Notts County in 1903." },
  { id: 75, short_name: "AC Milan", founded_year: 1899, description: "A Milan giant founded by English expatriates, seven-time European champions.", countries: "IT", sport: "football", region: "Southern Europe", fun_fact: "The English founders' roots survive in the spelling 'Milan', never Italianised." },
  { id: 76, short_name: "SS Lazio", founded_year: 1900, description: "A Roman club named after the surrounding region of Lazio.", countries: "IT", sport: "football", region: "Southern Europe", fun_fact: "Founded as a multi-sport club, the sky-blue colours honour Greece's national flag." },
  { id: 77, short_name: "L.R. Vicenza", founded_year: 1902, description: "One of Italy's oldest clubs, from the Veneto city of Vicenza.", countries: "IT", sport: "football", region: "Southern Europe", fun_fact: "The first Italian club to have a floodlit pitch, in 1957." },
  { id: 78, short_name: "Hellas Verona", founded_year: 1903, description: "A Veneto club from Verona, surprise Italian champions in 1985.", countries: "IT", sport: "football", region: "Southern Europe", fun_fact: "The 1985 title was the only time a provincial club won Serie A in the 1980s." },
  { id: 79, short_name: "Torino FC", founded_year: 1906, description: "A Turin club with working-class roots, home of the legendary Grande Torino.", countries: "IT", sport: "football", region: "Southern Europe", fun_fact: "The entire Grande Torino team died in the 1949 Superga air disaster." },
  { id: 80, short_name: "Atalanta", founded_year: 1907, description: "A Bergamo club named after the Greek heroine, famed for its academy.", countries: "IT", sport: "football", region: "Southern Europe", fun_fact: "Reached the Champions League quarter-finals in 2020, its best European run." },
  { id: 81, short_name: "Inter Milan", founded_year: 1908, description: "A Milan club founded by dissidents who wanted to sign foreign players.", countries: "IT", sport: "football", region: "Southern Europe", fun_fact: "Its name 'Internazionale' reflects a founding ideal of welcoming players of all nations." },
  { id: 82, short_name: "Bologna FC", founded_year: 1909, description: "An Emilian club, seven-time Italian champions.", countries: "IT", sport: "football", region: "Southern Europe", fun_fact: "Won the 1932 Mitropa Cup, one of the earliest European club trophies." },
  { id: 83, short_name: "SSC Napoli", founded_year: 1926, description: "A Naples club idolised by its city, led by Maradona to two Serie A titles.", countries: "IT", sport: "football", region: "Southern Europe", fun_fact: "Retired Diego Maradona's number 10 shirt in 2000." },
  { id: 84, short_name: "ACF Fiorentina", founded_year: 1926, description: "A Tuscan club from Florence, famous for its purple kit.", countries: "IT", sport: "football", region: "Southern Europe", fun_fact: "The purple colour comes from a dye accident with the original red and white halves." },
  { id: 85, short_name: "AS Roma", founded_year: 1927, description: "The capital's club, formed by merging three Roman teams.", countries: "IT", sport: "football", region: "Southern Europe", fun_fact: "The wolf-and-twins emblem references the founding myth of Rome." },

  // ===== Spain (Southern Europe) =====
  { id: 86, short_name: "Sevilla FC", founded_year: 1890, description: "Spain's oldest club dedicated solely to football, from Andalusia.", countries: "ES", sport: "football", region: "Southern Europe", fun_fact: "Won the UEFA Cup/Europa League a record seven times." },
  { id: 87, short_name: "Athletic Club Bilbao", founded_year: 1898, description: "A Basque club famous for fielding only players from its own region.", countries: "ES", sport: "football", region: "Southern Europe", fun_fact: "Has never been relegated from La Liga, alongside Real Madrid and Barcelona." },
  { id: 88, short_name: "FC Barcelona", founded_year: 1899, description: "A Catalan giant founded by Joan Gamper, 'more than a club' to its supporters.", countries: "ES", sport: "football", region: "Southern Europe", fun_fact: "The motto 'Més que un club' reflects its role in Catalan identity." },
  { id: 89, short_name: "RCD Espanyol", founded_year: 1900, description: "Barcelona's 'other' club, founded by Spanish students.", countries: "ES", sport: "football", region: "Southern Europe", fun_fact: "The name 'Espanyol' was chosen to signal Spanish identity against Catalan-focused Barça." },
  { id: 90, short_name: "Real Madrid", founded_year: 1902, description: "The most successful club in European football, from the Spanish capital.", countries: "ES", sport: "football", region: "Southern Europe", fun_fact: "Has won more European Cups than any other club." },
  { id: 91, short_name: "Atlético Madrid", founded_year: 1903, description: "Madrid's second giant, founded by Basque students in the capital.", countries: "ES", sport: "football", region: "Southern Europe", fun_fact: "Began as a youth branch of Athletic Bilbao before becoming independent." },
  { id: 92, short_name: "Sporting Gijón", founded_year: 1905, description: "Asturias' biggest club from the port city of Gijón.", countries: "ES", sport: "football", region: "Southern Europe", fun_fact: "El Molinón, its home ground, is one of Spain's oldest stadiums." },
  { id: 93, short_name: "Deportivo La Coruña", founded_year: 1906, description: "A Galician club that won its only La Liga title in 2000.", countries: "ES", sport: "football", region: "Southern Europe", fun_fact: "The 'Super Depor' side reached the 2004 Champions League semi-finals." },
  { id: 94, short_name: "Real Betis", founded_year: 1907, description: "A Seville club with a passionate green-and-white following.", countries: "ES", sport: "football", region: "Southern Europe", fun_fact: "Won La Liga in 1935, its only league title to date." },
  { id: 95, short_name: "Real Sociedad", founded_year: 1909, description: "A Basque club from San Sebastián that signed only Basque players for decades.", countries: "ES", sport: "football", region: "Southern Europe", fun_fact: "The Basque-only policy lasted until 1989." },
  { id: 96, short_name: "Valencia CF", founded_year: 1919, description: "A Mediterranean club and six-time La Liga champion.", countries: "ES", sport: "football", region: "Southern Europe", fun_fact: "Reached back-to-back Champions League finals in 2000 and 2001, losing both." },
  { id: 97, short_name: "Real Zaragoza", founded_year: 1932, description: "An Aragonese club with a rich Copa del Rey tradition.", countries: "ES", sport: "football", region: "Southern Europe", fun_fact: "Won the 1995 Cup Winners' Cup with a last-minute Nayim goal from the halfway line." },

  // ===== Portugal (Southern Europe) =====
  { id: 98, short_name: "FC Porto", founded_year: 1893, description: "Portugal's second-most decorated club, from the city of Porto.", countries: "PT", sport: "football", region: "Southern Europe", fun_fact: "Won the 2004 Champions League under José Mourinho." },
  { id: 99, short_name: "SL Benfica", founded_year: 1904, description: "A Lisbon giant with one of the largest fanbases in the world.", countries: "PT", sport: "football", region: "Southern Europe", fun_fact: "Won back-to-back European Cups in 1961 and 1962 with Eusébio." },
  { id: 100, short_name: "Sporting CP", founded_year: 1906, description: "A Lisbon club whose academy produced Cristiano Ronaldo.", countries: "PT", sport: "football", region: "Southern Europe", fun_fact: "Cristiano Ronaldo came through the famous Academia Sporting at Alcochete." },
  { id: 101, short_name: "Boavista", founded_year: 1907, description: "A Porto club famous for its black-and-white checkerboard kit.", countries: "PT", sport: "football", region: "Southern Europe", fun_fact: "Won its only Primeira Liga title in 2001." },
  { id: 102, short_name: "SC Braga", founded_year: 1921, description: "A Northern Portuguese club that has become a consistent European qualifier.", countries: "PT", sport: "football", region: "Southern Europe", fun_fact: "Plays in a stadium carved out of a former quarry." },

  // ===== Greece (Southern Europe) =====
  { id: 103, short_name: "Panathinaikos", founded_year: 1908, description: "An Athenian multi-sport club that reached a European Cup final.", countries: "GR", sport: "football", region: "Southern Europe", fun_fact: "Reached the 1971 European Cup final, the only Greek club to do so." },
  { id: 104, short_name: "Olympiacos", founded_year: 1925, description: "Greece's most successful club, based in Piraeus.", countries: "GR", sport: "football", region: "Southern Europe", fun_fact: "Has won more Greek league titles than any other club." },
  { id: 105, short_name: "PAOK", founded_year: 1926, description: "A Thessaloniki club with a famously passionate following.", countries: "GR", sport: "football", region: "Southern Europe", fun_fact: "The name stands for 'Panthessalonikian Athletic Club of Constantinople'." },

  // ===== Eastern Europe =====
  { id: 106, short_name: "Újpest FC", founded_year: 1885, description: "A Budapest club and one of the oldest in Hungary.", countries: "HU", sport: "football", region: "Eastern Europe", fun_fact: "Won its first Hungarian title in 1930 and 20 more followed." },
  { id: 107, short_name: "MTK Budapest", founded_year: 1888, description: "A historic Budapest club that pioneered Hungarian football.", countries: "HU", sport: "football", region: "Eastern Europe", fun_fact: "Was the club of Hungary's legendary 1950s 'Golden Team' coach Gusztáv Sebes." },
  { id: 108, short_name: "Slavia Prague", founded_year: 1892, description: "A Czech club and one of the oldest in Central Europe.", countries: "CZ", sport: "football", region: "Eastern Europe", fun_fact: "The red star on its badge is said to have come from its founders' student society." },
  { id: 109, short_name: "Sparta Prague", founded_year: 1893, description: "Czechia's most successful club, from Prague.", countries: "CZ", sport: "football", region: "Eastern Europe", fun_fact: "Has won more Czech league titles than any other club." },
  { id: 110, short_name: "Ferencváros", founded_year: 1899, description: "Hungary's most popular club, from Budapest.", countries: "HU", sport: "football", region: "Eastern Europe", fun_fact: "Reached the 1975 Cup Winners' Cup final, losing to Dynamo Kyiv." },
  { id: 111, short_name: "Wisła Kraków", founded_year: 1906, description: "A Kraków club and one of Poland's oldest and most successful.", countries: "PL", sport: "football", region: "Eastern Europe", fun_fact: "Known as the 'White Star', after the emblem on its badge." },
  { id: 112, short_name: "Cracovia", founded_year: 1906, description: "The oldest football club in Poland, from Kraków.", countries: "PL", sport: "football", region: "Eastern Europe", fun_fact: "Won the very first Polish championship in 1921." },
  { id: 113, short_name: "Legia Warsaw", founded_year: 1916, description: "A Warsaw club founded by soldiers of the Polish Legions during WWI.", countries: "PL", sport: "football", region: "Eastern Europe", fun_fact: "Has won the Polish league title more times than any other club." },
  { id: 114, short_name: "Hajduk Split", founded_year: 1911, description: "A Dalmatian club from Split with a devoted fanbase.", countries: "HR", sport: "football", region: "Southern Europe", fun_fact: "Founded in a Split pub called U Fleků." },
  { id: 115, short_name: "Dinamo Zagreb", founded_year: 1911, description: "Croatia's most successful club, from the capital Zagreb.", countries: "HR", sport: "football", region: "Southern Europe", fun_fact: "Produced Luka Modrić, who began his career in its academy." },
  { id: 116, short_name: "Red Star Belgrade", founded_year: 1945, description: "Serbia's most successful club, European Cup winner in 1991.", countries: "RS", sport: "football", region: "Southern Europe", fun_fact: "Won the 1991 European Cup, the last before the Champions League era." },
  { id: 117, short_name: "Partizan Belgrade", founded_year: 1945, description: "A Belgrade club that reached the 1966 European Cup final.", countries: "RS", sport: "football", region: "Southern Europe", fun_fact: "Was the first club from the Balkans to reach a European Cup final." },

  // ===== Turkey (Western Asia) =====
  { id: 118, short_name: "Beşiktaş", founded_year: 1903, description: "An Istanbul club founded in the late Ottoman era as a gymnastics club.", countries: "TR", sport: "football", region: "Western Asia", fun_fact: "Was one of the first Turkish clubs, formed before football arrived in Istanbul." },
  { id: 119, short_name: "Galatasaray", founded_year: 1905, description: "An Istanbul club founded by students of the famous Galatasaray High School.", countries: "TR", sport: "football", region: "Western Asia", fun_fact: "The first Turkish club to win a European trophy, the 2000 UEFA Cup." },
  { id: 120, short_name: "Fenerbahçe", founded_year: 1907, description: "An Istanbul club from the Kadıköy district on the Asian side.", countries: "TR", sport: "football", region: "Western Asia", fun_fact: "Has never been relegated from Turkey's top division." },

  // ===== Russia & Ukraine (Eastern Europe) =====
  { id: 121, short_name: "CSKA Moscow", founded_year: 1911, description: "A Moscow club with roots in the Russian army's sports society.", countries: "RU", sport: "football", region: "Eastern Europe", fun_fact: "Won the 2005 UEFA Cup, the first Russian club to win a European trophy." },
  { id: 122, short_name: "Spartak Moscow", founded_year: 1922, description: "A Moscow club founded by a trade-union sports society.", countries: "RU", sport: "football", region: "Eastern Europe", fun_fact: "Was the most successful Soviet club, winning 12 league titles." },
  { id: 123, short_name: "Zenit St Petersburg", founded_year: 1925, description: "A St Petersburg club backed by the Gazprom energy giant.", countries: "RU", sport: "football", region: "Eastern Europe", fun_fact: "Won the 2008 UEFA Cup by beating Rangers in the Manchester final." },
  { id: 124, short_name: "Dynamo Kyiv", founded_year: 1927, description: "Ukraine's most successful club, from the capital Kyiv.", countries: "UA", sport: "football", region: "Eastern Europe", fun_fact: "Was the first Soviet club to win a European trophy, the 1975 Cup Winners' Cup." },
  { id: 125, short_name: "Shakhtar Donetsk", founded_year: 1936, description: "A Donetsk club famous for its Brazilian scouting network.", countries: "UA", sport: "football", region: "Eastern Europe", fun_fact: "Won the 2009 UEFA Cup, the last Ukrainian club to lift a European trophy." },

  // ===== South America =====
  { id: 126, short_name: "Rosario Central", founded_year: 1889, description: "An Argentine club founded by British railway workers in Rosario.", countries: "AR", sport: "football", region: "South America", fun_fact: "Founded by workers of the Central Argentine Railway, hence the name." },
  { id: 127, short_name: "Peñarol", founded_year: 1891, description: "A Uruguayan giant, founded as a railway workers' cricket club.", countries: "UY", sport: "football", region: "South America", fun_fact: "Began as the Central Uruguay Railway Cricket Club, or CURCC." },
  { id: 128, short_name: "Club Nacional de Football", founded_year: 1899, description: "Uruguay's most successful club, from Montevideo.", countries: "UY", sport: "football", region: "South America", fun_fact: "Founded as a Uruguayan alternative to the British-run clubs of the time." },
  { id: 129, short_name: "Alianza Lima", founded_year: 1901, description: "Peru's oldest and one of its most successful clubs, from Lima.", countries: "PE", sport: "football", region: "South America", fun_fact: "Founded by young workers in the Breña district of Lima." },
  { id: 130, short_name: "River Plate", founded_year: 1901, description: "A Buenos Aires giant, the most successful club in Argentine football.", countries: "AR", sport: "football", region: "South America", fun_fact: "Nicknamed 'Los Millonarios' after spending big on players in the 1930s." },
  { id: 131, short_name: "Racing Club", founded_year: 1903, description: "An Avellaneda club and the first Argentine team to win the Intercontinental Cup.", countries: "AR", sport: "football", region: "South America", fun_fact: "Won seven consecutive league titles from 1913 to 1919, a national record." },
  { id: 132, short_name: "Olimpia", founded_year: 1902, description: "Paraguay's oldest and most successful club, from Asunción.", countries: "PY", sport: "football", region: "South America", fun_fact: "Has won more Paraguayan league titles than any other club." },
  { id: 133, short_name: "Newell's Old Boys", founded_year: 1903, description: "A Rosario club named after an English teacher, Isaac Newell.", countries: "AR", sport: "football", region: "South America", fun_fact: "Lionel Messi was offered a trial there as a child but ended up at Barcelona." },
  { id: 134, short_name: "Boca Juniors", founded_year: 1905, description: "A Buenos Aires giant from the La Boca district, world-famous for its colours.", countries: "AR", sport: "football", region: "South America", fun_fact: "The blue and gold colours supposedly came from a Swedish ship's flag in the port." },
  { id: 135, short_name: "Independiente", founded_year: 1905, description: "An Avellaneda club nicknamed the 'King of Cups' for its Libertadores record.", countries: "AR", sport: "football", region: "South America", fun_fact: "Has won the Copa Libertadores a record seven times." },
  { id: 136, short_name: "Estudiantes", founded_year: 1905, description: "A La Plata club founded by students, known for its gritty style.", countries: "AR", sport: "football", region: "South America", fun_fact: "Won three consecutive Copa Libertadores titles from 1968 to 1970." },
  { id: 137, short_name: "San Lorenzo", founded_year: 1908, description: "A Buenos Aires club with a devoted following, the club of Pope Francis.", countries: "AR", sport: "football", region: "South America", fun_fact: "Pope Francis is a lifelong San Lorenzo fan and member." },
  { id: 138, short_name: "Vélez Sarsfield", founded_year: 1910, description: "A Buenos Aires club from the Liniers neighbourhood.", countries: "AR", sport: "football", region: "South America", fun_fact: "Won the 1994 Copa Libertadores under Carlos Bianchi." },
  { id: 139, short_name: "Flamengo", founded_year: 1895, description: "Brazil's most popular club, founded as a rowing club in Rio.", countries: "BR", sport: "football", region: "South America", fun_fact: "The football section was only added in 1911, by members who defected from Fluminense." },
  { id: 140, short_name: "Vasco da Gama", founded_year: 1898, description: "A Rio club founded by Portuguese immigrants as a rowing club.", countries: "BR", sport: "football", region: "South America", fun_fact: "Was the first Brazilian club to sign Black and working-class players, winning the 1923 league with them." },
  { id: 141, short_name: "Fluminense", founded_year: 1902, description: "A Rio club and one of Brazil's oldest, famous for its tricolor kit.", countries: "BR", sport: "football", region: "South America", fun_fact: "Won the 2023 Copa Libertadores, its first continental crown." },
  { id: 142, short_name: "Grêmio", founded_year: 1903, description: "A Porto Alegre club founded by German and English immigrants.", countries: "BR", sport: "football", region: "South America", fun_fact: "Won the 1983 Intercontinental Cup, beating Hamburg in Tokyo." },
  { id: 143, short_name: "Botafogo", founded_year: 1904, description: "A Rio club and the team of Garrincha and Nilton Santos.", countries: "BR", sport: "football", region: "South America", fun_fact: "Garrincha's dribbling made the club beloved across Brazil in the 1950s." },
  { id: 144, short_name: "Atlético Mineiro", founded_year: 1908, description: "A Belo Horizonte club and one of Brazil's biggest.", countries: "BR", sport: "football", region: "South America", fun_fact: "Won its first Copa Libertadores in 2013, beating Olimpia in the final." },
  { id: 145, short_name: "Internacional", founded_year: 1909, description: "A Porto Alegre club, the great rival of Grêmio.", countries: "BR", sport: "football", region: "South America", fun_fact: "Won the 2006 Copa Libertadores and followed it with the Club World Cup." },
  { id: 146, short_name: "Corinthians", founded_year: 1910, description: "A São Paulo giant founded by railway workers inspired by an English amateur side.", countries: "BR", sport: "football", region: "South America", fun_fact: "Named after the English Corinthian FC, which toured Brazil that year." },
  { id: 147, short_name: "Santos", founded_year: 1912, description: "A coastal São Paulo club and the home of Pelé for 18 years.", countries: "BR", sport: "football", region: "South America", fun_fact: "Pelé scored over 1,000 of his career goals in a Santos shirt." },
  { id: 148, short_name: "Palmeiras", founded_year: 1914, description: "A São Paulo club founded by Italian immigrants as Palestra Italia.", countries: "BR", sport: "football", region: "South America", fun_fact: "Renamed itself in 1942 when Brazil entered the war against the Axis." },
  { id: 149, short_name: "Colo-Colo", founded_year: 1925, description: "Chile's most popular club, named after a Mapuche chief.", countries: "CL", sport: "football", region: "South America", fun_fact: "The only Chilean club to win the Copa Libertadores, in 1991." },
  { id: 150, short_name: "Barcelona SC", founded_year: 1925, description: "An Ecuadorian club from Guayaquil, named after the Catalan city.", countries: "EC", sport: "football", region: "South America", fun_fact: "Has the largest following in Ecuador despite never winning the Copa Libertadores." },

  // ===== Mexico (Central America) =====
  { id: 151, short_name: "Pachuca", founded_year: 1901, description: "Mexico's oldest football club, founded by Cornish miners in the state of Hidalgo.", countries: "MX", sport: "football", region: "Central America", fun_fact: "The Mexican championship trophy was first played for in 1902, won by Pachuca." },
  { id: 152, short_name: "Guadalajara (Chivas)", founded_year: 1906, description: "A Guadalajara club famous for fielding only Mexican players.", countries: "MX", sport: "football", region: "Central America", fun_fact: "Founded by a Belgian, Edgar Everaert, who insisted on an all-Mexican squad." },
  { id: 153, short_name: "Club América", founded_year: 1916, description: "A Mexico City giant and one of the country's most successful clubs.", countries: "MX", sport: "football", region: "Central America", fun_fact: "Founded by students on Columbus Day, hence the name 'América'." },
  { id: 154, short_name: "Cruz Azul", founded_year: 1927, description: "A Mexico City club founded as the team of a cement company.", countries: "MX", sport: "football", region: "Central America", fun_fact: "The 'cement makers' won seven consecutive league titles in the 1970s." },
  { id: 155, short_name: "UNAM Pumas", founded_year: 1954, description: "The club of the National Autonomous University of Mexico.", countries: "MX", sport: "football", region: "Central America", fun_fact: "Hugo Sánchez began his career at Pumas before moving to Atlético Madrid." },

  // ===== Africa =====
  { id: 156, short_name: "Al Ahly", founded_year: 1907, description: "Egypt's most successful club, from Cairo, founded by students.", countries: "EG", sport: "football", region: "Northern Africa", fun_fact: "Often called the most decorated club in African football history." },
  { id: 157, short_name: "Zamalek", founded_year: 1911, description: "A Cairo club, the great rival of Al Ahly.", countries: "EG", sport: "football", region: "Northern Africa", fun_fact: "Was founded as Qasr El Nil Club and renamed Zamalek in 1952." },
  { id: 158, short_name: "Hearts of Oak", founded_year: 1911, description: "Ghana's oldest and one of its most successful clubs, from Accra.", countries: "GH", sport: "football", region: "Western Africa", fun_fact: "Won the 2000 CAF Champions League, its first continental crown." },
  { id: 159, short_name: "Espérance de Tunis", founded_year: 1919, description: "A Tunisian giant, from the capital Tunis.", countries: "TN", sport: "football", region: "Northern Africa", fun_fact: "Founded in a Tunis café by a group of young students." },
  { id: 160, short_name: "Wydad AC", founded_year: 1937, description: "A Casablanca club and one of Morocco's most successful.", countries: "MA", sport: "football", region: "Northern Africa", fun_fact: "The name 'Wydad' means 'love' in Arabic, chosen to bind the club together." },
  { id: 161, short_name: "Orlando Pirates", founded_year: 1937, description: "A Soweto club and one of South Africa's most popular.", countries: "ZA", sport: "football", region: "Southern Africa", fun_fact: "Was the first South African club to win the CAF Champions League, in 1995." },
  { id: 162, short_name: "TP Mazembe", founded_year: 1939, description: "A DR Congo club from Lubumbashi, a continental powerhouse.", countries: "CD", sport: "football", region: "Middle Africa", fun_fact: "Became the first African side to reach a Club World Cup final, in 2010." },
  { id: 163, short_name: "Mamelodi Sundowns", founded_year: 1970, description: "A Pretoria club owned by billionaire Patrice Motsepe.", countries: "ZA", sport: "football", region: "Southern Africa", fun_fact: "Won the 2016 CAF Champions League with a squad nicknamed the 'Brazilians'." },

  // ===== Asia =====
  { id: 164, short_name: "Mohun Bagan", founded_year: 1889, description: "One of Asia's oldest football clubs, from Kolkata.", countries: "IN", sport: "football", region: "Southern Asia", fun_fact: "In 1911 became the first Indian club to beat a British team for the IFA Shield." },
  { id: 165, short_name: "Maccabi Tel Aviv", founded_year: 1906, description: "Israel's most successful club, from Tel Aviv.", countries: "IL", sport: "football", region: "Western Asia", fun_fact: "Was founded as a sports club before the state of Israel existed." },
  { id: 166, short_name: "Al Ittihad", founded_year: 1927, description: "A Jeddah club and one of Saudi Arabia's oldest and biggest.", countries: "SA", sport: "football", region: "Western Asia", fun_fact: "Won back-to-back AFC Champions League titles in 2004 and 2005." },
  { id: 167, short_name: "Esteghlal", founded_year: 1945, description: "A Tehran club founded as 'Taj', renamed after the Iranian Revolution.", countries: "IR", sport: "football", region: "Southern Asia", fun_fact: "Won the 1970 Asian Club Championship, the first Iranian club to do so." },
  { id: 168, short_name: "Persepolis", founded_year: 1963, description: "Iran's most popular club, from Tehran.", countries: "IR", sport: "football", region: "Southern Asia", fun_fact: "The Tehran derby against Esteghlal is one of Asia's biggest matches." },
  { id: 169, short_name: "Al Hilal", founded_year: 1957, description: "A Riyadh club and one of Asia's most successful.", countries: "SA", sport: "football", region: "Western Asia", fun_fact: "Has won the AFC Champions League more times than any other club." },
  { id: 170, short_name: "Al Nassr", founded_year: 1955, description: "A Riyadh club that became world-famous by signing Cristiano Ronaldo in 2022.", countries: "SA", sport: "football", region: "Western Asia", fun_fact: "Ronaldo's arrival made it one of the most-followed clubs in the world overnight." },
  { id: 171, short_name: "Urawa Red Diamonds", founded_year: 1950, description: "A Saitama club founded as the football team of Mitsubishi Heavy Industries.", countries: "JP", sport: "football", region: "Eastern Asia", fun_fact: "The 'Red Diamonds' name comes from the Mitsubishi logo." },

  // =====================================================
  // ===== OTHER SPORTS (ids 172–271) =====
  // =====================================================

  // ----- Baseball (Northern America) -----
  { id: 172, short_name: "Cincinnati Reds", founded_year: 1869, description: "The first openly all-professional baseball team in history.", countries: "US", sport: "baseball", region: "Northern America", fun_fact: "The 1869 Red Stockings went 57-0 on a nationwide tour." },
  { id: 173, short_name: "Atlanta Braves", founded_year: 1871, description: "The oldest continuously operating professional sports franchise in the Americas.", countries: "US", sport: "baseball", region: "Northern America", fun_fact: "Began as the Boston Red Stockings, played in Milwaukee, then Atlanta." },
  { id: 174, short_name: "Chicago Cubs", founded_year: 1876, description: "A charter member of the National League, playing at Wrigley Field since 1916.", countries: "US", sport: "baseball", region: "Northern America", fun_fact: "Went 108 years between World Series titles, finally winning in 2016." },
  { id: 175, short_name: "St. Louis Cardinals", founded_year: 1882, description: "One of baseball's most decorated clubs, with 11 World Series titles.", countries: "US", sport: "baseball", region: "Northern America", fun_fact: "The second-most World Series wins in MLB, behind only the Yankees." },
  { id: 176, short_name: "San Francisco Giants", founded_year: 1883, description: "A club founded in New York as the Gothams, later moved to San Francisco.", countries: "US", sport: "baseball", region: "Northern America", fun_fact: "Won the 1888 and 1889 World Series while still based in New York." },
  { id: 177, short_name: "Los Angeles Dodgers", founded_year: 1884, description: "A club founded in Brooklyn that became the first MLB team on the West Coast.", countries: "US", sport: "baseball", region: "Northern America", fun_fact: "Broke baseball's colour barrier by signing Jackie Robinson in 1947." },
  { id: 178, short_name: "Philadelphia Phillies", founded_year: 1883, description: "The longest continuously operating one-name, one-city franchise in MLB.", countries: "US", sport: "baseball", region: "Northern America", fun_fact: "Took 97 years to win its first World Series, in 1980." },
  { id: 179, short_name: "Pittsburgh Pirates", founded_year: 1882, description: "A Pittsburgh club that played in the first modern World Series in 1903.", countries: "US", sport: "baseball", region: "Northern America", fun_fact: "Began as the Allegheny Base Ball Club before becoming the Pirates." },
  { id: 180, short_name: "New York Yankees", founded_year: 1903, description: "The most successful club in MLB history, with 27 World Series titles.", countries: "US", sport: "baseball", region: "Northern America", fun_fact: "Began in Baltimore as the Orioles before moving to New York in 1903." },
  { id: 181, short_name: "Boston Red Sox", founded_year: 1901, description: "A charter member of the American League, playing at Fenway Park since 1912.", countries: "US", sport: "baseball", region: "Northern America", fun_fact: "Sold Babe Ruth to the Yankees in 1919, starting the 'Curse of the Bambino'." },
  { id: 182, short_name: "Detroit Tigers", founded_year: 1901, description: "A charter member of the American League, from Detroit.", countries: "US", sport: "baseball", region: "Northern America", fun_fact: "Ty Cobb played for the Tigers for 22 seasons, hitting .366 over his career." },

  // ----- American Football (Northern America) -----
  { id: 183, short_name: "Arizona Cardinals", founded_year: 1898, description: "The oldest continuously operating professional football club in the United States.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Began in Chicago as the Morgan Athletic Club, moved to St. Louis, then Arizona." },
  { id: 184, short_name: "Green Bay Packers", founded_year: 1919, description: "The only community-owned major professional sports franchise in the United States.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Has won 13 NFL championships, more than any other club." },
  { id: 185, short_name: "Chicago Bears", founded_year: 1919, description: "A founding franchise of the NFL, from Chicago.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Began as the Decatur Staleys, a company team of the A.E. Staley food company." },
  { id: 186, short_name: "New York Giants", founded_year: 1925, description: "A New York NFL franchise with eight championship titles.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Owned by the Mara family since its founding in 1925." },
  { id: 187, short_name: "Detroit Lions", founded_year: 1930, description: "A Detroit NFL franchise founded as the Portsmouth Spartans in Ohio.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Moved to Detroit in 1934 and was renamed the Lions." },
  { id: 188, short_name: "Washington Commanders", founded_year: 1932, description: "A Washington D.C. NFL franchise founded as the Boston Braves.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Moved from Boston to Washington in 1937." },
  { id: 189, short_name: "Philadelphia Eagles", founded_year: 1933, description: "A Philadelphia NFL franchise, famous for its passionate fans.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "The 'Philly Special' trick play won the franchise its first Super Bowl in 2018." },
  { id: 190, short_name: "Pittsburgh Steelers", founded_year: 1933, description: "A Pittsburgh NFL franchise and six-time Super Bowl champion.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Has won six Super Bowls, tied for the most in NFL history." },
  { id: 191, short_name: "Los Angeles Rams", founded_year: 1936, description: "An NFL franchise founded in Cleveland, later in St. Louis, now back in Los Angeles.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "The first NFL team to put logos on its helmets, in 1948." },
  { id: 192, short_name: "Cleveland Browns", founded_year: 1946, description: "An NFL franchise named after its first coach and co-founder, Paul Brown.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Won all four championships of the rival AAFC before joining the NFL in 1950." },
  { id: 193, short_name: "San Francisco 49ers", founded_year: 1946, description: "An NFL franchise named after the 1849 Gold Rush prospectors.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Won five Super Bowls between 1981 and 1995, all with Hall of Fame quarterbacks." },
  { id: 194, short_name: "Indianapolis Colts", founded_year: 1953, description: "An NFL franchise founded in Baltimore, later relocated to Indianapolis.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Was the Baltimore Colts when Johnny Unitas led the 'Greatest Game Ever Played' in 1958." },
  { id: 195, short_name: "Dallas Cowboys", founded_year: 1960, description: "A Texas NFL franchise nicknamed 'America's Team'.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "One of the most valuable sports franchises in the world, worth billions." },
  { id: 196, short_name: "Kansas City Chiefs", founded_year: 1960, description: "An NFL franchise founded as the Dallas Texans, later moved to Kansas City.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Won Super Bowl IV in 1970 and then waited 50 years for the next, in 2020." },
  { id: 197, short_name: "Las Vegas Raiders", founded_year: 1960, description: "An NFL franchise founded in Oakland, later moved to LA and Las Vegas.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "The pirate-themed 'Just Win, Baby' motto was coined by owner Al Davis." },
  { id: 198, short_name: "New England Patriots", founded_year: 1960, description: "An NFL franchise founded as the Boston Patriots, now based in Foxborough.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Won six Super Bowls under Tom Brady and Bill Belichick from 2001 to 2019." },
  { id: 199, short_name: "Miami Dolphins", founded_year: 1966, description: "An NFL franchise from Miami, the only team with a perfect season.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "The 1972 Dolphins went 17-0, the only undefeated season in NFL history." },
  { id: 200, short_name: "Minnesota Vikings", founded_year: 1961, description: "An NFL franchise from Minneapolis, known for its purple and gold colours.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Reached four Super Bowls in the 1970s but lost them all." },

  // ----- Ice Hockey (Northern America) -----
  { id: 201, short_name: "Montreal Canadiens", founded_year: 1909, description: "The oldest continuously operating professional ice hockey club in the world.", countries: "CA", sport: "ice hockey", region: "Northern America", fun_fact: "Has won 24 Stanley Cups, more than any other NHL club." },
  { id: 202, short_name: "Toronto Maple Leafs", founded_year: 1917, description: "A Toronto NHL franchise and one of the 'Original Six'.", countries: "CA", sport: "ice hockey", region: "Northern America", fun_fact: "Has won 13 Stanley Cups but none since 1967." },
  { id: 203, short_name: "Boston Bruins", founded_year: 1924, description: "The first American NHL franchise, from Boston.", countries: "US", sport: "ice hockey", region: "Northern America", fun_fact: "Was the first NHL team based in the United States." },
  { id: 204, short_name: "Chicago Blackhawks", founded_year: 1926, description: "An NHL franchise from Chicago, one of the 'Original Six'.", countries: "US", sport: "ice hockey", region: "Northern America", fun_fact: "Named after Chief Black Hawk of the Sauk nation." },
  { id: 205, short_name: "Detroit Red Wings", founded_year: 1926, description: "An NHL franchise from Detroit, one of the 'Original Six'.", countries: "US", sport: "ice hockey", region: "Northern America", fun_fact: "The 'winged wheel' logo reflects Detroit's automotive heritage." },
  { id: 206, short_name: "New York Rangers", founded_year: 1926, description: "An NHL franchise from New York, one of the 'Original Six'.", countries: "US", sport: "ice hockey", region: "Northern America", fun_fact: "Won the Stanley Cup in its second season, 1928." },
  { id: 207, short_name: "Edmonton Oilers", founded_year: 1972, description: "An NHL franchise from Edmonton, home of the 1980s Wayne Gretzky dynasty.", countries: "CA", sport: "ice hockey", region: "Northern America", fun_fact: "Won five Stanley Cups in seven years between 1984 and 1990." },
  { id: 208, short_name: "Pittsburgh Penguins", founded_year: 1967, description: "An NHL franchise from Pittsburgh, home of Mario Lemieux and Sidney Crosby.", countries: "US", sport: "ice hockey", region: "Northern America", fun_fact: "Saved from bankruptcy in 1999 when Lemieux bought the club." },
  { id: 209, short_name: "Philadelphia Flyers", founded_year: 1967, description: "An NHL franchise from Philadelphia, nicknamed the 'Broad Street Bullies'.", countries: "US", sport: "ice hockey", region: "Northern America", fun_fact: "The 'Bullies' won back-to-back Stanley Cups in 1974 and 1975." },
  { id: 210, short_name: "Los Angeles Kings", founded_year: 1967, description: "An NHL franchise from Los Angeles, transformed by the arrival of Wayne Gretzky.", countries: "US", sport: "ice hockey", region: "Northern America", fun_fact: "Gretzky's 1988 trade from Edmonton popularised hockey in the American West." },
  { id: 211, short_name: "New York Islanders", founded_year: 1972, description: "An NHL franchise from Long Island, winners of four straight Stanley Cups.", countries: "US", sport: "ice hockey", region: "Northern America", fun_fact: "Won four consecutive Stanley Cups from 1980 to 1983." },

  // ----- Basketball (Northern America) -----
  { id: 212, short_name: "Boston Celtics", founded_year: 1946, description: "An NBA franchise from Boston, one of the most successful in basketball history.", countries: "US", sport: "basketball", region: "Northern America", fun_fact: "Won a record 18 NBA championships, the most in league history." },
  { id: 213, short_name: "New York Knicks", founded_year: 1946, description: "An NBA franchise from New York, playing at Madison Square Garden.", countries: "US", sport: "basketball", region: "Northern America", fun_fact: "One of only two founding NBA clubs never to have relocated." },
  { id: 214, short_name: "Golden State Warriors", founded_year: 1946, description: "An NBA franchise founded in Philadelphia, now based in San Francisco.", countries: "US", sport: "basketball", region: "Northern America", fun_fact: "Won the first ever NBA championship in 1947, then as the Philadelphia Warriors." },
  { id: 215, short_name: "Philadelphia 76ers", founded_year: 1946, description: "An NBA franchise from Philadelphia, founded as the Syracuse Nationals.", countries: "US", sport: "basketball", region: "Northern America", fun_fact: "Wilt Chamberlain scored 100 points in a single game for the club in 1962." },
  { id: 216, short_name: "Los Angeles Lakers", founded_year: 1947, description: "An NBA franchise founded in Minneapolis, named after Minnesota's lakes.", countries: "US", sport: "basketball", region: "Northern America", fun_fact: "Kept the 'Lakers' name even after moving to land-locked Los Angeles in 1960." },
  { id: 217, short_name: "Detroit Pistons", founded_year: 1941, description: "An NBA franchise founded as the Fort Wayne Zollner Pistons.", countries: "US", sport: "basketball", region: "Northern America", fun_fact: "Named after the pistons made by owner Fred Zollner's manufacturing company." },
  { id: 218, short_name: "Sacramento Kings", founded_year: 1945, description: "An NBA franchise founded as the Rochester Royals, the oldest continuously operating club.", countries: "US", sport: "basketball", region: "Northern America", fun_fact: "Has relocated more times than any other NBA franchise: Rochester, Cincinnati, Kansas City, Sacramento." },
  { id: 219, short_name: "Chicago Bulls", founded_year: 1966, description: "An NBA franchise from Chicago, home of the Michael Jordan dynasty.", countries: "US", sport: "basketball", region: "Northern America", fun_fact: "Won six NBA championships in the 1990s, two 'three-peats' under Jordan." },
  { id: 220, short_name: "San Antonio Spurs", founded_year: 1967, description: "An NBA franchise founded as the Dallas Chaparrals of the rival ABA.", countries: "US", sport: "basketball", region: "Northern America", fun_fact: "Won five NBA championships in 15 years under coach Gregg Popovich." },
  { id: 221, short_name: "Miami Heat", founded_year: 1988, description: "An NBA franchise from Miami, home of the 'Big Three' era.", countries: "US", sport: "basketball", region: "Northern America", fun_fact: "LeBron James, Dwyane Wade and Chris Bosh won two titles together from 2010 to 2014." },

  // ----- European Basketball -----
  { id: 222, short_name: "Real Madrid Baloncesto", founded_year: 1931, description: "The basketball section of Real Madrid and the most successful club in Europe.", countries: "ES", sport: "basketball", region: "Southern Europe", fun_fact: "Has won a record 11 EuroLeague titles." },
  { id: 223, short_name: "FC Barcelona Bàsquet", founded_year: 1926, description: "The basketball section of FC Barcelona, from Catalonia.", countries: "ES", sport: "basketball", region: "Southern Europe", fun_fact: "Won two EuroLeague titles, in 2003 and 2010." },
  { id: 224, short_name: "Olimpia Milano", founded_year: 1936, description: "Italy's most successful basketball club, from Milan.", countries: "IT", sport: "basketball", region: "Southern Europe", fun_fact: "Has won 28 Italian league championships, a national record." },
  { id: 225, short_name: "KK Partizan", founded_year: 1945, description: "A Belgrade basketball club, 1992 European champions.", countries: "RS", sport: "basketball", region: "Southern Europe", fun_fact: "Won the 1992 European Cup with a squad that could not travel because of war sanctions." },
  { id: 226, short_name: "KK Crvena Zvezda", founded_year: 1945, description: "A Belgrade basketball club, the great rival of Partizan.", countries: "RS", sport: "basketball", region: "Southern Europe", fun_fact: "Known in English as Red Star Belgrade." },
  { id: 227, short_name: "Žalgiris Kaunas", founded_year: 1944, description: "A Lithuanian basketball club, 1999 EuroLeague champions.", countries: "LT", sport: "basketball", region: "Northern Europe", fun_fact: "Tyus Edney's buzzer-beating layup in the 1999 Final Four final became club folklore." },

  // ----- Rugby Union -----
  { id: 228, short_name: "Barbarian FC", founded_year: 1890, description: "An invitational rugby club with no ground or players of its own.", countries: "GB", sport: "rugby union", region: "Northern Europe", fun_fact: "Famous for the 1973 try against the All Blacks, voted the greatest of all time." },
  { id: 229, short_name: "Blackheath FC", founded_year: 1858, description: "The oldest open rugby club in the world, from south-east London.", countries: "GB", sport: "rugby union", region: "Northern Europe", fun_fact: "Helped draft the original laws of rugby football in 1871." },
  { id: 230, short_name: "Bath Rugby", founded_year: 1865, description: "An English rugby club from the city of Bath, dominant in the 1980s.", countries: "GB", sport: "rugby union", region: "Northern Europe", fun_fact: "Won six English league titles in the 1980s and 1990s." },
  { id: 231, short_name: "Harlequins", founded_year: 1866, description: "A London rugby club famous for its quartered shirts.", countries: "GB", sport: "rugby union", region: "Northern Europe", fun_fact: "The 'quins' style of play was once known for flair and trickery." },
  { id: 232, short_name: "Wasps", founded_year: 1867, description: "A London rugby club, now based in Coventry.", countries: "GB", sport: "rugby union", region: "Northern Europe", fun_fact: "Founded at a meeting in a London pub where the wasp-like striped shirts were chosen." },
  { id: 233, short_name: "Leicester Tigers", founded_year: 1880, description: "The most successful English rugby club, from Leicester.", countries: "GB", sport: "rugby union", region: "Northern Europe", fun_fact: "Has won ten English league titles, more than any other club." },
  { id: 234, short_name: "Gloucester Rugby", founded_year: 1873, description: "A West Country rugby club, playing at Kingsholm since 1891.", countries: "GB", sport: "rugby union", region: "Northern Europe", fun_fact: "The 'Cherry and Whites' have a fierce local rivalry with Bath." },
  { id: 235, short_name: "Saracens", founded_year: 1876, description: "A London rugby club, dominant in Europe in the 2010s.", countries: "GB", sport: "rugby union", region: "Northern Europe", fun_fact: "Won three European Champions Cups in four years from 2016 to 2019." },
  { id: 236, short_name: "Northampton Saints", founded_year: 1880, description: "An English rugby club from Northampton, 2000 European champions.", countries: "GB", sport: "rugby union", region: "Northern Europe", fun_fact: "Won the 2000 Heineken Cup against Munster in the final." },
  { id: 237, short_name: "Leinster Rugby", founded_year: 1875, description: "An Irish provincial rugby team, one of the most successful in Europe.", countries: "IE", sport: "rugby union", region: "Northern Europe", fun_fact: "Has won five European Champions Cups, more than any other club." },
  { id: 238, short_name: "Munster Rugby", founded_year: 1879, description: "An Irish provincial rugby team, famous for its passionate Thomond Park support.", countries: "IE", sport: "rugby union", region: "Northern Europe", fun_fact: "Was the first club to beat the All Blacks, in 1978." },
  { id: 239, short_name: "Stade Toulousain", founded_year: 1890, description: "A French rugby club, the most successful in Europe.", countries: "FR", sport: "rugby union", region: "Western Europe", fun_fact: "Has won six European Champions Cups, the most of any club." },

  // ----- Cricket -----
  { id: 240, short_name: "Marylebone Cricket Club", founded_year: 1787, description: "The guardian of the Laws of Cricket and owner of Lord's Cricket Ground.", countries: "GB", sport: "cricket", region: "Northern Europe", fun_fact: "Codified the Laws of Cricket in 1788, which still govern the game today." },
  { id: 241, short_name: "Melbourne Cricket Club", founded_year: 1838, description: "The oldest cricket club in Australia, owner of the Melbourne Cricket Ground.", countries: "AU", sport: "cricket", region: "Australia & New Zealand", fun_fact: "The MCG hosted the first ever Test match, in 1877." },
  { id: 242, short_name: "Sussex CCC", founded_year: 1839, description: "The oldest of the 18 first-class county cricket clubs in England.", countries: "GB", sport: "cricket", region: "Northern Europe", fun_fact: "Won the first official County Championship titles in the 1870s." },
  { id: 243, short_name: "Surrey CCC", founded_year: 1845, description: "A county cricket club based at The Oval in London.", countries: "GB", sport: "cricket", region: "Northern Europe", fun_fact: "The Oval hosted the first ever Test match on English soil, in 1880." },
  { id: 244, short_name: "Kent CCC", founded_year: 1859, description: "A county cricket club from south-east England.", countries: "GB", sport: "cricket", region: "Northern Europe", fun_fact: "Won the first officially recognised County Championship in 1890." },
  { id: 245, short_name: "Yorkshire CCC", founded_year: 1863, description: "The most successful county cricket club in England.", countries: "GB", sport: "cricket", region: "Northern Europe", fun_fact: "Has won 33 County Championship titles, more than any other county." },
  { id: 246, short_name: "Lancashire CCC", founded_year: 1864, description: "A county cricket club from Manchester, playing at Old Trafford.", countries: "GB", sport: "cricket", region: "Northern Europe", fun_fact: "The 'Roses' rivalry with Yorkshire is one of cricket's oldest." },

  // ----- Golf -----
  { id: 247, short_name: "The Royal and Ancient Golf Club", founded_year: 1754, description: "The governing body of golf, based at St Andrews in Scotland.", countries: "GB", sport: "golf", region: "Northern Europe", fun_fact: "Golf has been played at St Andrews Links for over 600 years." },
  { id: 248, short_name: "Honourable Company of Edinburgh Golfers", founded_year: 1744, description: "The oldest golf club in the world, now based at Muirfield.", countries: "GB", sport: "golf", region: "Northern Europe", fun_fact: "Wrote golf's original 13 rules in 1744." },

  // ----- Rowing -----
  { id: 249, short_name: "Leander Club", founded_year: 1818, description: "One of the world's oldest rowing clubs, based at Henley-on-Thames.", countries: "GB", sport: "rowing", region: "Northern Europe", fun_fact: "Its oarsmen have won more Olympic medals than those of any other rowing club." },

  // ----- Sailing -----
  { id: 250, short_name: "Royal Yacht Squadron", founded_year: 1815, description: "The most prestigious yacht club in the world, based at Cowes on the Isle of Wight.", countries: "GB", sport: "sailing", region: "Northern Europe", fun_fact: "Started the America's Cup by hosting the 1851 race around the Isle of Wight." },

  // ----- Tennis -----
  { id: 251, short_name: "All England Lawn Tennis Club", founded_year: 1868, description: "The home of Wimbledon, the oldest tennis tournament in the world.", countries: "GB", sport: "tennis", region: "Northern Europe", fun_fact: "Was founded as a croquet club; tennis was only added in 1875." },

  // ----- Australian Rules Football -----
  { id: 252, short_name: "Melbourne Football Club", founded_year: 1858, description: "Widely regarded as the oldest football club of any code in the world.", countries: "AU", sport: "Australian rules football", region: "Australia & New Zealand", fun_fact: "Helped write the first rules of Australian rules football in 1859." },
  { id: 253, short_name: "Geelong Football Club", founded_year: 1859, description: "The second-oldest AFL club, nicknamed the Cats.", countries: "AU", sport: "Australian rules football", region: "Australia & New Zealand", fun_fact: "Won the 2022 AFL premiership, its first in 16 years." },
  { id: 254, short_name: "Carlton Football Club", founded_year: 1864, description: "One of the AFL's oldest and most successful clubs.", countries: "AU", sport: "Australian rules football", region: "Australia & New Zealand", fun_fact: "Won the first VFL premiership in 1897." },
  { id: 255, short_name: "Essendon Football Club", founded_year: 1872, description: "An AFL club known as the Bombers, with 16 premierships.", countries: "AU", sport: "Australian rules football", region: "Australia & New Zealand", fun_fact: "Shares the record of 16 VFL/AFL premierships with Carlton." },
  { id: 256, short_name: "Port Adelaide Football Club", founded_year: 1870, description: "The most successful football club in South Australian history.", countries: "AU", sport: "Australian rules football", region: "Australia & New Zealand", fun_fact: "Won a record 36 SANFL premierships before joining the AFL in 1997." },

  // ----- Rugby League -----
  { id: 257, short_name: "Wigan Warriors", founded_year: 1872, description: "The most successful club in English rugby league history.", countries: "GB", sport: "rugby league", region: "Northern Europe", fun_fact: "Won eight consecutive Challenge Cup finals from 1988 to 1995." },
  { id: 258, short_name: "Hull FC", founded_year: 1865, description: "A rugby league club from Hull, one of the sport's oldest.", countries: "GB", sport: "rugby league", region: "Northern Europe", fun_fact: "The Hull derby with Hull KR is one of the fiercest in rugby league." },
  { id: 259, short_name: "South Sydney Rabbitohs", founded_year: 1908, description: "The most successful club in Australian rugby league history.", countries: "AU", sport: "rugby league", region: "Australia & New Zealand", fun_fact: "Won 21 premierships, a national record, but was expelled from the league in 1999 before returning in 2002." },
  { id: 260, short_name: "Sydney Roosters", founded_year: 1908, description: "An NRL club founded as Eastern Suburbs, one of the foundation clubs.", countries: "AU", sport: "rugby league", region: "Australia & New Zealand", fun_fact: "The only club to have played in every season of top-flight Australian rugby league." },
  { id: 261, short_name: "St George Illawarra Dragons", founded_year: 1921, description: "An NRL club with the record for most consecutive premierships.", countries: "AU", sport: "rugby league", region: "Australia & New Zealand", fun_fact: "The original St George won 11 consecutive premierships from 1956 to 1966." },

  // ----- Volleyball -----
  { id: 262, short_name: "Modena Volley", founded_year: 1968, description: "Italy's most successful volleyball club, from Modena.", countries: "IT", sport: "volleyball", region: "Southern Europe", fun_fact: "Has won 12 Italian league championships, a national record." },
  { id: 263, short_name: "Trentino Volley", founded_year: 2000, description: "A successful Italian volleyball club from Trento.", countries: "IT", sport: "volleyball", region: "Southern Europe", fun_fact: "Won four consecutive CEV Champions League titles from 2009 to 2012." },

  // ----- Curling -----
  { id: 264, short_name: "Royal Caledonian Curling Club", founded_year: 1838, description: "The 'mother club' of curling, the sport's governing body.", countries: "GB", sport: "curling", region: "Northern Europe", fun_fact: "Recognised worldwide as the guardian of the rules of curling." },

  // ----- Handball -----
  { id: 265, short_name: "THW Kiel", founded_year: 1904, description: "Germany's most successful handball club, from Kiel.", countries: "DE", sport: "handball", region: "Western Europe", fun_fact: "Has won more German handball championships than any other club." },

  // ----- NFL Expansion -----
  { id: 266, short_name: "Buffalo Bills", founded_year: 1960, description: "An NFL franchise from Buffalo, the only team to reach four straight Super Bowls.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Lost four consecutive Super Bowls from 1991 to 1994, a record no club wants." },
  { id: 267, short_name: "Denver Broncos", founded_year: 1960, description: "An NFL franchise from Denver, a founding member of the AFL.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Won back-to-back Super Bowls in 1998 and 1999 with John Elway at quarterback." },
  { id: 268, short_name: "Nashville Titans", founded_year: 1960, description: "An NFL franchise founded as the Houston Oilers, now based in Tennessee.", countries: "US", sport: "American football", region: "Northern America", fun_fact: "Was the Houston Oilers for 36 years before relocating to Nashville in 1997." },

  // ----- NHL Expansion -----
  { id: 269, short_name: "Buffalo Sabres", founded_year: 1970, description: "An NHL franchise from Buffalo, founded with the Canucks in the 1970 expansion.", countries: "US", sport: "ice hockey", region: "Northern America", fun_fact: "Gilbert Perreault was the club's first draft pick and played 17 seasons in Buffalo." },
  { id: 270, short_name: "Vancouver Canucks", founded_year: 1970, description: "An NHL franchise from Vancouver, Canada's West Coast team.", countries: "CA", sport: "ice hockey", region: "Northern America", fun_fact: "Reached the 2011 Stanley Cup final, losing Game 7 to the Boston Bruins." },
  { id: 271, short_name: "Calgary Flames", founded_year: 1972, description: "An NHL franchise founded in Atlanta, now based in Calgary.", countries: "CA", sport: "ice hockey", region: "Northern America", fun_fact: "Won the 1989 Stanley Cup, the only title in club history." },
];