UPDATE events SET fun_fact = NULL;

UPDATE events SET fun_fact = 'The Cyrillic alphabet used across Eastern Europe today was named after Saint Cyril, one of these brothers.' WHERE id = 1;
UPDATE events SET fun_fact = 'Vratislaus II was the first Czech ruler to be crowned king, though the title initially only lasted for his lifetime.' WHERE id = 3;
UPDATE events SET fun_fact = 'The Golden Bull granted the Czech king the hereditary right to elect the Holy Roman Emperor alongside six other princes.' WHERE id = 5;
UPDATE events SET fun_fact = 'Charles University is the oldest university in Central Europe still operating and the first German-language university in Europe.' WHERE id = 8;
UPDATE events SET fun_fact = 'Jan Hus was burned at the stake for heresy, yet his reforms inspired Martin Luther a century later.' WHERE id = 9;
UPDATE events SET fun_fact = 'Jan Zizka won this battle despite being completely blind, proving his genius for military tactics.' WHERE id = 10;
UPDATE events SET fun_fact = 'The surviving victims swore they were saved by angels cushioning their dramatic fall from the castle window.' WHERE id = 11;
UPDATE events SET fun_fact = 'After this battle, 27 Czech nobles were publicly executed on Prague Old Town Square in a single day.' WHERE id = 12;
UPDATE events SET fun_fact = 'The National Theatre burned down just 11 years after opening, but was rebuilt in two years through public donations.' WHERE id = 14;
UPDATE events SET fun_fact = 'Czechoslovakia became independent without a single shot fired as Austria-Hungary collapsed around it.' WHERE id = 15;
UPDATE events SET fun_fact = 'Neville Chamberlain returned to London declaring peace for our time less than a year before WWII began.' WHERE id = 16;
UPDATE events SET fun_fact = 'The Velvet Revolution toppled communism in just 10 days without a single person killed by the regime.' WHERE id = 19;
UPDATE events SET fun_fact = 'Czechoslovakia split peacefully into two nations in the Velvet Divorce, one of history few peaceful separations.' WHERE id = 20;
UPDATE events SET fun_fact = 'Charles IV was crowned Holy Roman Emperor in Rome while holding the legendary spear said to pierce Christ side.' WHERE id = 35;
UPDATE events SET fun_fact = 'The Golden Bull of 1356 remained the fundamental law of the Holy Roman Empire for over four centuries.' WHERE id = 78;
UPDATE events SET fun_fact = 'Luther nailed his 95 Theses to a church door in Wittenberg, sparking the Protestant Reformation across Europe.' WHERE id = 80;
UPDATE events SET fun_fact = 'The Peace of Augsburg established the principle cuius regio, eius religio: whose realm, his religion.' WHERE id = 82;
UPDATE events SET fun_fact = 'This battle led directly to the capture of Napoleon III and the proclamation of the German Empire in Versailles weeks later.' WHERE id = 96;
UPDATE events SET fun_fact = 'Mount Vesuvius eruption buried Pompeii under meters of ash, preserving Roman daily life in extraordinary detail.' WHERE id = 291;
UPDATE events SET fun_fact = 'Dante died in Ravenna after finishing the Divine Comedy, widely considered one of the greatest works of world literature.' WHERE id = 301;
UPDATE events SET fun_fact = 'Galileo observed Jupiter moons with his telescope, proving not everything revolves around Earth as previously believed.' WHERE id = 312;
UPDATE events SET fun_fact = 'Napoleon crowned himself King of Italy in Milan with the Iron Crown, declaring God gave it to me, let none dare touch it.' WHERE id = 321;
UPDATE events SET fun_fact = 'Garibaldi sailed from Genoa with just over a thousand volunteers and liberated most of southern Italy within months.' WHERE id = 328;
UPDATE events SET fun_fact = 'The Lateran Treaty recognized Vatican City as an independent state, ending a 59-year standoff with Italy.' WHERE id = 338;
UPDATE events SET fun_fact = 'Charles I was the only English monarch ever tried and executed by his own people, marking the end of absolute monarchy.' WHERE id = 410;
UPDATE events SET fun_fact = 'The RAF victory in the Battle of Britain prevented Operation Sea Lion, Hitler planned invasion of the United Kingdom.' WHERE id = 433;
UPDATE events SET fun_fact = 'The Brexit referendum passed by 52% to 48%, beginning the UK withdrawal process from the European Union.' WHERE id = 440;
UPDATE events SET fun_fact = 'Over 150,000 Allied troops stormed the beaches of Normandy in the largest seaborne invasion in human history.' WHERE id = 285;
UPDATE events SET fun_fact = 'The atomic bombing of Hiroshima killed approximately 80,000 people instantly and led to Japan surrender within days.' WHERE id = 286;
UPDATE events SET fun_fact = 'Colonists disguised as Mohawk warriors dumped 342 chests of British tea into Boston Harbor to protest taxation without representation.' WHERE id = 246;
UPDATE events SET fun_fact = 'The Declaration of Independence was signed by 56 delegates, though John Hancock famously wrote his name largest so the King could read it.' WHERE id = 249;
UPDATE events SET fun_fact = 'Lewis and Clark traveled over 8,000 miles over two years, mapping the newly acquired Louisiana Territory with Sacagawea as guide.' WHERE id = 258;
UPDATE events SET fun_fact = 'Lincoln delivered the Gettysburg Address in just two minutes, yet it became one of the most quoted speeches in American history.' WHERE id = 269;
UPDATE events SET fun_fact = 'The Wright Brothers first flight on December 17 lasted only 12 seconds but changed human transportation forever.' WHERE id = 279;
UPDATE events SET fun_fact = 'The Wall Street Crash triggered the Great Depression, leading to worldwide unemployment rates exceeding 25% in industrialized nations.' WHERE id = 283;
UPDATE events SET fun_fact = 'Martin Luther King Jr delivered his I Have a Dream speech to over 250,000 people at the March on Washington.' WHERE id = 289;
UPDATE events SET fun_fact = 'Neil Armstrong became the first human to walk on the moon, uttering the famous phrase one small step for man, one giant leap for mankind.' WHERE id = 290;
