-- Seed data for sport_clubs table
-- Run AFTER 19_create_sport_clubs.sql
-- 271 clubs (football + other sports)

INSERT INTO sport_clubs (id, short_name, founded_year, description, countries, sport, region, fun_fact) VALUES
  (1, 'Sheffield FC', 1857, 'The world''s oldest football club, founded in Sheffield and still playing there.', 'GB', 'football', 'Northern Europe', 'FIFA officially recognises it as the oldest football club still in existence.'),
  (2, 'Hallam FC', 1860, 'One of the oldest football clubs, from the Sheffield suburb of Crosspool.', 'GB', 'football', 'Northern Europe', 'Plays on the world''s oldest football ground, Sandygate.'),
  (3, 'Notts County', 1862, 'The oldest professional football club in the world, based in Nottingham.', 'GB', 'football', 'Northern Europe', 'Juventus adopted Notts County''s black and white stripes in 1903.'),
  (4, 'Stoke City', 1863, 'One of the oldest professional clubs, founded by railway workers in Stoke-on-Trent.', 'GB', 'football', 'Northern Europe', 'Claims to be the second-oldest professional football club in the world.'),
  (5, 'Wrexham', 1864, 'The oldest football club in Wales, from the border town of Wrexham.', 'GB', 'football', 'Northern Europe', 'Now famously co-owned by actors Ryan Reynolds and Rob McElhenney.'),
  (6, 'Nottingham Forest', 1865, 'A historic English club that won back-to-back European Cups under Brian Clough.', 'GB', 'football', 'Northern Europe', 'Won the European Cup just three seasons after promotion to the top flight.'),
  (7, 'Queen''s Park', 1867, 'Scotland''s oldest football club, playing at Glasgow''s Hampden Park.', 'GB', 'football', 'Northern Europe', 'Hampden Park once held a crowd of 149,000 for a Scotland–England match.'),
  (8, 'Sheffield Wednesday', 1867, 'A proud Sheffield club that dominated early English football.', 'GB', 'football', 'Northern Europe', 'Named after the Wednesday cricket club whose members had that day off work.'),
  (9, 'Rangers', 1872, 'Glasgow giants and one of the most decorated clubs in world football.', 'GB', 'football', 'Northern Europe', 'Holds the world record for domestic league titles won by a single club.'),
  (10, 'Aston Villa', 1874, 'A Birmingham club and European Cup winner, a founding member of the Football League.', 'GB', 'football', 'Northern Europe', 'Won the European Cup in 1982, just three years after returning to the top flight.'),
  (11, 'Hearts', 1874, 'An Edinburgh football club and one of Scotland''s oldest.', 'GB', 'football', 'Northern Europe', 'Named after a dance hall, the Heart of Midlothian, where its founders met.'),
  (12, 'Bolton Wanderers', 1874, 'A Lancashire club and a founding member of the Football League.', 'GB', 'football', 'Northern Europe', 'Won the FA Cup four times in the 1920s.'),
  (13, 'Hibernian', 1875, 'An Edinburgh club founded by Irish immigrants, whose name comes from the Latin for Ireland.', 'GB', 'football', 'Northern Europe', 'The first British club to play in the European Cup, in 1955.'),
  (14, 'Blackburn Rovers', 1875, 'A Lancashire club that won the Premier League in 1995.', 'GB', 'football', 'Northern Europe', 'Won three consecutive FA Cups in the 1880s.'),
  (15, 'Wolverhampton Wanderers', 1877, 'A Midlands club known as Wolves, founders of the Football League.', 'GB', 'football', 'Northern Europe', 'Wolves'' floodlit friendlies against Honvéd in 1954 inspired the European Cup.'),
  (16, 'Everton', 1878, 'A Liverpool club that has played more top-flight seasons than any other English club.', 'GB', 'football', 'Northern Europe', 'Everton have contested over 120 top-flight seasons, more than any other club.'),
  (17, 'Manchester United', 1878, 'One of the world''s most famous clubs, formed by railway workers in Newton Heath.', 'GB', 'football', 'Northern Europe', 'Began as Newton Heath LYR, playing in green and gold halves.'),
  (18, 'Fulham', 1879, 'London''s oldest professional football club, based at Craven Cottage.', 'GB', 'football', 'Northern Europe', 'Craven Cottage''s Cottage pavilion dates from 1905 and still stands.'),
  (19, 'Sunderland', 1879, 'A North-East club nicknamed the Black Cats, six-time English champions.', 'GB', 'football', 'Northern Europe', 'Sunderland''s 19th-century ''Team of All Talents'' won three league titles in four years.'),
  (20, 'Preston North End', 1880, 'A Lancashire club and the first ''Double'' winners in English football.', 'GB', 'football', 'Northern Europe', 'The 1888-89 ''Invincibles'' won the league unbeaten and the FA Cup without conceding a goal.'),
  (21, 'Manchester City', 1880, 'Founded as St Mark''s church team, now a global football powerhouse.', 'GB', 'football', 'Northern Europe', 'Began in east Manchester to curb local gang violence among workers'' children.'),
  (22, 'Tottenham Hotspur', 1882, 'A North London club formed by grammar school boys, the first British club to win a European trophy.', 'GB', 'football', 'Northern Europe', 'Won the 1963 Cup Winners'' Cup, the first British side to lift a European trophy.'),
  (23, 'Burnley', 1882, 'A Lancashire club that won the league as recently as 1960.', 'GB', 'football', 'Northern Europe', 'In 1960 Burnley were champions with a squad of just 16 players.'),
  (24, 'Derby County', 1884, 'A Midlands club and founding member of the Football League.', 'GB', 'football', 'Northern Europe', 'Won two league titles under Brian Clough in the 1970s.'),
  (25, 'Leicester City', 1884, 'A Midlands club that stunned the world by winning the Premier League in 2016.', 'GB', 'football', 'Northern Europe', 'Won the 2015-16 Premier League at pre-season odds of 5000/1.'),
  (26, 'Southampton', 1885, 'A South Coast club founded as St Mary''s Young Men''s Association.', 'GB', 'football', 'Northern Europe', 'The ''Saints'' nickname comes directly from its church origins at St Mary''s.'),
  (27, 'Arsenal', 1886, 'A North London club founded by munitions workers in Woolwich, 13-time English champions.', 'GB', 'football', 'Northern Europe', 'Founded as Dial Square by workers at the Royal Arsenal.'),
  (28, 'Celtic', 1887, 'A Glasgow club founded to raise money for the city''s Irish immigrant community.', 'GB', 'football', 'Northern Europe', 'The 1967 ''Lisbon Lions'' were the first British club to win the European Cup, all born within 30 miles of Glasgow.'),
  (29, 'West Ham United', 1895, 'An East London club founded as Thames Ironworks FC by shipyard workers.', 'GB', 'football', 'Northern Europe', 'The club crest still features crossed riveting hammers, a nod to its ironworks roots.'),
  (30, 'Liverpool', 1892, 'One of the most successful clubs in world football, founded after a rent dispute at Anfield.', 'GB', 'football', 'Northern Europe', 'Created when Everton left Anfield and owner John Houlding started a new club.'),
  (31, 'Newcastle United', 1892, 'A passionate North-East club that plays at the iconic St James'' Park.', 'GB', 'football', 'Northern Europe', 'Formed by the merger of two rival East End and West End clubs.'),
  (32, 'Chelsea', 1905, 'A West London club now among the most decorated in English football.', 'GB', 'football', 'Northern Europe', 'Founded at The Rising Sun pub and elected to the League the same year.'),
  (33, 'Leeds United', 1919, 'A Yorkshire club with a huge following, revived under Marcelo Bielsa and beyond.', 'GB', 'football', 'Northern Europe', 'Formed after the previous Leeds City club was expelled from the League.'),
  (34, 'Cliftonville', 1879, 'The oldest football club in Northern Ireland, from north Belfast.', 'GB', 'football', 'Northern Europe', 'Won the very first Irish Cup in 1881.'),
  (35, 'Bohemians', 1890, 'The oldest football club in the Republic of Ireland, based in Dublin.', 'IE', 'football', 'Northern Europe', 'The only club to have played in every season of the League of Ireland.'),
  (36, 'Shelbourne', 1895, 'A Dublin club and one of the most successful in Irish football history.', 'IE', 'football', 'Northern Europe', 'Reached the Champions League first qualifying round in 2004.'),
  (37, 'Shamrock Rovers', 1901, 'The most successful club in Irish football, from the Dublin suburb of Milltown.', 'IE', 'football', 'Northern Europe', 'The first Irish club to reach the group stage of a European competition, in 2011.'),
  (38, 'Le Havre AC', 1872, 'The oldest football club in France, from the port city of Le Havre.', 'FR', 'football', 'Western Europe', 'Founded by English residents and originally played a mix of football and rugby.'),
  (39, 'Girondins de Bordeaux', 1881, 'A French club founded as a gymnastics and sports society.', 'FR', 'football', 'Western Europe', 'Won six Ligue 1 titles in the 20th century.'),
  (40, 'Olympique de Marseille', 1899, 'France''s most passionately supported club, from the Mediterranean port city.', 'FR', 'football', 'Western Europe', 'The only French club to win the Champions League, in 1993.'),
  (41, 'Stade Rennais', 1901, 'A Breton club from the city of Rennes.', 'FR', 'football', 'Western Europe', 'Produced the teenage Ousmane Dembélé before he moved to Dortmund.'),
  (42, 'RC Lens', 1906, 'A passionate Northern French club with a close-knit mining-town fanbase.', 'FR', 'football', 'Western Europe', 'Stade Bollaert is built on a slag heap left by the region''s old coal mines.'),
  (43, 'RC Strasbourg', 1906, 'An Alsace club from the city of Strasbourg, near the German border.', 'FR', 'football', 'Western Europe', 'The only club to have won titles in both French and German football.'),
  (44, 'Stade de Reims', 1931, 'A Champagne-region club that reached two European Cup finals in the 1950s.', 'FR', 'football', 'Western Europe', 'Lost the 1956 European Cup final to Real Madrid, the tournament''s very first final.'),
  (45, 'AS Saint-Étienne', 1933, 'A former powerhouse of French football, from the industrial city of Saint-Étienne.', 'FR', 'football', 'Western Europe', 'Won ten Ligue 1 titles, more than any other French club.'),
  (46, 'AS Monaco', 1924, 'A club from the tiny principality of Monaco that plays in the French league.', 'MC', 'football', 'Western Europe', 'Won eight Ligue 1 titles despite coming from a country smaller than most stadiums'' car parks.'),
  (47, 'Olympique Lyonnais', 1950, 'A French club that dominated Ligue 1 with seven consecutive titles.', 'FR', 'football', 'Western Europe', 'Won seven straight Ligue 1 titles from 2002 to 2008, a national record.'),
  (48, 'Paris Saint-Germain', 1970, 'The club of the French capital, now among the richest in the world.', 'FR', 'football', 'Western Europe', 'Formed by the merger of Paris FC and Stade Saint-Germain.'),
  (49, 'Hamburger SV', 1887, 'A North German club with deep roots, based in Hamburg.', 'DE', 'football', 'Western Europe', 'Was the only club to play every Bundesliga season until its first relegation in 2018.'),
  (50, 'Hertha BSC', 1892, 'A Berlin club named after a steamship, based at the Olympiastadion.', 'DE', 'football', 'Western Europe', 'The blue and white colours come from a steamship named Hertha.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO sport_clubs (id, short_name, founded_year, description, countries, sport, region, fun_fact) VALUES
  (51, 'VfB Stuttgart', 1893, 'A Baden-Württemberg club and a founding member of the Bundesliga.', 'DE', 'football', 'Western Europe', 'Founded as a rugby club before football took over.'),
  (52, 'Werder Bremen', 1899, 'A North German club from Bremen, famous for its long Bundesliga tenure.', 'DE', 'football', 'Western Europe', 'Its name comes from a word for ''river peninsula'', the meadow where the founders first played.'),
  (53, 'Eintracht Frankfurt', 1899, 'A Hesse club from Frankfurt, known for its passionate supporters.', 'DE', 'football', 'Western Europe', 'Lost the 1960 European Cup final 7-3 to Real Madrid, one of the greatest finals ever.'),
  (54, 'Bayern Munich', 1900, 'Germany''s most successful club and a global football giant.', 'DE', 'football', 'Western Europe', 'Has won the Bundesliga more times than all other clubs combined would need many lifetimes.'),
  (55, '1. FC Nürnberg', 1900, 'A Franconian club that was Germany''s dominant side in the 1920s.', 'DE', 'football', 'Western Europe', 'Won nine German championships, mostly before the Bundesliga era.'),
  (56, 'FC Schalke 04', 1904, 'A Ruhr Valley club from Gelsenkirchen, known for its working-class fanbase.', 'DE', 'football', 'Western Europe', 'The ''04'' in its name refers to its founding year, 1904.'),
  (57, '1. FSV Mainz 05', 1905, 'A Rhineland-Palatinate club where Jürgen Klopp began his managerial career.', 'DE', 'football', 'Western Europe', 'Klopp''s Mainz side was promoted to the Bundesliga for the first time in 2004.'),
  (58, 'Borussia Dortmund', 1909, 'A Ruhr Valley giant with one of the loudest stadiums in world football.', 'DE', 'football', 'Western Europe', 'The Signal Iduna Park ''Yellow Wall'' is the largest standing terrace in European football.'),
  (59, 'FC St. Pauli', 1910, 'A Hamburg club famous for its punk-inspired, politically engaged fan culture.', 'DE', 'football', 'Western Europe', 'Its skull-and-crossbones logo was adopted by fans in the 1980s.'),
  (60, '1. FC Köln', 1948, 'A Rhineland club and founding member of the Bundesliga.', 'DE', 'football', 'Western Europe', 'A live goat named Hennes serves as the club mascot.'),
  (61, 'Sparta Rotterdam', 1888, 'The oldest professional football club in the Netherlands, from Rotterdam.', 'NL', 'football', 'Western Europe', 'Won six Dutch championships in the early 20th century.'),
  (62, 'Willem II', 1896, 'A Tilburg club named after the Dutch king, with three league titles.', 'NL', 'football', 'Western Europe', 'Named after King Willem II of the Netherlands.'),
  (63, 'Ajax', 1900, 'An Amsterdam club and one of the most famous academies in world football.', 'NL', 'football', 'Western Europe', 'Produced Cruyff, Van Basten, Bergkamp and a generation of ''Total Football'' stars.'),
  (64, 'Feyenoord', 1908, 'A Rotterdam club with a huge working-class following.', 'NL', 'football', 'Western Europe', 'The first Dutch club to win the European Cup, in 1970.'),
  (65, 'PSV Eindhoven', 1913, 'An Eindhoven club founded for the workers of the Philips electronics company.', 'NL', 'football', 'Western Europe', 'Founded to celebrate the centenary of Dutch independence from France.'),
  (66, 'Royal Antwerp', 1880, 'Belgium''s oldest football club, from the port city of Antwerp.', 'BE', 'football', 'Western Europe', 'The first Belgian club to reach a European final, in 1993.'),
  (67, 'Club Brugge', 1891, 'A Flemish club from Bruges and one of Belgium''s most successful.', 'BE', 'football', 'Western Europe', 'Reached the 1978 European Cup final, losing to Liverpool.'),
  (68, 'Standard Liège', 1898, 'A Walloon club from Liège with a famously fervent support.', 'BE', 'football', 'Western Europe', 'Won ten Belgian league titles in the 20th century.'),
  (69, 'RSC Anderlecht', 1908, 'Belgium''s most successful club, from the Brussels commune of Anderlecht.', 'BE', 'football', 'Western Europe', 'Won two European Cup Winners'' Cups in 1976 and 1978.'),
  (70, 'FC St. Gallen', 1879, 'The oldest football club in continental Europe, from St. Gallen.', 'CH', 'football', 'Western Europe', 'Founded by an English theology student living in Switzerland.'),
  (71, 'FC Basel', 1893, 'A Northwestern Swiss club and one of the country''s most successful.', 'CH', 'football', 'Western Europe', 'Famously knocked Manchester United out of the Champions League group stage in 2011.'),
  (72, 'Genoa CFC', 1893, 'Italy''s oldest football club, founded by Englishmen as a cricket and athletics club.', 'IT', 'football', 'Southern Europe', 'Won nine Italian championships, the first four of them consecutively from 1898.'),
  (73, 'Udinese', 1896, 'A North-Eastern Italian club from Udine, founded as a gymnastics and fencing society.', 'IT', 'football', 'Southern Europe', 'The club''s first ever match was against a team from visiting sailors.'),
  (74, 'Juventus', 1897, 'Italy''s most successful club, founded by students in Turin.', 'IT', 'football', 'Southern Europe', 'Adopted its black and white stripes from Notts County in 1903.'),
  (75, 'AC Milan', 1899, 'A Milan giant founded by English expatriates, seven-time European champions.', 'IT', 'football', 'Southern Europe', 'The English founders'' roots survive in the spelling ''Milan'', never Italianised.'),
  (76, 'SS Lazio', 1900, 'A Roman club named after the surrounding region of Lazio.', 'IT', 'football', 'Southern Europe', 'Founded as a multi-sport club, the sky-blue colours honour Greece''s national flag.'),
  (77, 'L.R. Vicenza', 1902, 'One of Italy''s oldest clubs, from the Veneto city of Vicenza.', 'IT', 'football', 'Southern Europe', 'The first Italian club to have a floodlit pitch, in 1957.'),
  (78, 'Hellas Verona', 1903, 'A Veneto club from Verona, surprise Italian champions in 1985.', 'IT', 'football', 'Southern Europe', 'The 1985 title was the only time a provincial club won Serie A in the 1980s.'),
  (79, 'Torino FC', 1906, 'A Turin club with working-class roots, home of the legendary Grande Torino.', 'IT', 'football', 'Southern Europe', 'The entire Grande Torino team died in the 1949 Superga air disaster.'),
  (80, 'Atalanta', 1907, 'A Bergamo club named after the Greek heroine, famed for its academy.', 'IT', 'football', 'Southern Europe', 'Reached the Champions League quarter-finals in 2020, its best European run.'),
  (81, 'Inter Milan', 1908, 'A Milan club founded by dissidents who wanted to sign foreign players.', 'IT', 'football', 'Southern Europe', 'Its name ''Internazionale'' reflects a founding ideal of welcoming players of all nations.'),
  (82, 'Bologna FC', 1909, 'An Emilian club, seven-time Italian champions.', 'IT', 'football', 'Southern Europe', 'Won the 1932 Mitropa Cup, one of the earliest European club trophies.'),
  (83, 'SSC Napoli', 1926, 'A Naples club idolised by its city, led by Maradona to two Serie A titles.', 'IT', 'football', 'Southern Europe', 'Retired Diego Maradona''s number 10 shirt in 2000.'),
  (84, 'ACF Fiorentina', 1926, 'A Tuscan club from Florence, famous for its purple kit.', 'IT', 'football', 'Southern Europe', 'The purple colour comes from a dye accident with the original red and white halves.'),
  (85, 'AS Roma', 1927, 'The capital''s club, formed by merging three Roman teams.', 'IT', 'football', 'Southern Europe', 'The wolf-and-twins emblem references the founding myth of Rome.'),
  (86, 'Sevilla FC', 1890, 'Spain''s oldest club dedicated solely to football, from Andalusia.', 'ES', 'football', 'Southern Europe', 'Won the UEFA Cup/Europa League a record seven times.'),
  (87, 'Athletic Club Bilbao', 1898, 'A Basque club famous for fielding only players from its own region.', 'ES', 'football', 'Southern Europe', 'Has never been relegated from La Liga, alongside Real Madrid and Barcelona.'),
  (88, 'FC Barcelona', 1899, 'A Catalan giant founded by Joan Gamper, ''more than a club'' to its supporters.', 'ES', 'football', 'Southern Europe', 'The motto ''Més que un club'' reflects its role in Catalan identity.'),
  (89, 'RCD Espanyol', 1900, 'Barcelona''s ''other'' club, founded by Spanish students.', 'ES', 'football', 'Southern Europe', 'The name ''Espanyol'' was chosen to signal Spanish identity against Catalan-focused Barça.'),
  (90, 'Real Madrid', 1902, 'The most successful club in European football, from the Spanish capital.', 'ES', 'football', 'Southern Europe', 'Has won more European Cups than any other club.'),
  (91, 'Atlético Madrid', 1903, 'Madrid''s second giant, founded by Basque students in the capital.', 'ES', 'football', 'Southern Europe', 'Began as a youth branch of Athletic Bilbao before becoming independent.'),
  (92, 'Sporting Gijón', 1905, 'Asturias'' biggest club from the port city of Gijón.', 'ES', 'football', 'Southern Europe', 'El Molinón, its home ground, is one of Spain''s oldest stadiums.'),
  (93, 'Deportivo La Coruña', 1906, 'A Galician club that won its only La Liga title in 2000.', 'ES', 'football', 'Southern Europe', 'The ''Super Depor'' side reached the 2004 Champions League semi-finals.'),
  (94, 'Real Betis', 1907, 'A Seville club with a passionate green-and-white following.', 'ES', 'football', 'Southern Europe', 'Won La Liga in 1935, its only league title to date.'),
  (95, 'Real Sociedad', 1909, 'A Basque club from San Sebastián that signed only Basque players for decades.', 'ES', 'football', 'Southern Europe', 'The Basque-only policy lasted until 1989.'),
  (96, 'Valencia CF', 1919, 'A Mediterranean club and six-time La Liga champion.', 'ES', 'football', 'Southern Europe', 'Reached back-to-back Champions League finals in 2000 and 2001, losing both.'),
  (97, 'Real Zaragoza', 1932, 'An Aragonese club with a rich Copa del Rey tradition.', 'ES', 'football', 'Southern Europe', 'Won the 1995 Cup Winners'' Cup with a last-minute Nayim goal from the halfway line.'),
  (98, 'FC Porto', 1893, 'Portugal''s second-most decorated club, from the city of Porto.', 'PT', 'football', 'Southern Europe', 'Won the 2004 Champions League under José Mourinho.'),
  (99, 'SL Benfica', 1904, 'A Lisbon giant with one of the largest fanbases in the world.', 'PT', 'football', 'Southern Europe', 'Won back-to-back European Cups in 1961 and 1962 with Eusébio.'),
  (100, 'Sporting CP', 1906, 'A Lisbon club whose academy produced Cristiano Ronaldo.', 'PT', 'football', 'Southern Europe', 'Cristiano Ronaldo came through the famous Academia Sporting at Alcochete.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO sport_clubs (id, short_name, founded_year, description, countries, sport, region, fun_fact) VALUES
  (101, 'Boavista', 1907, 'A Porto club famous for its black-and-white checkerboard kit.', 'PT', 'football', 'Southern Europe', 'Won its only Primeira Liga title in 2001.'),
  (102, 'SC Braga', 1921, 'A Northern Portuguese club that has become a consistent European qualifier.', 'PT', 'football', 'Southern Europe', 'Plays in a stadium carved out of a former quarry.'),
  (103, 'Panathinaikos', 1908, 'An Athenian multi-sport club that reached a European Cup final.', 'GR', 'football', 'Southern Europe', 'Reached the 1971 European Cup final, the only Greek club to do so.'),
  (104, 'Olympiacos', 1925, 'Greece''s most successful club, based in Piraeus.', 'GR', 'football', 'Southern Europe', 'Has won more Greek league titles than any other club.'),
  (105, 'PAOK', 1926, 'A Thessaloniki club with a famously passionate following.', 'GR', 'football', 'Southern Europe', 'The name stands for ''Panthessalonikian Athletic Club of Constantinople''.'),
  (106, 'Újpest FC', 1885, 'A Budapest club and one of the oldest in Hungary.', 'HU', 'football', 'Eastern Europe', 'Won its first Hungarian title in 1930 and 20 more followed.'),
  (107, 'MTK Budapest', 1888, 'A historic Budapest club that pioneered Hungarian football.', 'HU', 'football', 'Eastern Europe', 'Was the club of Hungary''s legendary 1950s ''Golden Team'' coach Gusztáv Sebes.'),
  (108, 'Slavia Prague', 1892, 'A Czech club and one of the oldest in Central Europe.', 'CZ', 'football', 'Eastern Europe', 'The red star on its badge is said to have come from its founders'' student society.'),
  (109, 'Sparta Prague', 1893, 'Czechia''s most successful club, from Prague.', 'CZ', 'football', 'Eastern Europe', 'Has won more Czech league titles than any other club.'),
  (110, 'Ferencváros', 1899, 'Hungary''s most popular club, from Budapest.', 'HU', 'football', 'Eastern Europe', 'Reached the 1975 Cup Winners'' Cup final, losing to Dynamo Kyiv.'),
  (111, 'Wisła Kraków', 1906, 'A Kraków club and one of Poland''s oldest and most successful.', 'PL', 'football', 'Eastern Europe', 'Known as the ''White Star'', after the emblem on its badge.'),
  (112, 'Cracovia', 1906, 'The oldest football club in Poland, from Kraków.', 'PL', 'football', 'Eastern Europe', 'Won the very first Polish championship in 1921.'),
  (113, 'Legia Warsaw', 1916, 'A Warsaw club founded by soldiers of the Polish Legions during WWI.', 'PL', 'football', 'Eastern Europe', 'Has won the Polish league title more times than any other club.'),
  (114, 'Hajduk Split', 1911, 'A Dalmatian club from Split with a devoted fanbase.', 'HR', 'football', 'Southern Europe', 'Founded in a Split pub called U Fleků.'),
  (115, 'Dinamo Zagreb', 1911, 'Croatia''s most successful club, from the capital Zagreb.', 'HR', 'football', 'Southern Europe', 'Produced Luka Modrić, who began his career in its academy.'),
  (116, 'Red Star Belgrade', 1945, 'Serbia''s most successful club, European Cup winner in 1991.', 'RS', 'football', 'Southern Europe', 'Won the 1991 European Cup, the last before the Champions League era.'),
  (117, 'Partizan Belgrade', 1945, 'A Belgrade club that reached the 1966 European Cup final.', 'RS', 'football', 'Southern Europe', 'Was the first club from the Balkans to reach a European Cup final.'),
  (118, 'Beşiktaş', 1903, 'An Istanbul club founded in the late Ottoman era as a gymnastics club.', 'TR', 'football', 'Western Asia', 'Was one of the first Turkish clubs, formed before football arrived in Istanbul.'),
  (119, 'Galatasaray', 1905, 'An Istanbul club founded by students of the famous Galatasaray High School.', 'TR', 'football', 'Western Asia', 'The first Turkish club to win a European trophy, the 2000 UEFA Cup.'),
  (120, 'Fenerbahçe', 1907, 'An Istanbul club from the Kadıköy district on the Asian side.', 'TR', 'football', 'Western Asia', 'Has never been relegated from Turkey''s top division.'),
  (121, 'CSKA Moscow', 1911, 'A Moscow club with roots in the Russian army''s sports society.', 'RU', 'football', 'Eastern Europe', 'Won the 2005 UEFA Cup, the first Russian club to win a European trophy.'),
  (122, 'Spartak Moscow', 1922, 'A Moscow club founded by a trade-union sports society.', 'RU', 'football', 'Eastern Europe', 'Was the most successful Soviet club, winning 12 league titles.'),
  (123, 'Zenit St Petersburg', 1925, 'A St Petersburg club backed by the Gazprom energy giant.', 'RU', 'football', 'Eastern Europe', 'Won the 2008 UEFA Cup by beating Rangers in the Manchester final.'),
  (124, 'Dynamo Kyiv', 1927, 'Ukraine''s most successful club, from the capital Kyiv.', 'UA', 'football', 'Eastern Europe', 'Was the first Soviet club to win a European trophy, the 1975 Cup Winners'' Cup.'),
  (125, 'Shakhtar Donetsk', 1936, 'A Donetsk club famous for its Brazilian scouting network.', 'UA', 'football', 'Eastern Europe', 'Won the 2009 UEFA Cup, the last Ukrainian club to lift a European trophy.'),
  (126, 'Rosario Central', 1889, 'An Argentine club founded by British railway workers in Rosario.', 'AR', 'football', 'South America', 'Founded by workers of the Central Argentine Railway, hence the name.'),
  (127, 'Peñarol', 1891, 'A Uruguayan giant, founded as a railway workers'' cricket club.', 'UY', 'football', 'South America', 'Began as the Central Uruguay Railway Cricket Club, or CURCC.'),
  (128, 'Club Nacional de Football', 1899, 'Uruguay''s most successful club, from Montevideo.', 'UY', 'football', 'South America', 'Founded as a Uruguayan alternative to the British-run clubs of the time.'),
  (129, 'Alianza Lima', 1901, 'Peru''s oldest and one of its most successful clubs, from Lima.', 'PE', 'football', 'South America', 'Founded by young workers in the Breña district of Lima.'),
  (130, 'River Plate', 1901, 'A Buenos Aires giant, the most successful club in Argentine football.', 'AR', 'football', 'South America', 'Nicknamed ''Los Millonarios'' after spending big on players in the 1930s.'),
  (131, 'Racing Club', 1903, 'An Avellaneda club and the first Argentine team to win the Intercontinental Cup.', 'AR', 'football', 'South America', 'Won seven consecutive league titles from 1913 to 1919, a national record.'),
  (132, 'Olimpia', 1902, 'Paraguay''s oldest and most successful club, from Asunción.', 'PY', 'football', 'South America', 'Has won more Paraguayan league titles than any other club.'),
  (133, 'Newell''s Old Boys', 1903, 'A Rosario club named after an English teacher, Isaac Newell.', 'AR', 'football', 'South America', 'Lionel Messi was offered a trial there as a child but ended up at Barcelona.'),
  (134, 'Boca Juniors', 1905, 'A Buenos Aires giant from the La Boca district, world-famous for its colours.', 'AR', 'football', 'South America', 'The blue and gold colours supposedly came from a Swedish ship''s flag in the port.'),
  (135, 'Independiente', 1905, 'An Avellaneda club nicknamed the ''King of Cups'' for its Libertadores record.', 'AR', 'football', 'South America', 'Has won the Copa Libertadores a record seven times.'),
  (136, 'Estudiantes', 1905, 'A La Plata club founded by students, known for its gritty style.', 'AR', 'football', 'South America', 'Won three consecutive Copa Libertadores titles from 1968 to 1970.'),
  (137, 'San Lorenzo', 1908, 'A Buenos Aires club with a devoted following, the club of Pope Francis.', 'AR', 'football', 'South America', 'Pope Francis is a lifelong San Lorenzo fan and member.'),
  (138, 'Vélez Sarsfield', 1910, 'A Buenos Aires club from the Liniers neighbourhood.', 'AR', 'football', 'South America', 'Won the 1994 Copa Libertadores under Carlos Bianchi.'),
  (139, 'Flamengo', 1895, 'Brazil''s most popular club, founded as a rowing club in Rio.', 'BR', 'football', 'South America', 'The football section was only added in 1911, by members who defected from Fluminense.'),
  (140, 'Vasco da Gama', 1898, 'A Rio club founded by Portuguese immigrants as a rowing club.', 'BR', 'football', 'South America', 'Was the first Brazilian club to sign Black and working-class players, winning the 1923 league with them.'),
  (141, 'Fluminense', 1902, 'A Rio club and one of Brazil''s oldest, famous for its tricolor kit.', 'BR', 'football', 'South America', 'Won the 2023 Copa Libertadores, its first continental crown.'),
  (142, 'Grêmio', 1903, 'A Porto Alegre club founded by German and English immigrants.', 'BR', 'football', 'South America', 'Won the 1983 Intercontinental Cup, beating Hamburg in Tokyo.'),
  (143, 'Botafogo', 1904, 'A Rio club and the team of Garrincha and Nilton Santos.', 'BR', 'football', 'South America', 'Garrincha''s dribbling made the club beloved across Brazil in the 1950s.'),
  (144, 'Atlético Mineiro', 1908, 'A Belo Horizonte club and one of Brazil''s biggest.', 'BR', 'football', 'South America', 'Won its first Copa Libertadores in 2013, beating Olimpia in the final.'),
  (145, 'Internacional', 1909, 'A Porto Alegre club, the great rival of Grêmio.', 'BR', 'football', 'South America', 'Won the 2006 Copa Libertadores and followed it with the Club World Cup.'),
  (146, 'Corinthians', 1910, 'A São Paulo giant founded by railway workers inspired by an English amateur side.', 'BR', 'football', 'South America', 'Named after the English Corinthian FC, which toured Brazil that year.'),
  (147, 'Santos', 1912, 'A coastal São Paulo club and the home of Pelé for 18 years.', 'BR', 'football', 'South America', 'Pelé scored over 1,000 of his career goals in a Santos shirt.'),
  (148, 'Palmeiras', 1914, 'A São Paulo club founded by Italian immigrants as Palestra Italia.', 'BR', 'football', 'South America', 'Renamed itself in 1942 when Brazil entered the war against the Axis.'),
  (149, 'Colo-Colo', 1925, 'Chile''s most popular club, named after a Mapuche chief.', 'CL', 'football', 'South America', 'The only Chilean club to win the Copa Libertadores, in 1991.'),
  (150, 'Barcelona SC', 1925, 'An Ecuadorian club from Guayaquil, named after the Catalan city.', 'EC', 'football', 'South America', 'Has the largest following in Ecuador despite never winning the Copa Libertadores.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO sport_clubs (id, short_name, founded_year, description, countries, sport, region, fun_fact) VALUES
  (151, 'Pachuca', 1901, 'Mexico''s oldest football club, founded by Cornish miners in the state of Hidalgo.', 'MX', 'football', 'Central America', 'The Mexican championship trophy was first played for in 1902, won by Pachuca.'),
  (152, 'Guadalajara (Chivas)', 1906, 'A Guadalajara club famous for fielding only Mexican players.', 'MX', 'football', 'Central America', 'Founded by a Belgian, Edgar Everaert, who insisted on an all-Mexican squad.'),
  (153, 'Club América', 1916, 'A Mexico City giant and one of the country''s most successful clubs.', 'MX', 'football', 'Central America', 'Founded by students on Columbus Day, hence the name ''América''.'),
  (154, 'Cruz Azul', 1927, 'A Mexico City club founded as the team of a cement company.', 'MX', 'football', 'Central America', 'The ''cement makers'' won seven consecutive league titles in the 1970s.'),
  (155, 'UNAM Pumas', 1954, 'The club of the National Autonomous University of Mexico.', 'MX', 'football', 'Central America', 'Hugo Sánchez began his career at Pumas before moving to Atlético Madrid.'),
  (156, 'Al Ahly', 1907, 'Egypt''s most successful club, from Cairo, founded by students.', 'EG', 'football', 'Northern Africa', 'Often called the most decorated club in African football history.'),
  (157, 'Zamalek', 1911, 'A Cairo club, the great rival of Al Ahly.', 'EG', 'football', 'Northern Africa', 'Was founded as Qasr El Nil Club and renamed Zamalek in 1952.'),
  (158, 'Hearts of Oak', 1911, 'Ghana''s oldest and one of its most successful clubs, from Accra.', 'GH', 'football', 'Western Africa', 'Won the 2000 CAF Champions League, its first continental crown.'),
  (159, 'Espérance de Tunis', 1919, 'A Tunisian giant, from the capital Tunis.', 'TN', 'football', 'Northern Africa', 'Founded in a Tunis café by a group of young students.'),
  (160, 'Wydad AC', 1937, 'A Casablanca club and one of Morocco''s most successful.', 'MA', 'football', 'Northern Africa', 'The name ''Wydad'' means ''love'' in Arabic, chosen to bind the club together.'),
  (161, 'Orlando Pirates', 1937, 'A Soweto club and one of South Africa''s most popular.', 'ZA', 'football', 'Southern Africa', 'Was the first South African club to win the CAF Champions League, in 1995.'),
  (162, 'TP Mazembe', 1939, 'A DR Congo club from Lubumbashi, a continental powerhouse.', 'CD', 'football', 'Middle Africa', 'Became the first African side to reach a Club World Cup final, in 2010.'),
  (163, 'Mamelodi Sundowns', 1970, 'A Pretoria club owned by billionaire Patrice Motsepe.', 'ZA', 'football', 'Southern Africa', 'Won the 2016 CAF Champions League with a squad nicknamed the ''Brazilians''.'),
  (164, 'Mohun Bagan', 1889, 'One of Asia''s oldest football clubs, from Kolkata.', 'IN', 'football', 'Southern Asia', 'In 1911 became the first Indian club to beat a British team for the IFA Shield.'),
  (165, 'Maccabi Tel Aviv', 1906, 'Israel''s most successful club, from Tel Aviv.', 'IL', 'football', 'Western Asia', 'Was founded as a sports club before the state of Israel existed.'),
  (166, 'Al Ittihad', 1927, 'A Jeddah club and one of Saudi Arabia''s oldest and biggest.', 'SA', 'football', 'Western Asia', 'Won back-to-back AFC Champions League titles in 2004 and 2005.'),
  (167, 'Esteghlal', 1945, 'A Tehran club founded as ''Taj'', renamed after the Iranian Revolution.', 'IR', 'football', 'Southern Asia', 'Won the 1970 Asian Club Championship, the first Iranian club to do so.'),
  (168, 'Persepolis', 1963, 'Iran''s most popular club, from Tehran.', 'IR', 'football', 'Southern Asia', 'The Tehran derby against Esteghlal is one of Asia''s biggest matches.'),
  (169, 'Al Hilal', 1957, 'A Riyadh club and one of Asia''s most successful.', 'SA', 'football', 'Western Asia', 'Has won the AFC Champions League more times than any other club.'),
  (170, 'Al Nassr', 1955, 'A Riyadh club that became world-famous by signing Cristiano Ronaldo in 2022.', 'SA', 'football', 'Western Asia', 'Ronaldo''s arrival made it one of the most-followed clubs in the world overnight.'),
  (171, 'Urawa Red Diamonds', 1950, 'A Saitama club founded as the football team of Mitsubishi Heavy Industries.', 'JP', 'football', 'Eastern Asia', 'The ''Red Diamonds'' name comes from the Mitsubishi logo.'),
  (172, 'Cincinnati Reds', 1869, 'The first openly all-professional baseball team in history.', 'US', 'baseball', 'Northern America', 'The 1869 Red Stockings went 57-0 on a nationwide tour.'),
  (173, 'Atlanta Braves', 1871, 'The oldest continuously operating professional sports franchise in the Americas.', 'US', 'baseball', 'Northern America', 'Began as the Boston Red Stockings, played in Milwaukee, then Atlanta.'),
  (174, 'Chicago Cubs', 1876, 'A charter member of the National League, playing at Wrigley Field since 1916.', 'US', 'baseball', 'Northern America', 'Went 108 years between World Series titles, finally winning in 2016.'),
  (175, 'St. Louis Cardinals', 1882, 'One of baseball''s most decorated clubs, with 11 World Series titles.', 'US', 'baseball', 'Northern America', 'The second-most World Series wins in MLB, behind only the Yankees.'),
  (176, 'San Francisco Giants', 1883, 'A club founded in New York as the Gothams, later moved to San Francisco.', 'US', 'baseball', 'Northern America', 'Won the 1888 and 1889 World Series while still based in New York.'),
  (177, 'Los Angeles Dodgers', 1884, 'A club founded in Brooklyn that became the first MLB team on the West Coast.', 'US', 'baseball', 'Northern America', 'Broke baseball''s colour barrier by signing Jackie Robinson in 1947.'),
  (178, 'Philadelphia Phillies', 1883, 'The longest continuously operating one-name, one-city franchise in MLB.', 'US', 'baseball', 'Northern America', 'Took 97 years to win its first World Series, in 1980.'),
  (179, 'Pittsburgh Pirates', 1882, 'A Pittsburgh club that played in the first modern World Series in 1903.', 'US', 'baseball', 'Northern America', 'Began as the Allegheny Base Ball Club before becoming the Pirates.'),
  (180, 'New York Yankees', 1903, 'The most successful club in MLB history, with 27 World Series titles.', 'US', 'baseball', 'Northern America', 'Began in Baltimore as the Orioles before moving to New York in 1903.'),
  (181, 'Boston Red Sox', 1901, 'A charter member of the American League, playing at Fenway Park since 1912.', 'US', 'baseball', 'Northern America', 'Sold Babe Ruth to the Yankees in 1919, starting the ''Curse of the Bambino''.'),
  (182, 'Detroit Tigers', 1901, 'A charter member of the American League, from Detroit.', 'US', 'baseball', 'Northern America', 'Ty Cobb played for the Tigers for 22 seasons, hitting .366 over his career.'),
  (183, 'Arizona Cardinals', 1898, 'The oldest continuously operating professional football club in the United States.', 'US', 'American football', 'Northern America', 'Began in Chicago as the Morgan Athletic Club, moved to St. Louis, then Arizona.'),
  (184, 'Green Bay Packers', 1919, 'The only community-owned major professional sports franchise in the United States.', 'US', 'American football', 'Northern America', 'Has won 13 NFL championships, more than any other club.'),
  (185, 'Chicago Bears', 1919, 'A founding franchise of the NFL, from Chicago.', 'US', 'American football', 'Northern America', 'Began as the Decatur Staleys, a company team of the A.E. Staley food company.'),
  (186, 'New York Giants', 1925, 'A New York NFL franchise with eight championship titles.', 'US', 'American football', 'Northern America', 'Owned by the Mara family since its founding in 1925.'),
  (187, 'Detroit Lions', 1930, 'A Detroit NFL franchise founded as the Portsmouth Spartans in Ohio.', 'US', 'American football', 'Northern America', 'Moved to Detroit in 1934 and was renamed the Lions.'),
  (188, 'Washington Commanders', 1932, 'A Washington D.C. NFL franchise founded as the Boston Braves.', 'US', 'American football', 'Northern America', 'Moved from Boston to Washington in 1937.'),
  (189, 'Philadelphia Eagles', 1933, 'A Philadelphia NFL franchise, famous for its passionate fans.', 'US', 'American football', 'Northern America', 'The ''Philly Special'' trick play won the franchise its first Super Bowl in 2018.'),
  (190, 'Pittsburgh Steelers', 1933, 'A Pittsburgh NFL franchise and six-time Super Bowl champion.', 'US', 'American football', 'Northern America', 'Has won six Super Bowls, tied for the most in NFL history.'),
  (191, 'Los Angeles Rams', 1936, 'An NFL franchise founded in Cleveland, later in St. Louis, now back in Los Angeles.', 'US', 'American football', 'Northern America', 'The first NFL team to put logos on its helmets, in 1948.'),
  (192, 'Cleveland Browns', 1946, 'An NFL franchise named after its first coach and co-founder, Paul Brown.', 'US', 'American football', 'Northern America', 'Won all four championships of the rival AAFC before joining the NFL in 1950.'),
  (193, 'San Francisco 49ers', 1946, 'An NFL franchise named after the 1849 Gold Rush prospectors.', 'US', 'American football', 'Northern America', 'Won five Super Bowls between 1981 and 1995, all with Hall of Fame quarterbacks.'),
  (194, 'Indianapolis Colts', 1953, 'An NFL franchise founded in Baltimore, later relocated to Indianapolis.', 'US', 'American football', 'Northern America', 'Was the Baltimore Colts when Johnny Unitas led the ''Greatest Game Ever Played'' in 1958.'),
  (195, 'Dallas Cowboys', 1960, 'A Texas NFL franchise nicknamed ''America''s Team''.', 'US', 'American football', 'Northern America', 'One of the most valuable sports franchises in the world, worth billions.'),
  (196, 'Kansas City Chiefs', 1960, 'An NFL franchise founded as the Dallas Texans, later moved to Kansas City.', 'US', 'American football', 'Northern America', 'Won Super Bowl IV in 1970 and then waited 50 years for the next, in 2020.'),
  (197, 'Las Vegas Raiders', 1960, 'An NFL franchise founded in Oakland, later moved to LA and Las Vegas.', 'US', 'American football', 'Northern America', 'The pirate-themed ''Just Win, Baby'' motto was coined by owner Al Davis.'),
  (198, 'New England Patriots', 1960, 'An NFL franchise founded as the Boston Patriots, now based in Foxborough.', 'US', 'American football', 'Northern America', 'Won six Super Bowls under Tom Brady and Bill Belichick from 2001 to 2019.'),
  (199, 'Miami Dolphins', 1966, 'An NFL franchise from Miami, the only team with a perfect season.', 'US', 'American football', 'Northern America', 'The 1972 Dolphins went 17-0, the only undefeated season in NFL history.'),
  (200, 'Minnesota Vikings', 1961, 'An NFL franchise from Minneapolis, known for its purple and gold colours.', 'US', 'American football', 'Northern America', 'Reached four Super Bowls in the 1970s but lost them all.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO sport_clubs (id, short_name, founded_year, description, countries, sport, region, fun_fact) VALUES
  (201, 'Montreal Canadiens', 1909, 'The oldest continuously operating professional ice hockey club in the world.', 'CA', 'ice hockey', 'Northern America', 'Has won 24 Stanley Cups, more than any other NHL club.'),
  (202, 'Toronto Maple Leafs', 1917, 'A Toronto NHL franchise and one of the ''Original Six''.', 'CA', 'ice hockey', 'Northern America', 'Has won 13 Stanley Cups but none since 1967.'),
  (203, 'Boston Bruins', 1924, 'The first American NHL franchise, from Boston.', 'US', 'ice hockey', 'Northern America', 'Was the first NHL team based in the United States.'),
  (204, 'Chicago Blackhawks', 1926, 'An NHL franchise from Chicago, one of the ''Original Six''.', 'US', 'ice hockey', 'Northern America', 'Named after Chief Black Hawk of the Sauk nation.'),
  (205, 'Detroit Red Wings', 1926, 'An NHL franchise from Detroit, one of the ''Original Six''.', 'US', 'ice hockey', 'Northern America', 'The ''winged wheel'' logo reflects Detroit''s automotive heritage.'),
  (206, 'New York Rangers', 1926, 'An NHL franchise from New York, one of the ''Original Six''.', 'US', 'ice hockey', 'Northern America', 'Won the Stanley Cup in its second season, 1928.'),
  (207, 'Edmonton Oilers', 1972, 'An NHL franchise from Edmonton, home of the 1980s Wayne Gretzky dynasty.', 'CA', 'ice hockey', 'Northern America', 'Won five Stanley Cups in seven years between 1984 and 1990.'),
  (208, 'Pittsburgh Penguins', 1967, 'An NHL franchise from Pittsburgh, home of Mario Lemieux and Sidney Crosby.', 'US', 'ice hockey', 'Northern America', 'Saved from bankruptcy in 1999 when Lemieux bought the club.'),
  (209, 'Philadelphia Flyers', 1967, 'An NHL franchise from Philadelphia, nicknamed the ''Broad Street Bullies''.', 'US', 'ice hockey', 'Northern America', 'The ''Bullies'' won back-to-back Stanley Cups in 1974 and 1975.'),
  (210, 'Los Angeles Kings', 1967, 'An NHL franchise from Los Angeles, transformed by the arrival of Wayne Gretzky.', 'US', 'ice hockey', 'Northern America', 'Gretzky''s 1988 trade from Edmonton popularised hockey in the American West.'),
  (211, 'New York Islanders', 1972, 'An NHL franchise from Long Island, winners of four straight Stanley Cups.', 'US', 'ice hockey', 'Northern America', 'Won four consecutive Stanley Cups from 1980 to 1983.'),
  (212, 'Boston Celtics', 1946, 'An NBA franchise from Boston, one of the most successful in basketball history.', 'US', 'basketball', 'Northern America', 'Won a record 18 NBA championships, the most in league history.'),
  (213, 'New York Knicks', 1946, 'An NBA franchise from New York, playing at Madison Square Garden.', 'US', 'basketball', 'Northern America', 'One of only two founding NBA clubs never to have relocated.'),
  (214, 'Golden State Warriors', 1946, 'An NBA franchise founded in Philadelphia, now based in San Francisco.', 'US', 'basketball', 'Northern America', 'Won the first ever NBA championship in 1947, then as the Philadelphia Warriors.'),
  (215, 'Philadelphia 76ers', 1946, 'An NBA franchise from Philadelphia, founded as the Syracuse Nationals.', 'US', 'basketball', 'Northern America', 'Wilt Chamberlain scored 100 points in a single game for the club in 1962.'),
  (216, 'Los Angeles Lakers', 1947, 'An NBA franchise founded in Minneapolis, named after Minnesota''s lakes.', 'US', 'basketball', 'Northern America', 'Kept the ''Lakers'' name even after moving to land-locked Los Angeles in 1960.'),
  (217, 'Detroit Pistons', 1941, 'An NBA franchise founded as the Fort Wayne Zollner Pistons.', 'US', 'basketball', 'Northern America', 'Named after the pistons made by owner Fred Zollner''s manufacturing company.'),
  (218, 'Sacramento Kings', 1945, 'An NBA franchise founded as the Rochester Royals, the oldest continuously operating club.', 'US', 'basketball', 'Northern America', 'Has relocated more times than any other NBA franchise: Rochester, Cincinnati, Kansas City, Sacramento.'),
  (219, 'Chicago Bulls', 1966, 'An NBA franchise from Chicago, home of the Michael Jordan dynasty.', 'US', 'basketball', 'Northern America', 'Won six NBA championships in the 1990s, two ''three-peats'' under Jordan.'),
  (220, 'San Antonio Spurs', 1967, 'An NBA franchise founded as the Dallas Chaparrals of the rival ABA.', 'US', 'basketball', 'Northern America', 'Won five NBA championships in 15 years under coach Gregg Popovich.'),
  (221, 'Miami Heat', 1988, 'An NBA franchise from Miami, home of the ''Big Three'' era.', 'US', 'basketball', 'Northern America', 'LeBron James, Dwyane Wade and Chris Bosh won two titles together from 2010 to 2014.'),
  (222, 'Real Madrid Baloncesto', 1931, 'The basketball section of Real Madrid and the most successful club in Europe.', 'ES', 'basketball', 'Southern Europe', 'Has won a record 11 EuroLeague titles.'),
  (223, 'FC Barcelona Bàsquet', 1926, 'The basketball section of FC Barcelona, from Catalonia.', 'ES', 'basketball', 'Southern Europe', 'Won two EuroLeague titles, in 2003 and 2010.'),
  (224, 'Olimpia Milano', 1936, 'Italy''s most successful basketball club, from Milan.', 'IT', 'basketball', 'Southern Europe', 'Has won 28 Italian league championships, a national record.'),
  (225, 'KK Partizan', 1945, 'A Belgrade basketball club, 1992 European champions.', 'RS', 'basketball', 'Southern Europe', 'Won the 1992 European Cup with a squad that could not travel because of war sanctions.'),
  (226, 'KK Crvena Zvezda', 1945, 'A Belgrade basketball club, the great rival of Partizan.', 'RS', 'basketball', 'Southern Europe', 'Known in English as Red Star Belgrade.'),
  (227, 'Žalgiris Kaunas', 1944, 'A Lithuanian basketball club, 1999 EuroLeague champions.', 'LT', 'basketball', 'Northern Europe', 'Tyus Edney''s buzzer-beating layup in the 1999 Final Four final became club folklore.'),
  (228, 'Barbarian FC', 1890, 'An invitational rugby club with no ground or players of its own.', 'GB', 'rugby union', 'Northern Europe', 'Famous for the 1973 try against the All Blacks, voted the greatest of all time.'),
  (229, 'Blackheath FC', 1858, 'The oldest open rugby club in the world, from south-east London.', 'GB', 'rugby union', 'Northern Europe', 'Helped draft the original laws of rugby football in 1871.'),
  (230, 'Bath Rugby', 1865, 'An English rugby club from the city of Bath, dominant in the 1980s.', 'GB', 'rugby union', 'Northern Europe', 'Won six English league titles in the 1980s and 1990s.'),
  (231, 'Harlequins', 1866, 'A London rugby club famous for its quartered shirts.', 'GB', 'rugby union', 'Northern Europe', 'The ''quins'' style of play was once known for flair and trickery.'),
  (232, 'Wasps', 1867, 'A London rugby club, now based in Coventry.', 'GB', 'rugby union', 'Northern Europe', 'Founded at a meeting in a London pub where the wasp-like striped shirts were chosen.'),
  (233, 'Leicester Tigers', 1880, 'The most successful English rugby club, from Leicester.', 'GB', 'rugby union', 'Northern Europe', 'Has won ten English league titles, more than any other club.'),
  (234, 'Gloucester Rugby', 1873, 'A West Country rugby club, playing at Kingsholm since 1891.', 'GB', 'rugby union', 'Northern Europe', 'The ''Cherry and Whites'' have a fierce local rivalry with Bath.'),
  (235, 'Saracens', 1876, 'A London rugby club, dominant in Europe in the 2010s.', 'GB', 'rugby union', 'Northern Europe', 'Won three European Champions Cups in four years from 2016 to 2019.'),
  (236, 'Northampton Saints', 1880, 'An English rugby club from Northampton, 2000 European champions.', 'GB', 'rugby union', 'Northern Europe', 'Won the 2000 Heineken Cup against Munster in the final.'),
  (237, 'Leinster Rugby', 1875, 'An Irish provincial rugby team, one of the most successful in Europe.', 'IE', 'rugby union', 'Northern Europe', 'Has won five European Champions Cups, more than any other club.'),
  (238, 'Munster Rugby', 1879, 'An Irish provincial rugby team, famous for its passionate Thomond Park support.', 'IE', 'rugby union', 'Northern Europe', 'Was the first club to beat the All Blacks, in 1978.'),
  (239, 'Stade Toulousain', 1890, 'A French rugby club, the most successful in Europe.', 'FR', 'rugby union', 'Western Europe', 'Has won six European Champions Cups, the most of any club.'),
  (240, 'Marylebone Cricket Club', 1787, 'The guardian of the Laws of Cricket and owner of Lord''s Cricket Ground.', 'GB', 'cricket', 'Northern Europe', 'Codified the Laws of Cricket in 1788, which still govern the game today.'),
  (241, 'Melbourne Cricket Club', 1838, 'The oldest cricket club in Australia, owner of the Melbourne Cricket Ground.', 'AU', 'cricket', 'Australia & New Zealand', 'The MCG hosted the first ever Test match, in 1877.'),
  (242, 'Sussex CCC', 1839, 'The oldest of the 18 first-class county cricket clubs in England.', 'GB', 'cricket', 'Northern Europe', 'Won the first official County Championship titles in the 1870s.'),
  (243, 'Surrey CCC', 1845, 'A county cricket club based at The Oval in London.', 'GB', 'cricket', 'Northern Europe', 'The Oval hosted the first ever Test match on English soil, in 1880.'),
  (244, 'Kent CCC', 1859, 'A county cricket club from south-east England.', 'GB', 'cricket', 'Northern Europe', 'Won the first officially recognised County Championship in 1890.'),
  (245, 'Yorkshire CCC', 1863, 'The most successful county cricket club in England.', 'GB', 'cricket', 'Northern Europe', 'Has won 33 County Championship titles, more than any other county.'),
  (246, 'Lancashire CCC', 1864, 'A county cricket club from Manchester, playing at Old Trafford.', 'GB', 'cricket', 'Northern Europe', 'The ''Roses'' rivalry with Yorkshire is one of cricket''s oldest.'),
  (247, 'The Royal and Ancient Golf Club', 1754, 'The governing body of golf, based at St Andrews in Scotland.', 'GB', 'golf', 'Northern Europe', 'Golf has been played at St Andrews Links for over 600 years.'),
  (248, 'Honourable Company of Edinburgh Golfers', 1744, 'The oldest golf club in the world, now based at Muirfield.', 'GB', 'golf', 'Northern Europe', 'Wrote golf''s original 13 rules in 1744.'),
  (249, 'Leander Club', 1818, 'One of the world''s oldest rowing clubs, based at Henley-on-Thames.', 'GB', 'rowing', 'Northern Europe', 'Its oarsmen have won more Olympic medals than those of any other rowing club.'),
  (250, 'Royal Yacht Squadron', 1815, 'The most prestigious yacht club in the world, based at Cowes on the Isle of Wight.', 'GB', 'sailing', 'Northern Europe', 'Started the America''s Cup by hosting the 1851 race around the Isle of Wight.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO sport_clubs (id, short_name, founded_year, description, countries, sport, region, fun_fact) VALUES
  (251, 'All England Lawn Tennis Club', 1868, 'The home of Wimbledon, the oldest tennis tournament in the world.', 'GB', 'tennis', 'Northern Europe', 'Was founded as a croquet club; tennis was only added in 1875.'),
  (252, 'Melbourne Football Club', 1858, 'Widely regarded as the oldest football club of any code in the world.', 'AU', 'Australian rules football', 'Australia & New Zealand', 'Helped write the first rules of Australian rules football in 1859.'),
  (253, 'Geelong Football Club', 1859, 'The second-oldest AFL club, nicknamed the Cats.', 'AU', 'Australian rules football', 'Australia & New Zealand', 'Won the 2022 AFL premiership, its first in 16 years.'),
  (254, 'Carlton Football Club', 1864, 'One of the AFL''s oldest and most successful clubs.', 'AU', 'Australian rules football', 'Australia & New Zealand', 'Won the first VFL premiership in 1897.'),
  (255, 'Essendon Football Club', 1872, 'An AFL club known as the Bombers, with 16 premierships.', 'AU', 'Australian rules football', 'Australia & New Zealand', 'Shares the record of 16 VFL/AFL premierships with Carlton.'),
  (256, 'Port Adelaide Football Club', 1870, 'The most successful football club in South Australian history.', 'AU', 'Australian rules football', 'Australia & New Zealand', 'Won a record 36 SANFL premierships before joining the AFL in 1997.'),
  (257, 'Wigan Warriors', 1872, 'The most successful club in English rugby league history.', 'GB', 'rugby league', 'Northern Europe', 'Won eight consecutive Challenge Cup finals from 1988 to 1995.'),
  (258, 'Hull FC', 1865, 'A rugby league club from Hull, one of the sport''s oldest.', 'GB', 'rugby league', 'Northern Europe', 'The Hull derby with Hull KR is one of the fiercest in rugby league.'),
  (259, 'South Sydney Rabbitohs', 1908, 'The most successful club in Australian rugby league history.', 'AU', 'rugby league', 'Australia & New Zealand', 'Won 21 premierships, a national record, but was expelled from the league in 1999 before returning in 2002.'),
  (260, 'Sydney Roosters', 1908, 'An NRL club founded as Eastern Suburbs, one of the foundation clubs.', 'AU', 'rugby league', 'Australia & New Zealand', 'The only club to have played in every season of top-flight Australian rugby league.'),
  (261, 'St George Illawarra Dragons', 1921, 'An NRL club with the record for most consecutive premierships.', 'AU', 'rugby league', 'Australia & New Zealand', 'The original St George won 11 consecutive premierships from 1956 to 1966.'),
  (262, 'Modena Volley', 1968, 'Italy''s most successful volleyball club, from Modena.', 'IT', 'volleyball', 'Southern Europe', 'Has won 12 Italian league championships, a national record.'),
  (263, 'Trentino Volley', 2000, 'A successful Italian volleyball club from Trento.', 'IT', 'volleyball', 'Southern Europe', 'Won four consecutive CEV Champions League titles from 2009 to 2012.'),
  (264, 'Royal Caledonian Curling Club', 1838, 'The ''mother club'' of curling, the sport''s governing body.', 'GB', 'curling', 'Northern Europe', 'Recognised worldwide as the guardian of the rules of curling.'),
  (265, 'THW Kiel', 1904, 'Germany''s most successful handball club, from Kiel.', 'DE', 'handball', 'Western Europe', 'Has won more German handball championships than any other club.'),
  (266, 'Buffalo Bills', 1960, 'An NFL franchise from Buffalo, the only team to reach four straight Super Bowls.', 'US', 'American football', 'Northern America', 'Lost four consecutive Super Bowls from 1991 to 1994, a record no club wants.'),
  (267, 'Denver Broncos', 1960, 'An NFL franchise from Denver, a founding member of the AFL.', 'US', 'American football', 'Northern America', 'Won back-to-back Super Bowls in 1998 and 1999 with John Elway at quarterback.'),
  (268, 'Nashville Titans', 1960, 'An NFL franchise founded as the Houston Oilers, now based in Tennessee.', 'US', 'American football', 'Northern America', 'Was the Houston Oilers for 36 years before relocating to Nashville in 1997.'),
  (269, 'Buffalo Sabres', 1970, 'An NHL franchise from Buffalo, founded with the Canucks in the 1970 expansion.', 'US', 'ice hockey', 'Northern America', 'Gilbert Perreault was the club''s first draft pick and played 17 seasons in Buffalo.'),
  (270, 'Vancouver Canucks', 1970, 'An NHL franchise from Vancouver, Canada''s West Coast team.', 'CA', 'ice hockey', 'Northern America', 'Reached the 2011 Stanley Cup final, losing Game 7 to the Boston Bruins.'),
  (271, 'Calgary Flames', 1972, 'An NHL franchise founded in Atlanta, now based in Calgary.', 'CA', 'ice hockey', 'Northern America', 'Won the 1989 Stanley Cup, the only title in club history.')
ON CONFLICT (id) DO NOTHING;

