// Per-game UI text dictionaries for single-player and multiplayer screens.
// History strings are identical to the original pages (moved verbatim).
// Mountains strings mirror them with mountain-appropriate wording.

import { baseUiText } from './i18n.js';

export const SP_UI = {
  history: {
    en: {
      ...baseUiText.en,
      title: 'Which happened earlier?',
      subtitle: 'Pick the older historical event',
      loading: 'Loading events from Supabase…',
      settingsTitle: '⚙️ Game Settings',
      startGame: 'Start Game',
      streak: 'Streak',
      streakProgress: '🔥 Rank Progress',
      nextReward: 'Next rank',
      milestone: 'Milestone',
      reached: 'reached!',
      correct: 'Correct!',
      wrong: 'Wrong —',
      earlierThan: 'was earlier than',
      yearsApart: '{n} years apart',
      or: 'or',
      next: 'Next →',
      filters: '⚙️ Filters',
      youWon: 'You Won!',
      winSubtitle: 'You reached a streak of 50!',
      eventsAvailable: 'events available',
      needMore: 'Pick broader filters — need at least',
      toPlay: 'to play',
      minValueLabel: 'Start Year',
      maxValueLabel: 'End Year',
      groupLabel: 'Region',
      placeholderMinValue: 'e.g. 1500',
      placeholderMaxValue: 'e.g. 2000',
      year: 'Year',
      preparing: 'Preparing next events…',
      winRank: 'King of Historical Knowledge',
      missingEnv: 'Missing Supabase env vars',
      error: 'Error:',
      crash: 'Crash:',
      needEventsTable: 'Need at least 2 events in the table.',
      pickAriaLabel: 'Pick this event as earlier',
      backToHomescreen: '🏠 Back to Games',
    },
    cs: {
      ...baseUiText.cs,
      title: 'Co se stalo dříve?',
      subtitle: 'Vyber starší historickou událost',
      loading: 'Načítání událostí ze Supabase…',
      settingsTitle: '⚙️ Nastavení hry',
      startGame: 'Spustit hru',
      streak: 'Série',
      streakProgress: '🔥 Průběh hodnosti',
      nextReward: 'Další hodnost',
      milestone: 'Milník',
      reached: 'dosažen!',
      correct: 'Správně!',
      wrong: 'Špatně —',
      earlierThan: 'bylo dříve než',
      yearsApart: '{n} let od sebe',
      or: 'nebo',
      next: 'Další →',
      filters: '⚙️ Filtry',
      youWon: 'Vyhrál jsi!',
      winSubtitle: 'Dosáhl jsi série 50!',
      eventsAvailable: 'událostí k dispozici',
      needMore: 'Vyber méně restriktivní filtry — potřebuješ alespoň',
      toPlay: 'k hraní',
      minValueLabel: 'Od roku',
      maxValueLabel: 'Do roku',
      groupLabel: 'Region',
      placeholderMinValue: 'např. 1500',
      placeholderMaxValue: 'např. 2000',
      year: 'Rok',
      preparing: 'Příprava dalších událostí…',
      winRank: 'Král historických znalostí',
      error: 'Chyba:',
      crash: 'Pád:',
      needEventsTable: 'V tabulce musí být alespoň 2 události.',
      missingEnv: 'Chybí Supabase proměnné prostředí',
      pickAriaLabel: 'Vyber tuto událost jako dřívější',
      backToHomescreen: '🏠 Zpět na hry',
    },
    it: {
      ...baseUiText.it,
      title: 'Quale è avvenuto prima?',
      subtitle: "Scegli l'evento storico più antico",
      loading: 'Caricamento eventi da Supabase…',
      settingsTitle: '⚙️ Impostazioni di gioco',
      startGame: 'Inizia',
      streak: 'Serie',
      streakProgress: '🔥 Progresso grado',
      nextReward: 'Prossimo grado',
      milestone: 'Traguardo',
      reached: 'raggiunto!',
      correct: 'Corretto!',
      wrong: 'Sbagliato —',
      earlierThan: 'era prima di',
      yearsApart: '{n} anni di distanza',
      or: 'oppure',
      next: 'Avanti →',
      filters: '⚙️ Filtri',
      youWon: 'Hai Vinto!',
      winSubtitle: 'Hai raggiunto una serie di 50!',
      eventsAvailable: 'eventi disponibili',
      needMore: 'Allarga i filtri — servono almeno',
      toPlay: 'per giocare',
      minValueLabel: 'Anno inizio',
      maxValueLabel: 'Anno fine',
      groupLabel: 'Regione',
      placeholderMinValue: 'es. 1500',
      placeholderMaxValue: 'es. 2000',
      year: 'Anno',
      preparing: 'Preparazione prossimi eventi…',
      winRank: 'Re della conoscenza storica',
      error: 'Errore:',
      crash: 'Errore critico:',
      needEventsTable: 'Servono almeno 2 eventi nella tabella.',
      missingEnv: 'Variabili d\'ambiente Supabase mancanti',
      pickAriaLabel: "Scegli questo evento come più antico",
      backToHomescreen: '🏠 Torna ai giochi',
    },
  },

  mountains: {
    en: {
      ...baseUiText.en,
      title: 'Which mountain is higher?',
      subtitle: 'Pick the taller peak',
      loading: 'Loading mountains from Supabase…',
      settingsTitle: '⚙️ Game Settings',
      startGame: 'Start Game',
      streak: 'Streak',
      streakProgress: '🔥 Rank Progress',
      nextReward: 'Next rank',
      milestone: 'Milestone',
      reached: 'reached!',
      correct: 'Correct!',
      wrong: 'Wrong —',
      earlierThan: 'is higher than',
      yearsApart: '{n} m apart',
      or: 'or',
      next: 'Next →',
      filters: '⚙️ Filters',
      youWon: 'You Won!',
      winSubtitle: 'You reached a streak of 50!',
      eventsAvailable: 'mountains available',
      needMore: 'Pick broader filters — need at least',
      toPlay: 'to play',
      minValueLabel: 'Min Elevation (m)',
      maxValueLabel: 'Max Elevation (m)',
      groupLabel: 'Region',
      placeholderMinValue: 'e.g. 2000',
      placeholderMaxValue: 'e.g. 8000',
      year: 'Elevation',
      preparing: 'Preparing next mountains…',
      winRank: 'King of the Peaks',
      missingEnv: 'Missing Supabase env vars',
      error: 'Error:',
      crash: 'Crash:',
      needEventsTable: 'Need at least 2 mountains in the table.',
      pickAriaLabel: 'Pick this mountain as higher',
      backToHomescreen: '🏠 Back to Games',
    },
    cs: {
      ...baseUiText.cs,
      title: 'Která hora je vyšší?',
      subtitle: 'Vyber vyšší horu',
      loading: 'Načítání hor ze Supabase…',
      settingsTitle: '⚙️ Nastavení hry',
      startGame: 'Spustit hru',
      streak: 'Série',
      streakProgress: '🔥 Průběh hodnosti',
      nextReward: 'Další hodnost',
      milestone: 'Milník',
      reached: 'dosažen!',
      correct: 'Správně!',
      wrong: 'Špatně —',
      earlierThan: 'je vyšší než',
      yearsApart: '{n} m od sebe',
      or: 'nebo',
      next: 'Další →',
      filters: '⚙️ Filtry',
      youWon: 'Vyhrál jsi!',
      winSubtitle: 'Dosáhl jsi série 50!',
      eventsAvailable: 'hor k dispozici',
      needMore: 'Vyber méně restriktivní filtry — potřebuješ alespoň',
      toPlay: 'k hraní',
      minValueLabel: 'Min. nadmořská výška (m)',
      maxValueLabel: 'Max. nadmořská výška (m)',
      groupLabel: 'Region',
      placeholderMinValue: 'např. 2000',
      placeholderMaxValue: 'např. 8000',
      year: 'Nadmořská výška',
      preparing: 'Příprava dalších hor…',
      winRank: 'Král vrcholů',
      error: 'Chyba:',
      crash: 'Pád:',
      needEventsTable: 'V tabulce musí být alespoň 2 hory.',
      missingEnv: 'Chybí Supabase proměnné prostředí',
      pickAriaLabel: 'Vyber tuto horu jako vyšší',
      backToHomescreen: '🏠 Zpět na hry',
    },
    it: {
       ...baseUiText.it,
       title: 'Quale montagna è più alta?',
       subtitle: 'Scegli la vetta più alta',
       loading: 'Caricamento montagne da Supabase…',
       settingsTitle: '⚙️ Impostazioni di gioco',
       startGame: 'Inizia',
       streak: 'Serie',
       streakProgress: '🔥 Progresso grado',
       nextReward: 'Prossimo grado',
       milestone: 'Traguardo',
       reached: 'raggiunto!',
       correct: 'Corretto!',
       wrong: 'Sbagliato —',
       earlierThan: 'è più alta di',
       yearsApart: '{n} m di distanza',
       or: 'oppure',
       next: 'Avanti →',
       filters: '⚙️ Filtri',
       youWon: 'Hai Vinto!',
       winSubtitle: 'Hai raggiunto una serie di 50!',
       eventsAvailable: 'montagne disponibili',
       needMore: 'Allarga i filtri — servono almeno',
       toPlay: 'per giocare',
       minValueLabel: 'Altitudine min (m)',
       maxValueLabel: 'Altitudine max (m)',
       groupLabel: 'Regione',
       placeholderMinValue: 'es. 2000',
       placeholderMaxValue: 'es. 8000',
       year: 'Altitudine',
       preparing: 'Preparazione prossime montagne…',
       winRank: 'Re delle vette',
       error: 'Errore:',
       crash: 'Errore critico:',
       needEventsTable: 'Servono almeno 2 montagne nella tabella.',
       missingEnv: 'Variabili d\'ambiente Supabase mancanti',
       pickAriaLabel: 'Scegli questa montagna come più alta',
       backToHomescreen: '🏠 Torna ai giochi',
     },
   },
   rivers: {
     en: {
       ...baseUiText.en,
       title: 'Which river is longer?',
       subtitle: 'Pick the longer river',
       loading: 'Loading rivers from Supabase…',
       settingsTitle: '⚙️ Game Settings',
       startGame: 'Start Game',
       streak: 'Streak',
       streakProgress: '🔥 Rank Progress',
       nextReward: 'Next rank',
       milestone: 'Milestone',
       reached: 'reached!',
       correct: 'Correct!',
       wrong: 'Wrong —',
       earlierThan: 'is longer than',
       yearsApart: '{n} km apart',
       or: 'or',
       next: 'Next →',
       filters: '⚙️ Filters',
       youWon: 'You Won!',
       winSubtitle: 'You reached a streak of 50!',
       eventsAvailable: 'rivers available',
       needMore: 'Pick broader filters — need at least',
       toPlay: 'to play',
       minValueLabel: 'Min Length (km)',
       maxValueLabel: 'Max Length (km)',
       groupLabel: 'Region',
       placeholderMinValue: 'e.g. 100',
       placeholderMaxValue: 'e.g. 7000',
       year: 'Length',
       preparing: 'Preparing next rivers…',
       winRank: 'Master of the Waters',
       missingEnv: 'Missing Supabase env vars',
       error: 'Error:',
       crash: 'Crash:',
       needEventsTable: 'Need at least 2 rivers in the table.',
       pickAriaLabel: 'Pick this river as longer',
       backToHomescreen: '🏠 Back to Games',
     },
     cs: {
       ...baseUiText.cs,
       title: 'Která řeka je delší?',
       subtitle: 'Vyber delší řeku',
       loading: 'Načítání řek ze Supabase…',
       settingsTitle: '⚙️ Nastavení hry',
       startGame: 'Spustit hru',
       streak: 'Série',
       streakProgress: '🔥 Průběh hodnosti',
       nextReward: 'Další hodnost',
       milestone: 'Milník',
       reached: 'dosažen!',
       correct: 'Správně!',
       wrong: 'Špatně —',
       earlierThan: 'je delší než',
       yearsApart: '{n} km od sebe',
       or: 'nebo',
       next: 'Další →',
       filters: '⚙️ Filtry',
       youWon: 'Vyhrál jsi!',
       winSubtitle: 'Dosáhl jsi série 50!',
       eventsAvailable: 'řek k dispozici',
       needMore: 'Vyber méně restriktivní filtry — potřebuješ alespoň',
       toPlay: 'k hraní',
       minValueLabel: 'Min. délka (km)',
       maxValueLabel: 'Max. délka (km)',
       groupLabel: 'Region',
       placeholderMinValue: 'např. 100',
       placeholderMaxValue: 'např. 7000',
       year: 'Délka',
       preparing: 'Příprava dalších řek…',
       winRank: 'Mistr vod',
       error: 'Chyba:',
       crash: 'Pád:',
       needEventsTable: 'V tabulce musí být alespoň 2 řeky.',
       missingEnv: 'Chybí Supabase proměnné prostředí',
       pickAriaLabel: 'Vyber tuto řeku jako delší',
       backToHomescreen: '🏠 Zpět na hry',
     },
    it: {
       ...baseUiText.it,
       title: 'Quale montagna è più alta?',
       subtitle: 'Scegli la vetta più alta',
       loading: 'Caricamento montagne da Supabase…',
       settingsTitle: '⚙️ Impostazioni di gioco',
       startGame: 'Inizia',
       streak: 'Serie',
       streakProgress: '🔥 Progresso grado',
       nextReward: 'Prossimo grado',
       milestone: 'Traguardo',
       reached: 'raggiunto!',
       correct: 'Corretto!',
       wrong: 'Sbagliato —',
       earlierThan: 'è più alta di',
       yearsApart: '{n} m di distanza',
       or: 'oppure',
       next: 'Avanti →',
       filters: '⚙️ Filtri',
       youWon: 'Hai Vinto!',
       winSubtitle: 'Hai raggiunto una serie di 50!',
       eventsAvailable: 'montagne disponibili',
       needMore: 'Allarga i filtri — servono almeno',
       toPlay: 'per giocare',
       minValueLabel: 'Altitudine min (m)',
       maxValueLabel: 'Altitudine max (m)',
       groupLabel: 'Regione',
       placeholderMinValue: 'es. 2000',
       placeholderMaxValue: 'es. 8000',
       year: 'Altitudine',
       preparing: 'Preparazione prossime montagne…',
       winRank: 'Re delle vette',
       error: 'Errore:',
       crash: 'Errore critico:',
       needEventsTable: 'Servono almeno 2 montagne nella tabella.',
       missingEnv: 'Variabili d\'ambiente Supabase mancanti',
       pickAriaLabel: 'Scegli questa montagna come più alta',
       backToHomescreen: '🏠 Torna ai giochi',
     },
   },
   rivers: {
     en: {
       ...baseUiText.en,
       title: 'Which river is longer?',
       subtitle: 'Pick the longer river',
       loading: 'Loading rivers from Supabase…',
       settingsTitle: '⚙️ Game Settings',
       startGame: 'Start Game',
       streak: 'Streak',
       streakProgress: '🔥 Rank Progress',
       nextReward: 'Next rank',
       milestone: 'Milestone',
       reached: 'reached!',
       correct: 'Correct!',
       wrong: 'Wrong —',
       earlierThan: 'is longer than',
       yearsApart: '{n} km apart',
       or: 'or',
       next: 'Next →',
       filters: '⚙️ Filters',
       youWon: 'You Won!',
       winSubtitle: 'You reached a streak of 50!',
       eventsAvailable: 'rivers available',
       needMore: 'Pick broader filters — need at least',
       toPlay: 'to play',
       minValueLabel: 'Min Length (km)',
       maxValueLabel: 'Max Length (km)',
       groupLabel: 'Region',
       placeholderMinValue: 'e.g. 100',
       placeholderMaxValue: 'e.g. 7000',
       year: 'Length',
       preparing: 'Preparing next rivers…',
       winRank: 'Master of the Waters',
       missingEnv: 'Missing Supabase env vars',
       error: 'Error:',
       crash: 'Crash:',
       needEventsTable: 'Need at least 2 rivers in the table.',
       pickAriaLabel: 'Pick this river as longer',
       backToHomescreen: '🏠 Back to Games',
     },
     cs: {
       ...baseUiText.cs,
       title: 'Která řeka je delší?',
       subtitle: 'Vyber delší řeku',
       loading: 'Načítání řek ze Supabase…',
       settingsTitle: '⚙️ Nastavení hry',
       startGame: 'Spustit hru',
       streak: 'Série',
       streakProgress: '🔥 Průběh hodnosti',
       nextReward: 'Další hodnost',
       milestone: 'Milník',
       reached: 'dosažen!',
       correct: 'Správně!',
       wrong: 'Špatně —',
       earlierThan: 'je delší než',
       yearsApart: '{n} km od sebe',
       or: 'nebo',
       next: 'Další →',
       filters: '⚙️ Filtry',
       youWon: 'Vyhrál jsi!',
       winSubtitle: 'Dosáhl jsi série 50!',
       eventsAvailable: 'řek k dispozici',
       needMore: 'Vyber méně restriktivní filtry — potřebuješ alespoň',
       toPlay: 'k hraní',
       minValueLabel: 'Min. délka (km)',
       maxValueLabel: 'Max. délka (km)',
       groupLabel: 'Region',
       placeholderMinValue: 'např. 100',
       placeholderMaxValue: 'např. 7000',
       year: 'Délka',
       preparing: 'Příprava dalších řek…',
       winRank: 'Mistr vod',
       error: 'Chyba:',
       crash: 'Pád:',
       needEventsTable: 'V tabulce musí být alespoň 2 řeky.',
       missingEnv: 'Chybí Supabase proměnné prostředí',
       pickAriaLabel: 'Vyber tuto řeku jako delší',
       backToHomescreen: '🏠 Zpět na hry',
     },
    it: {
       ...baseUiText.it,
       title: 'Quale montagna è più alta?',
       subtitle: 'Scegli la vetta più alta',
       loading: 'Caricamento montagne da Supabase…',
       settingsTitle: '⚙️ Impostazioni di gioco',
       startGame: 'Inizia',
       streak: 'Serie',
       streakProgress: '🔥 Progresso grado',
       nextReward: 'Prossimo grado',
       milestone: 'Traguardo',
       reached: 'raggiunto!',
       correct: 'Corretto!',
       wrong: 'Sbagliato —',
       earlierThan: 'è più alta di',
       yearsApart: '{n} m di distanza',
       or: 'oppure',
       next: 'Avanti →',
       filters: '⚙️ Filtri',
       youWon: 'Hai Vinto!',
       winSubtitle: 'Hai raggiunto una serie di 50!',
       eventsAvailable: 'montagne disponibili',
       needMore: 'Allarga i filtri — servono almeno',
       toPlay: 'per giocare',
       minValueLabel: 'Altitudine min (m)',
       maxValueLabel: 'Altitudine max (m)',
       groupLabel: 'Regione',
       placeholderMinValue: 'es. 2000',
       placeholderMaxValue: 'es. 8000',
       year: 'Altitudine',
       preparing: 'Preparazione prossime montagne…',
       winRank: 'Re delle vette',
       error: 'Errore:',
       crash: 'Errore critico:',
       needEventsTable: 'Servono almeno 2 montagne nella tabella.',
       missingEnv: 'Variabili d\'ambiente Supabase mancanti',
       pickAriaLabel: 'Scegli questa montagna come più alta',
       backToHomescreen: '🏠 Torna ai giochi',
     },
   },
   rivers: {
     en: {
       ...baseUiText.en,
       title: 'Which river is longer?',
       subtitle: 'Pick the longer river',
       loading: 'Loading rivers from Supabase…',
       settingsTitle: '⚙️ Game Settings',
       startGame: 'Start Game',
       streak: 'Streak',
       streakProgress: '🔥 Rank Progress',
       nextReward: 'Next rank',
       milestone: 'Milestone',
       reached: 'reached!',
       correct: 'Correct!',
       wrong: 'Wrong —',
       earlierThan: 'is longer than',
       yearsApart: '{n} km apart',
       or: 'or',
       next: 'Next →',
       filters: '⚙️ Filters',
       youWon: 'You Won!',
       winSubtitle: 'You reached a streak of 50!',
       eventsAvailable: 'rivers available',
       needMore: 'Pick broader filters — need at least',
       toPlay: 'to play',
       minValueLabel: 'Min Length (km)',
       maxValueLabel: 'Max Length (km)',
       groupLabel: 'Region',
       placeholderMinValue: 'e.g. 100',
       placeholderMaxValue: 'e.g. 7000',
       year: 'Length',
       preparing: 'Preparing next rivers…',
       winRank: 'Master of the Waters',
       missingEnv: 'Missing Supabase env vars',
       error: 'Error:',
       crash: 'Crash:',
       needEventsTable: 'Need at least 2 rivers in the table.',
       pickAriaLabel: 'Pick this river as longer',
       backToHomescreen: '🏠 Back to Games',
     },
     cs: {
       ...baseUiText.cs,
       title: 'Která řeka je delší?',
       subtitle: 'Vyber delší řeku',
       loading: 'Načítání řek ze Supabase…',
       settingsTitle: '⚙️ Nastavení hry',
       startGame: 'Spustit hru',
       streak: 'Série',
       streakProgress: '🔥 Průběh hodnosti',
       nextReward: 'Další hodnost',
       milestone: 'Milník',
       reached: 'dosažen!',
       correct: 'Správně!',
       wrong: 'Špatně —',
       earlierThan: 'je delší než',
       yearsApart: '{n} km od sebe',
       or: 'nebo',
       next: 'Další →',
       filters: '⚙️ Filtry',
       youWon: 'Vyhrál jsi!',
       winSubtitle: 'Dosáhl jsi série 50!',
       eventsAvailable: 'řek k dispozici',
       needMore: 'Vyber méně restriktivní filtry — potřebuješ alespoň',
       toPlay: 'k hraní',
       minValueLabel: 'Min. délka (km)',
       maxValueLabel: 'Max. délka (km)',
       groupLabel: 'Region',
       placeholderMinValue: 'např. 100',
       placeholderMaxValue: 'např. 7000',
       year: 'Délka',
       preparing: 'Příprava dalších řek…',
       winRank: 'Mistr vod',
       error: 'Chyba:',
       crash: 'Pád:',
       needEventsTable: 'V tabulce musí být alespoň 2 řeky.',
       missingEnv: 'Chybí Supabase proměnné prostředí',
       pickAriaLabel: 'Vyber tuto řeku jako delší',
       backToHomescreen: '🏠 Zpět na hry',
     },
    it: {
       ...baseUiText.it,
       title: 'Quale montagna è più alta?',
       subtitle: 'Scegli la vetta più alta',
       loading: 'Caricamento montagne da Supabase…',
       settingsTitle: '⚙️ Impostazioni di gioco',
       startGame: 'Inizia',
       streak: 'Serie',
       streakProgress: '🔥 Progresso grado',
       nextReward: 'Prossimo grado',
       milestone: 'Traguardo',
       reached: 'raggiunto!',
       correct: 'Corretto!',
       wrong: 'Sbagliato —',
       earlierThan: 'è più alta di',
       yearsApart: '{n} m di distanza',
       or: 'oppure',
       next: 'Avanti →',
       filters: '⚙️ Filtri',
       youWon: 'Hai Vinto!',
       winSubtitle: 'Hai raggiunto una serie di 50!',
       eventsAvailable: 'montagne disponibili',
       needMore: 'Allarga i filtri — servono almeno',
       toPlay: 'per giocare',
       minValueLabel: 'Altitudine min (m)',
       maxValueLabel: 'Altitudine max (m)',
       groupLabel: 'Regione',
       placeholderMinValue: 'es. 2000',
       placeholderMaxValue: 'es. 8000',
       year: 'Altitudine',
       preparing: 'Preparazione prossime montagne…',
       winRank: 'Re delle vette',
       error: 'Errore:',
       crash: 'Errore critico:',
       needEventsTable: 'Servono almeno 2 montagne nella tabella.',
       missingEnv: 'Variabili d\'ambiente Supabase mancanti',
       pickAriaLabel: 'Scegli questa montagna come più alta',
       backToHomescreen: '🏠 Torna ai giochi',
     },
   },
   rivers: {
     en: {
       ...baseUiText.en,
       title: 'Which river is longer?',
       subtitle: 'Pick the longer river',
       loading: 'Loading rivers from Supabase…',
       settingsTitle: '⚙️ Game Settings',
       startGame: 'Start Game',
       streak: 'Streak',
       streakProgress: '🔥 Rank Progress',
       nextReward: 'Next rank',
       milestone: 'Milestone',
       reached: 'reached!',
       correct: 'Correct!',
       wrong: 'Wrong —',
       earlierThan: 'is longer than',
       yearsApart: '{n} km apart',
       or: 'or',
       next: 'Next →',
       filters: '⚙️ Filters',
       youWon: 'You Won!',
       winSubtitle: 'You reached a streak of 50!',
       eventsAvailable: 'rivers available',
       needMore: 'Pick broader filters — need at least',
       toPlay: 'to play',
       minValueLabel: 'Min Length (km)',
       maxValueLabel: 'Max Length (km)',
       groupLabel: 'Region',
       placeholderMinValue: 'e.g. 100',
       placeholderMaxValue: 'e.g. 7000',
       year: 'Length',
       preparing: 'Preparing next rivers…',
       winRank: 'Master of the Waters',
       missingEnv: 'Missing Supabase env vars',
       error: 'Error:',
       crash: 'Crash:',
       needEventsTable: 'Need at least 2 rivers in the table.',
       pickAriaLabel: 'Pick this river as longer',
       backToHomescreen: '🏠 Back to Games',
     },
     cs: {
       ...baseUiText.cs,
       title: 'Která řeka je delší?',
       subtitle: 'Vyber delší řeku',
       loading: 'Načítání řek ze Supabase…',
       settingsTitle: '⚙️ Nastavení hry',
       startGame: 'Spustit hru',
       streak: 'Série',
       streakProgress: '🔥 Průběh hodnosti',
       nextReward: 'Další hodnost',
       milestone: 'Milník',
       reached: 'dosažen!',
       correct: 'Správně!',
       wrong: 'Špatně —',
       earlierThan: 'je delší než',
       yearsApart: '{n} km od sebe',
       or: 'nebo',
       next: 'Další →',
       filters: '⚙️ Filtry',
       youWon: 'Vyhrál jsi!',
       winSubtitle: 'Dosáhl jsi série 50!',
       eventsAvailable: 'řek k dispozici',
       needMore: 'Vyber méně restriktivní filtry — potřebuješ alespoň',
       toPlay: 'k hraní',
       minValueLabel: 'Min. délka (km)',
       maxValueLabel: 'Max. délka (km)',
       groupLabel: 'Region',
       placeholderMinValue: 'např. 100',
       placeholderMaxValue: 'např. 7000',
       year: 'Délka',
       preparing: 'Příprava dalších řek…',
       winRank: 'Mistr vod',
       error: 'Chyba:',
       crash: 'Pád:',
       needEventsTable: 'V tabulce musí být alespoň 2 řeky.',
       missingEnv: 'Chybí Supabase proměnné prostředí',
       pickAriaLabel: 'Vyber tuto řeku jako delší',
       backToHomescreen: '🏠 Zpět na hry',
     },
     it: {
       ...baseUiText.it,
       title: 'Quale fiume è più lungo?',
       subtitle: 'Scegli il fiume più lungo',
       loading: 'Caricamento fiumi da Supabase…',
       settingsTitle: '⚙️ Impostazioni di gioco',
       startGame: 'Inizia',
       streak: 'Serie',
       streakProgress: '🔥 Progresso grado',
       nextReward: 'Prossimo grado',
       milestone: 'Traguardo',
       reached: 'raggiunto!',
       correct: 'Corretto!',
       wrong: 'Sbagliato —',
       earlierThan: 'è più lungo di',
       yearsApart: '{n} km di distanza',
       or: 'oppure',
       next: 'Avanti →',
       filters: '⚙️ Filtri',
       youWon: 'Hai Vinto!',
       winSubtitle: 'Hai raggiunto una serie di 50!',
       eventsAvailable: 'fiumi disponibili',
       needMore: 'Allarga i filtri — servono almeno',
       toPlay: 'per giocare',
       minValueLabel: 'Lunghezza min (km)',
       maxValueLabel: 'Lunghezza max (km)',
       groupLabel: 'Regione',
       placeholderMinValue: 'es. 100',
       placeholderMaxValue: 'es. 7000',
       year: 'Lunghezza',
       preparing: 'Preparazione prossimi fiumi…',
       winRank: 'Maestro delle Acque',
       error: 'Errore:',
       crash: 'Errore critico:',
       needEventsTable: 'Servono almeno 2 fiumi nella tabella.',
       missingEnv: 'Variabili d\'ambiente Supabase mancanti',
       pickAriaLabel: 'Scegli questo fiume come più lungo',
       backToHomescreen: '🏠 Torna ai giochi',
     },
   },
 };

export const MP_UI = {
  history: {
    en: {
      ...baseUiText.en,
      title: 'Multiplayer',
      subtitle: 'Compete with up to 9 friends in real time',
      createGame: 'Create Game',
      joinGame: 'Join Game',
      rounds: 'Number of Rounds (5–50)',
      createRoom: 'Create Room',
      joinRoom: 'Join Room',
      roomCode: 'Room Code',
      loading: 'Loading...',
      waiting: 'Waiting Room',
      waitingOpp: 'Waiting for other players...',
      waitingHost: 'Waiting for host to start the game...',
      yourTurn: 'Your turn! Pick the earlier event.',
      loadingEvents: 'Loading events...',
      you: 'You',
      opponent: 'Opponent',
      leaderboard: 'Leaderboard',
      round: 'Round',
      correct: 'Correct!',
      wrong: 'Wrong!',
      timedOut: 'No answer',
      wasEarlier: 'was earlier',
      didYouKnow: 'Did you know?',
      roomClosedTitle: 'Room Closed',
      roomClosedMsg: 'The host has left. This room is no longer available.',
      roomClosedSub: 'Create a new room or join another one.',
      backToLobby: 'Back to Lobby',
      playersConnected: '{count} / {max} players connected',
      startGame: 'Start Game',
      nickname: 'Nickname',
      pickColor: 'Color',
      save: 'Save',
      finalStandings: 'Final Standings',
      rank: 'Rank',
      returnToLobby: 'Return to lobby',
      restartGame: 'Restart game',
      minPlayers: 'Need at least 2 players to start',
      roomFull: 'Room is full',
      oppLabel: 'Opponent:',
      nextRound: 'Next round starting soon...',
      sending: 'Sending...',
      networkError: 'Network error. Please try again.',
      failedCreate: 'Failed to create room',
      failedJoin: 'Failed to join room',
      roundsRange: 'Rounds must be 5–50',
      poolAvailable: '{count} events available ✅',
      needEvents: 'Need at least {min} events to play ({count})',
      creating: 'Creating...',
      minValueLabel: 'Start Year',
      maxValueLabel: 'End Year',
      groupLabel: 'Region',
      placeholderStartYear: 'e.g. 1500',
      placeholderEndYear: 'e.g. 2000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Pick this event as earlier',
      backToHomescreen: '🏠 Back to Games',
    },
    cs: {
      ...baseUiText.cs,
      title: 'Multiplayer',
      subtitle: 'Soutěž s až 9 přáteli v reálném čase',
      createGame: 'Vytvořit hru',
      joinGame: 'Připojit se ke hře',
      rounds: 'Počet kol (5–50)',
      createRoom: 'Vytvořit místnost',
      joinRoom: 'Připojit se',
      roomCode: 'Kód místnosti',
      loading: 'Načítání...',
      waiting: 'Čekací místnost',
      waitingOpp: 'Čeká se na ostatní hráče...',
      waitingHost: 'Čeká se na hostitele, aby spustil hru...',
      yourTurn: 'Jsi na tahu! Vyber dřívější událost.',
      loadingEvents: 'Načítání událostí...',
      you: 'Ty',
      opponent: 'Soupeř',
      leaderboard: 'Žebříček',
      round: 'Kolo',
      correct: 'Správně!',
      wrong: 'Špatně!',
      timedOut: 'Bez odpovědi',
      wasEarlier: 'bylo dřív',
      didYouKnow: 'Věděl jsi?',
      roomClosedTitle: 'Místnost uzavřena',
      roomClosedMsg: 'Hostitel odešel. Tato místnost již není dostupná.',
      roomClosedSub: 'Vytvoř novou místnost nebo se připoj k jiné.',
      backToLobby: 'Zpět do lobby',
      playersConnected: '{count} / {max} hráčů připojeno',
      startGame: 'Spustit hru',
      nickname: 'Přezdívka',
      pickColor: 'Barva',
      save: 'Uložit',
      finalStandings: 'Konečné pořadí',
      rank: 'Pozice',
      returnToLobby: 'Zpět do lobby',
      restartGame: 'Restart hry',
      minPlayers: 'Ke startu jsou potřeba alespoň 2 hráči',
      roomFull: 'Místnost je plná',
      oppLabel: 'Soupeř:',
      nextRound: 'Další kolo začíná za chvíli...',
      sending: 'Odesílání...',
      networkError: 'Chyba sítě. Zkus to znovu.',
      failedCreate: 'Nepodařilo se vytvořit místnost',
      failedJoin: 'Nepodařilo se připojit do místnosti',
      roundsRange: 'Kol musí být 5–50',
      poolAvailable: '{count} událostí k dispozici ✅',
      needEvents: 'Potřebuješ alespoň {min} událostí ke hře ({count})',
      creating: 'Vytváření...',
      minValueLabel: 'Od roku',
      maxValueLabel: 'Do roku',
      groupLabel: 'Region',
      placeholderStartYear: 'např. 1500',
      placeholderEndYear: 'např. 2000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Vyber tuto událost jako dřívější',
      backToHomescreen: '🏠 Zpět na hry',
    },
    it: {
      ...baseUiText.it,
      title: 'Multiplayer',
      subtitle: 'Gareggia con fino a 9 amici in tempo reale',
      createGame: 'Crea partita',
      joinGame: 'Unisciti alla partita',
      rounds: 'Numero di round (5–50)',
      createRoom: 'Crea stanza',
      joinRoom: 'Unisciti',
      roomCode: 'Codice stanza',
      loading: 'Caricamento...',
      waiting: 'Sala d\'attesa',
      waitingOpp: 'In attesa degli altri giocatori...',
      waitingHost: 'In attesa che l\'host avvii la partita...',
      yourTurn: 'Tocca a te! Scegli l\'evento più antico.',
      loadingEvents: 'Caricamento eventi...',
      you: 'Tu',
      opponent: 'Avversario',
      leaderboard: 'Classifica',
      round: 'Round',
      correct: 'Corretto!',
      wrong: 'Sbagliato!',
      timedOut: 'Nessuna risposta',
      wasEarlier: 'era prima',
      didYouKnow: 'Lo sapevi?',
      roomClosedTitle: 'Stanza chiusa',
      roomClosedMsg: 'L\'host è uscito. Questa stanza non è più disponibile.',
      roomClosedSub: 'Crea una nuova stanza o unisciti a un\'altra.',
      backToLobby: 'Torna alla lobby',
      playersConnected: '{count} / {max} giocatori connessi',
      startGame: 'Avvia partita',
      nickname: 'Nickname',
      pickColor: 'Colore',
      save: 'Salva',
      finalStandings: 'Classifica finale',
      rank: 'Posizione',
      returnToLobby: 'Torna alla lobby',
      restartGame: 'Ricomincia partita',
      minPlayers: 'Servono almeno 2 giocatori per iniziare',
      roomFull: 'Stanza piena',
      oppLabel: 'Avversario:',
      nextRound: 'Il prossimo round inizierà a breve...',
      sending: 'Invio in corso...',
      networkError: 'Errore di rete. Riprova.',
      failedCreate: 'Impossibile creare la stanza',
      failedJoin: 'Impossibile unirsi alla stanza',
      roundsRange: 'I round devono essere 5–50',
      poolAvailable: '{count} eventi disponibili ✅',
      needEvents: 'Servono almeno {min} eventi per giocare ({count})',
      creating: 'Creazione in corso...',
      minValueLabel: 'Anno inizio',
      maxValueLabel: 'Anno fine',
      groupLabel: 'Regione',
      placeholderStartYear: 'es. 1500',
      placeholderEndYear: 'es. 2000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: "Scegli questo evento come più antico",
      backToHomescreen: '🏠 Torna ai giochi',
    },
  },
  mountains: {
    en: {
      ...baseUiText.en,
      title: 'Multiplayer',
      subtitle: 'Compete with up to 9 friends in real time',
      createGame: 'Create Game',
      joinGame: 'Join Game',
      rounds: 'Number of Rounds (5–50)',
      createRoom: 'Create Room',
      joinRoom: 'Join Room',
      roomCode: 'Room Code',
      loading: 'Loading...',
      waiting: 'Waiting Room',
      waitingOpp: 'Waiting for other players...',
      waitingHost: 'Waiting for host to start the game...',
      yourTurn: 'Your turn! Pick the higher mountain.',
      loadingEvents: 'Loading mountains...',
      you: 'You',
      opponent: 'Opponent',
      leaderboard: 'Leaderboard',
      round: 'Round',
      correct: 'Correct!',
      wrong: 'Wrong!',
      timedOut: 'No answer',
      wasEarlier: 'is higher',
      didYouKnow: 'Did you know?',
      roomClosedTitle: 'Room Closed',
      roomClosedMsg: 'The host has left. This room is no longer available.',
      roomClosedSub: 'Create a new room or join another one.',
      backToLobby: 'Back to Lobby',
      playersConnected: '{count} / {max} players connected',
      startGame: 'Start Game',
      nickname: 'Nickname',
      pickColor: 'Color',
      save: 'Save',
      finalStandings: 'Final Standings',
      rank: 'Rank',
      returnToLobby: 'Return to lobby',
      restartGame: 'Restart game',
      minPlayers: 'Need at least 2 players to start',
      roomFull: 'Room is full',
      oppLabel: 'Opponent:',
      nextRound: 'Next round starting soon...',
      sending: 'Sending...',
      networkError: 'Network error. Please try again.',
      failedCreate: 'Failed to create room',
      failedJoin: 'Failed to join room',
      roundsRange: 'Rounds must be 5–50',
      poolAvailable: '{count} mountains available ✅',
      needEvents: 'Need at least {min} mountains to play ({count})',
      creating: 'Creating...',
      minValueLabel: 'Min Elevation (m)',
      maxValueLabel: 'Max Elevation (m)',
      groupLabel: 'Range',
      placeholderStartYear: 'e.g. 2000',
      placeholderEndYear: 'e.g. 8000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Pick this mountain as higher',
      backToHomescreen: '🏠 Back to Games',
    },
    cs: {
      ...baseUiText.cs,
      title: 'Multiplayer',
      subtitle: 'Soutěž s až 9 přáteli v reálném čase',
      createGame: 'Vytvořit hru',
      joinGame: 'Připojit se ke hře',
      rounds: 'Počet kol (5–50)',
      createRoom: 'Vytvořit místnost',
      joinRoom: 'Připojit se',
      roomCode: 'Kód místnosti',
      loading: 'Načítání...',
      waiting: 'Čekací místnost',
      waitingOpp: 'Čeká se na ostatní hráče...',
      waitingHost: 'Čeká se na hostitele, aby spustil hru...',
      yourTurn: 'Jsi na tahu! Vyber vyšší horu.',
      loadingEvents: 'Načítání hor...',
      you: 'Ty',
      opponent: 'Soupeř',
      leaderboard: 'Žebříček',
      round: 'Kolo',
      correct: 'Správně!',
      wrong: 'Špatně!',
      timedOut: 'Bez odpovědi',
      wasEarlier: 'je vyšší',
      didYouKnow: 'Věděl jsi?',
      roomClosedTitle: 'Místnost uzavřena',
      roomClosedMsg: 'Hostitel odešel. Tato místnost již není dostupná.',
      roomClosedSub: 'Vytvoř novou místnost nebo se připoj k jiné.',
      backToLobby: 'Zpět do lobby',
      playersConnected: '{count} / {max} hráčů připojeno',
      startGame: 'Spustit hru',
      nickname: 'Přezdívka',
      pickColor: 'Barva',
      save: 'Uložit',
      finalStandings: 'Konečné pořadí',
      rank: 'Pozice',
      returnToLobby: 'Zpět do lobby',
      restartGame: 'Restart hry',
      minPlayers: 'Ke startu jsou potřeba alespoň 2 hráči',
      roomFull: 'Místnost je plná',
      oppLabel: 'Soupeř:',
      nextRound: 'Další kolo začíná za chvíli...',
      sending: 'Odesílání...',
      networkError: 'Chyba sítě. Zkus to znovu.',
      failedCreate: 'Nepodařilo se vytvořit místnost',
      failedJoin: 'Nepodařilo se připojit do místnosti',
      roundsRange: 'Kol musí být 5–50',
      poolAvailable: '{count} hor k dispozici ✅',
      needEvents: 'Potřebuješ alespoň {min} hor ke hře ({count})',
      creating: 'Vytváření...',
      minValueLabel: 'Min. nadmořská výška (m)',
      maxValueLabel: 'Max. nadmořská výška (m)',
      groupLabel: 'Pohoří',
      placeholderStartYear: 'např. 2000',
      placeholderEndYear: 'např. 8000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Vyber tuto horu jako vyšší',
      backToHomescreen: '🏠 Zpět na hry',
    },
    it: {
      ...baseUiText.it,
      title: 'Multiplayer',
      subtitle: 'Gareggia con fino a 9 amici in tempo reale',
      createGame: 'Crea partita',
      joinGame: 'Unisciti alla partita',
      rounds: 'Numero di round (5–50)',
      createRoom: 'Crea stanza',
      joinRoom: 'Unisciti',
      roomCode: 'Codice stanza',
      loading: 'Caricamento...',
      waiting: 'Sala d\'attesa',
      waitingOpp: 'In attesa degli altri giocatori...',
      waitingHost: 'In attesa che l\'host avvii la partita...',
      yourTurn: 'Tocca a te! Scegli la montagna più alta.',
      loadingEvents: 'Caricamento montagne...',
      you: 'Tu',
      opponent: 'Avversario',
      leaderboard: 'Classifica',
      round: 'Round',
      correct: 'Corretto!',
      wrong: 'Sbagliato!',
      timedOut: 'Nessuna risposta',
      wasEarlier: 'è più alta',
      didYouKnow: 'Lo sapevi?',
      roomClosedTitle: 'Stanza chiusa',
      roomClosedMsg: 'L\'host è uscito. Questa stanza non è più disponibile.',
      roomClosedSub: 'Crea una nuova stanza o unisciti a un\'altra.',
      backToLobby: 'Torna alla lobby',
      playersConnected: '{count} / {max} giocatori connessi',
      startGame: 'Avvia partita',
      nickname: 'Nickname',
      pickColor: 'Colore',
      save: 'Salva',
      finalStandings: 'Classifica finale',
      rank: 'Posizione',
      returnToLobby: 'Torna alla lobby',
      restartGame: 'Ricomincia partita',
      minPlayers: 'Servono almeno 2 giocatori per iniziare',
      roomFull: 'Stanza piena',
      oppLabel: 'Avversario:',
      nextRound: 'Il prossimo round inizierà a breve...',
      sending: 'Invio in corso...',
      networkError: 'Errore di rete. Riprova.',
      failedCreate: 'Impossibile creare la stanza',
      failedJoin: 'Impossibile unirsi alla stanza',
      roundsRange: 'I round devono essere 5–50',
      poolAvailable: '{count} montagne disponibili ✅',
      needEvents: 'Servono almeno {min} montagne per giocare ({count})',
      creating: 'Creazione in corso...',
      minValueLabel: 'Altitudine min (m)',
      maxValueLabel: 'Altitudine max (m)',
      groupLabel: 'Catena',
      placeholderStartYear: 'es. 2000',
      placeholderEndYear: 'es. 8000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Scegli questa montagna come più alta',
      backToHomescreen: '🏠 Torna ai giochi',
    },
  },
  rivers: {
    en: {
      ...baseUiText.en,
      title: 'Multiplayer',
      subtitle: 'Compete with up to 9 friends in real time',
      createGame: 'Create Game',
      joinGame: 'Join Game',
      rounds: 'Number of Rounds (5–50)',
      createRoom: 'Create Room',
      joinRoom: 'Join Room',
      roomCode: 'Room Code',
      loading: 'Loading...',
      waiting: 'Waiting Room',
      waitingOpp: 'Waiting for other players...',
      waitingHost: 'Waiting for host to start the game...',
      yourTurn: 'Your turn! Pick the longer river.',
      loadingEvents: 'Loading rivers...',
      you: 'You',
      opponent: 'Opponent',
      leaderboard: 'Leaderboard',
      round: 'Round',
      correct: 'Correct!',
      wrong: 'Wrong!',
      timedOut: 'No answer',
      wasEarlier: 'is longer',
      didYouKnow: 'Did you know?',
      roomClosedTitle: 'Room Closed',
      roomClosedMsg: 'The host has left. This room is no longer available.',
      roomClosedSub: 'Create a new room or join another one.',
      backToLobby: 'Back to Lobby',
      playersConnected: '{count} / {max} players connected',
      startGame: 'Start Game',
      nickname: 'Nickname',
      pickColor: 'Color',
      save: 'Save',
      finalStandings: 'Final Standings',
      rank: 'Rank',
      returnToLobby: 'Return to lobby',
      restartGame: 'Restart game',
      minPlayers: 'Need at least 2 players to start',
      roomFull: 'Room is full',
      oppLabel: 'Opponent:',
      nextRound: 'Next round starting soon...',
      sending: 'Sending...',
      networkError: 'Network error. Please try again.',
      failedCreate: 'Failed to create room',
      failedJoin: 'Failed to join room',
      roundsRange: 'Rounds must be 5–50',
      poolAvailable: '{count} rivers available ✅',
      needEvents: 'Need at least {min} rivers to play ({count})',
      creating: 'Creating...',
      minValueLabel: 'Min Length (km)',
      maxValueLabel: 'Max Length (km)',
      groupLabel: 'Region',
      placeholderStartYear: 'e.g. 100',
      placeholderEndYear: 'e.g. 7000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Pick this river as longer',
      backToHomescreen: '🏠 Back to Games',
    },
    cs: {
      ...baseUiText.cs,
      title: 'Multiplayer',
      subtitle: 'Soutěž s až 9 přáteli v reálném čase',
      createGame: 'Vytvořit hru',
      joinGame: 'Připojit se ke hře',
      rounds: 'Počet kol (5–50)',
      createRoom: 'Vytvořit místnost',
      joinRoom: 'Připojit se',
      roomCode: 'Kód místnosti',
      loading: 'Načítání...',
      waiting: 'Čekací místnost',
      waitingOpp: 'Čeká se na ostatní hráče...',
      waitingHost: 'Čeká se na hostitele, aby spustil hru...',
      yourTurn: 'Jsi na tahu! Vyber delší řeku.',
      loadingEvents: 'Načítání řek...',
      you: 'Ty',
      opponent: 'Soupeř',
      leaderboard: 'Žebříček',
      round: 'Kolo',
      correct: 'Správně!',
      wrong: 'Špatně!',
      timedOut: 'Bez odpovědi',
      wasEarlier: 'je delší',
      didYouKnow: 'Věděl jsi?',
      roomClosedTitle: 'Místnost uzavřena',
      roomClosedMsg: 'Hostitel odešel. Tato místnost již není dostupná.',
      roomClosedSub: 'Vytvoř novou místnost nebo se připoj k jiné.',
      backToLobby: 'Zpět do lobby',
      playersConnected: '{count} / {max} hráčů připojeno',
      startGame: 'Spustit hru',
      nickname: 'Přezdívka',
      pickColor: 'Barva',
      save: 'Uložit',
      finalStandings: 'Konečné pořadí',
      rank: 'Pozice',
      returnToLobby: 'Zpět do lobby',
      restartGame: 'Restart hry',
      minPlayers: 'Ke startu jsou potřeba alespoň 2 hráči',
      roomFull: 'Místnost je plná',
      oppLabel: 'Soupeř:',
      nextRound: 'Další kolo začíná za chvíli...',
      sending: 'Odesílání...',
      networkError: 'Chyba sítě. Zkus to znovu.',
      failedCreate: 'Nepodařilo se vytvořit místnost',
      failedJoin: 'Nepodařilo se připojit do místnosti',
      roundsRange: 'Kol musí být 5–50',
      poolAvailable: '{count} řek k dispozici ✅',
      needEvents: 'Potřebuješ alespoň {min} řek ke hře ({count})',
      creating: 'Vytváření...',
      minValueLabel: 'Min. délka (km)',
      maxValueLabel: 'Max. délka (km)',
      groupLabel: 'Region',
      placeholderStartYear: 'např. 100',
      placeholderEndYear: 'např. 7000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Vyber tuto řeku jako delší',
      backToHomescreen: '🏠 Zpět na hry',
    },
    it: {
      ...baseUiText.it,
      title: 'Multiplayer',
      subtitle: 'Gareggia con fino a 9 amici in tempo reale',
      createGame: 'Crea partita',
      joinGame: 'Unisciti alla partita',
      rounds: 'Numero di round (5–50)',
      createRoom: 'Crea stanza',
      joinRoom: 'Unisciti',
      roomCode: 'Codice stanza',
      loading: 'Caricamento...',
      waiting: 'Sala d\'attesa',
      waitingOpp: 'In attesa degli altri giocatori...',
      waitingHost: 'In attesa che l\'host avvii la partita...',
      yourTurn: 'Tocca a te! Scegli il fiume più lungo.',
      loadingEvents: 'Caricamento fiumi...',
      you: 'Tu',
      opponent: 'Avversario',
      leaderboard: 'Classifica',
      round: 'Round',
      correct: 'Corretto!',
      wrong: 'Sbagliato!',
      timedOut: 'Nessuna risposta',
      wasEarlier: 'è più lungo',
      didYouKnow: 'Lo sapevi?',
      roomClosedTitle: 'Stanza chiusa',
      roomClosedMsg: 'L\'host è uscito. Questa stanza non è più disponibile.',
      roomClosedSub: 'Crea una nuova stanza o unisciti a un\'altra.',
      backToLobby: 'Torna alla lobby',
      playersConnected: '{count} / {max} giocatori connessi',
      startGame: 'Avvia partita',
      nickname: 'Nickname',
      pickColor: 'Colore',
      save: 'Salva',
      finalStandings: 'Classifica finale',
      rank: 'Posizione',
      returnToLobby: 'Torna alla lobby',
      restartGame: 'Ricomincia partita',
      minPlayers: 'Servono almeno 2 giocatori per iniziare',
      roomFull: 'Stanza piena',
      oppLabel: 'Avversario:',
      nextRound: 'Il prossimo round inizierà a breve...',
      sending: 'Invio in corso...',
      networkError: 'Errore di rete. Riprova.',
      failedCreate: 'Impossibile creare la stanza',
      failedJoin: 'Impossibile unirsi alla stanza',
      roundsRange: 'I round devono essere 5–50',
      poolAvailable: '{count} fiumi disponibili ✅',
      needEvents: 'Servono almeno {min} fiumi per giocare ({count})',
      creating: 'Creazione in corso...',
      minValueLabel: 'Lunghezza min (km)',
      maxValueLabel: 'Lunghezza max (km)',
      groupLabel: 'Regione',
      placeholderStartYear: 'es. 100',
      placeholderEndYear: 'es. 7000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Scegli questo fiume come più lungo',
      backToHomescreen: '🏠 Torna ai giochi',
    },
  },
};


  history: {
    en: {
      ...baseUiText.en,
      title: 'Multiplayer',
      subtitle: 'Compete with up to 9 friends in real time',
      createGame: 'Create Game',
      joinGame: 'Join Game',
      rounds: 'Number of Rounds (5–50)',
      createRoom: 'Create Room',
      joinRoom: 'Join Room',
      roomCode: 'Room Code',
      loading: 'Loading...',
      waiting: 'Waiting Room',
      waitingOpp: 'Waiting for other players...',
      waitingHost: 'Waiting for host to start the game...',
      yourTurn: 'Your turn! Pick the earlier event.',
      loadingEvents: 'Loading events...',
      you: 'You',
      opponent: 'Opponent',
      leaderboard: 'Leaderboard',
      round: 'Round',
      correct: 'Correct!',
      wrong: 'Wrong!',
      timedOut: 'No answer',
      wasEarlier: 'was earlier',
      didYouKnow: 'Did you know?',
      roomClosedTitle: 'Room Closed',
      roomClosedMsg: 'The host has left. This room is no longer available.',
      roomClosedSub: 'Create a new room or join another one.',
      backToLobby: 'Back to Lobby',
      playersConnected: '{count} / {max} players connected',
      startGame: 'Start Game',
      nickname: 'Nickname',
      pickColor: 'Color',
      save: 'Save',
      finalStandings: 'Final Standings',
      rank: 'Rank',
      returnToLobby: 'Return to lobby',
      restartGame: 'Restart game',
      minPlayers: 'Need at least 2 players to start',
      roomFull: 'Room is full',
      oppLabel: 'Opponent:',
      nextRound: 'Next round starting soon...',
      sending: 'Sending...',
      networkError: 'Network error. Please try again.',
      failedCreate: 'Failed to create room',
      failedJoin: 'Failed to join room',
      roundsRange: 'Rounds must be 5–50',
      poolAvailable: '{count} events available ✅',
      needEvents: 'Need at least {min} events to play ({count})',
      creating: 'Creating...',
      minValueLabel: 'Start Year',
      maxValueLabel: 'End Year',
      groupLabel: 'Region',
      placeholderStartYear: 'e.g. 1500',
      placeholderEndYear: 'e.g. 2000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Pick this event as earlier',
      backToHomescreen: '🏠 Back to Games',
    },
    cs: {
      ...baseUiText.cs,
      title: 'Multiplayer',
      subtitle: 'Soutěž s až 9 přáteli v reálném čase',
      createGame: 'Vytvořit hru',
      joinGame: 'Připojit se ke hře',
      rounds: 'Počet kol (5–50)',
      createRoom: 'Vytvořit místnost',
      joinRoom: 'Připojit se',
      roomCode: 'Kód místnosti',
      loading: 'Načítání...',
      waiting: 'Čekací místnost',
      waitingOpp: 'Čeká se na ostatní hráče...',
      waitingHost: 'Čeká se na hostitele, aby spustil hru...',
      yourTurn: 'Jsi na tahu! Vyber dřívější událost.',
      loadingEvents: 'Načítání událostí...',
      you: 'Ty',
      opponent: 'Soupeř',
      leaderboard: 'Žebříček',
      round: 'Kolo',
      correct: 'Správně!',
      wrong: 'Špatně!',
      timedOut: 'Bez odpovědi',
      wasEarlier: 'bylo dřív',
      didYouKnow: 'Věděl jsi?',
      roomClosedTitle: 'Místnost uzavřena',
      roomClosedMsg: 'Hostitel odešel. Tato místnost již není dostupná.',
      roomClosedSub: 'Vytvoř novou místnost nebo se připoj k jiné.',
      backToLobby: 'Zpět do lobby',
      playersConnected: '{count} / {max} hráčů připojeno',
      startGame: 'Spustit hru',
      nickname: 'Přezdívka',
      pickColor: 'Barva',
      save: 'Uložit',
      finalStandings: 'Konečné pořadí',
      rank: 'Pozice',
      returnToLobby: 'Zpět do lobby',
      restartGame: 'Restart hry',
      minPlayers: 'Ke startu jsou potřeba alespoň 2 hráči',
      roomFull: 'Místnost je plná',
      oppLabel: 'Soupeř:',
      nextRound: 'Další kolo začíná za chvíli...',
      sending: 'Odesílání...',
      networkError: 'Chyba sítě. Zkus to znovu.',
      failedCreate: 'Nepodařilo se vytvořit místnost',
      failedJoin: 'Nepodařilo se připojit do místnosti',
      roundsRange: 'Kol musí být 5–50',
      poolAvailable: '{count} událostí k dispozici ✅',
      needEvents: 'Potřebuješ alespoň {min} událostí ke hře ({count})',
      creating: 'Vytváření...',
      minValueLabel: 'Od roku',
      maxValueLabel: 'Do roku',
      groupLabel: 'Region',
      placeholderStartYear: 'např. 1500',
      placeholderEndYear: 'např. 2000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Vyber tuto událost jako dřívější',
      backToHomescreen: '🏠 Zpět na hry',
    },
    it: {
      ...baseUiText.it,
      title: 'Multiplayer',
      subtitle: 'Gareggia con fino a 9 amici in tempo reale',
      createGame: 'Crea partita',
      joinGame: 'Unisciti alla partita',
      rounds: 'Numero di round (5–50)',
      createRoom: 'Crea stanza',
      joinRoom: 'Unisciti',
      roomCode: 'Codice stanza',
      loading: 'Caricamento...',
      waiting: 'Sala d\'attesa',
      waitingOpp: 'In attesa degli altri giocatori...',
      waitingHost: 'In attesa che l\'host avvii la partita...',
      yourTurn: 'Tocca a te! Scegli l\'evento più antico.',
      loadingEvents: 'Caricamento eventi...',
      you: 'Tu',
      opponent: 'Avversario',
      leaderboard: 'Classifica',
      round: 'Round',
      correct: 'Corretto!',
      wrong: 'Sbagliato!',
      timedOut: 'Nessuna risposta',
      wasEarlier: 'era prima',
      didYouKnow: 'Lo sapevi?',
      roomClosedTitle: 'Stanza chiusa',
      roomClosedMsg: 'L\'host è uscito. Questa stanza non è più disponibile.',
      roomClosedSub: 'Crea una nuova stanza o unisciti a un\'altra.',
      backToLobby: 'Torna alla lobby',
      playersConnected: '{count} / {max} giocatori connessi',
      startGame: 'Avvia partita',
      nickname: 'Nickname',
      pickColor: 'Colore',
      save: 'Salva',
      finalStandings: 'Classifica finale',
      rank: 'Posizione',
      returnToLobby: 'Torna alla lobby',
      restartGame: 'Ricomincia partita',
      minPlayers: 'Servono almeno 2 giocatori per iniziare',
      roomFull: 'Stanza piena',
      oppLabel: 'Avversario:',
      nextRound: 'Il prossimo round inizierà a breve...',
      sending: 'Invio in corso...',
      networkError: 'Errore di rete. Riprova.',
      failedCreate: 'Impossibile creare la stanza',
      failedJoin: 'Impossibile unirsi alla stanza',
      roundsRange: 'I round devono essere 5–50',
      poolAvailable: '{count} eventi disponibili ✅',
      needEvents: 'Servono almeno {min} eventi per giocare ({count})',
      creating: 'Creazione in corso...',
      minValueLabel: 'Anno inizio',
      maxValueLabel: 'Anno fine',
      groupLabel: 'Regione',
      placeholderStartYear: 'es. 1500',
      placeholderEndYear: 'es. 2000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: "Scegli questo evento come più antico",
      backToHomescreen: '🏠 Torna ai giochi',
    },
  },
  mountains: {
    en: {
      ...baseUiText.en,
      title: 'Multiplayer',
      subtitle: 'Compete with up to 9 friends in real time',
      createGame: 'Create Game',
      joinGame: 'Join Game',
      rounds: 'Number of Rounds (5–50)',
      createRoom: 'Create Room',
      joinRoom: 'Join Room',
      roomCode: 'Room Code',
      loading: 'Loading...',
      waiting: 'Waiting Room',
      waitingOpp: 'Waiting for other players...',
      waitingHost: 'Waiting for host to start the game...',
      yourTurn: 'Your turn! Pick the higher mountain.',
      loadingEvents: 'Loading mountains...',
      you: 'You',
      opponent: 'Opponent',
      leaderboard: 'Leaderboard',
      round: 'Round',
      correct: 'Correct!',
      wrong: 'Wrong!',
      timedOut: 'No answer',
      wasEarlier: 'is higher',
      didYouKnow: 'Did you know?',
      roomClosedTitle: 'Room Closed',
      roomClosedMsg: 'The host has left. This room is no longer available.',
      roomClosedSub: 'Create a new room or join another one.',
      backToLobby: 'Back to Lobby',
      playersConnected: '{count} / {max} players connected',
      startGame: 'Start Game',
      nickname: 'Nickname',
      pickColor: 'Color',
      save: 'Save',
      finalStandings: 'Final Standings',
      rank: 'Rank',
      returnToLobby: 'Return to lobby',
      restartGame: 'Restart game',
      minPlayers: 'Need at least 2 players to start',
      roomFull: 'Room is full',
      oppLabel: 'Opponent:',
      nextRound: 'Next round starting soon...',
      sending: 'Sending...',
      networkError: 'Network error. Please try again.',
      failedCreate: 'Failed to create room',
      failedJoin: 'Failed to join room',
      roundsRange: 'Rounds must be 5–50',
      poolAvailable: '{count} mountains available ✅',
      needEvents: 'Need at least {min} mountains to play ({count})',
      creating: 'Creating...',
      minValueLabel: 'Min Elevation (m)',
      maxValueLabel: 'Max Elevation (m)',
      groupLabel: 'Range',
      placeholderStartYear: 'e.g. 2000',
      placeholderEndYear: 'e.g. 8000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Pick this mountain as higher',
      backToHomescreen: '🏠 Back to Games',
    },
    cs: {
      ...baseUiText.cs,
      title: 'Multiplayer',
      subtitle: 'Soutěž s až 9 přáteli v reálném čase',
      createGame: 'Vytvořit hru',
      joinGame: 'Připojit se ke hře',
      rounds: 'Počet kol (5–50)',
      createRoom: 'Vytvořit místnost',
      joinRoom: 'Připojit se',
      roomCode: 'Kód místnosti',
      loading: 'Načítání...',
      waiting: 'Čekací místnost',
      waitingOpp: 'Čeká se na ostatní hráče...',
      waitingHost: 'Čeká se na hostitele, aby spustil hru...',
      yourTurn: 'Jsi na tahu! Vyber vyšší horu.',
      loadingEvents: 'Načítání hor...',
      you: 'Ty',
      opponent: 'Soupeř',
      leaderboard: 'Žebříček',
      round: 'Kolo',
      correct: 'Správně!',
      wrong: 'Špatně!',
      timedOut: 'Bez odpovědi',
      wasEarlier: 'je vyšší',
      didYouKnow: 'Věděl jsi?',
      roomClosedTitle: 'Místnost uzavřena',
      roomClosedMsg: 'Hostitel odešel. Tato místnost již není dostupná.',
      roomClosedSub: 'Vytvoř novou místnost nebo se připoj k jiné.',
      backToLobby: 'Zpět do lobby',
      playersConnected: '{count} / {max} hráčů připojeno',
      startGame: 'Spustit hru',
      nickname: 'Přezdívka',
      pickColor: 'Barva',
      save: 'Uložit',
      finalStandings: 'Konečné pořadí',
      rank: 'Pozice',
      returnToLobby: 'Zpět do lobby',
      restartGame: 'Restart hry',
      minPlayers: 'Ke startu jsou potřeba alespoň 2 hráči',
      roomFull: 'Místnost je plná',
      oppLabel: 'Soupeř:',
      nextRound: 'Další kolo začíná za chvíli...',
      sending: 'Odesílání...',
      networkError: 'Chyba sítě. Zkus to znovu.',
      failedCreate: 'Nepodařilo se vytvořit místnost',
      failedJoin: 'Nepodařilo se připojit do místnosti',
      roundsRange: 'Kol musí být 5–50',
      poolAvailable: '{count} hor k dispozici ✅',
      needEvents: 'Potřebuješ alespoň {min} hor ke hře ({count})',
      creating: 'Vytváření...',
      minValueLabel: 'Min. nadmořská výška (m)',
      maxValueLabel: 'Max. nadmořská výška (m)',
      groupLabel: 'Pohoří',
      placeholderStartYear: 'např. 2000',
      placeholderEndYear: 'např. 8000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Vyber tuto horu jako vyšší',
      backToHomescreen: '🏠 Zpět na hry',
    },
    it: {
      ...baseUiText.it,
      title: 'Multiplayer',
      subtitle: 'Gareggia con fino a 9 amici in tempo reale',
      createGame: 'Crea partita',
      joinGame: 'Unisciti alla partita',
      rounds: 'Numero di round (5–50)',
      createRoom: 'Crea stanza',
      joinRoom: 'Unisciti',
      roomCode: 'Codice stanza',
      loading: 'Caricamento...',
      waiting: 'Sala d\'attesa',
      waitingOpp: 'In attesa degli altri giocatori...',
      waitingHost: 'In attesa che l\'host avvii la partita...',
      yourTurn: 'Tocca a te! Scegli la montagna più alta.',
      loadingEvents: 'Caricamento montagne...',
      you: 'Tu',
      opponent: 'Avversario',
      leaderboard: 'Classifica',
      round: 'Round',
      correct: 'Corretto!',
      wrong: 'Sbagliato!',
      timedOut: 'Nessuna risposta',
      wasEarlier: 'è più alta',
      didYouKnow: 'Lo sapevi?',
      roomClosedTitle: 'Stanza chiusa',
      roomClosedMsg: 'L\'host è uscito. Questa stanza non è più disponibile.',
      roomClosedSub: 'Crea una nuova stanza o unisciti a un\'altra.',
      backToLobby: 'Torna alla lobby',
      playersConnected: '{count} / {max} giocatori connessi',
      startGame: 'Avvia partita',
      nickname: 'Nickname',
      pickColor: 'Colore',
      save: 'Salva',
      finalStandings: 'Classifica finale',
      rank: 'Posizione',
      returnToLobby: 'Torna alla lobby',
      restartGame: 'Ricomincia partita',
      minPlayers: 'Servono almeno 2 giocatori per iniziare',
      roomFull: 'Stanza piena',
      oppLabel: 'Avversario:',
      nextRound: 'Il prossimo round inizierà a breve...',
      sending: 'Invio in corso...',
      networkError: 'Errore di rete. Riprova.',
      failedCreate: 'Impossibile creare la stanza',
      failedJoin: 'Impossibile unirsi alla stanza',
      roundsRange: 'I round devono essere 5–50',
      poolAvailable: '{count} montagne disponibili ✅',
      needEvents: 'Servono almeno {min} montagne per giocare ({count})',
      creating: 'Creazione in corso...',
      minValueLabel: 'Altitudine min (m)',
      maxValueLabel: 'Altitudine max (m)',
      groupLabel: 'Catena',
      placeholderStartYear: 'es. 2000',
      placeholderEndYear: 'es. 8000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Scegli questa montagna come più alta',
      backToHomescreen: '🏠 Torna ai giochi',
    },
  },
  rivers: {
    en: {
      ...baseUiText.en,
      title: 'Multiplayer',
      subtitle: 'Compete with up to 9 friends in real time',
      createGame: 'Create Game',
      joinGame: 'Join Game',
      rounds: 'Number of Rounds (5–50)',
      createRoom: 'Create Room',
      joinRoom: 'Join Room',
      roomCode: 'Room Code',
      loading: 'Loading...',
      waiting: 'Waiting Room',
      waitingOpp: 'Waiting for other players...',
      waitingHost: 'Waiting for host to start the game...',
      yourTurn: 'Your turn! Pick the longer river.',
      loadingEvents: 'Loading rivers...',
      you: 'You',
      opponent: 'Opponent',
      leaderboard: 'Leaderboard',
      round: 'Round',
      correct: 'Correct!',
      wrong: 'Wrong!',
      timedOut: 'No answer',
      wasEarlier: 'is longer',
      didYouKnow: 'Did you know?',
      roomClosedTitle: 'Room Closed',
      roomClosedMsg: 'The host has left. This room is no longer available.',
      roomClosedSub: 'Create a new room or join another one.',
      backToLobby: 'Back to Lobby',
      playersConnected: '{count} / {max} players connected',
      startGame: 'Start Game',
      nickname: 'Nickname',
      pickColor: 'Color',
      save: 'Save',
      finalStandings: 'Final Standings',
      rank: 'Rank',
      returnToLobby: 'Return to lobby',
      restartGame: 'Restart game',
      minPlayers: 'Need at least 2 players to start',
      roomFull: 'Room is full',
      oppLabel: 'Opponent:',
      nextRound: 'Next round starting soon...',
      sending: 'Sending...',
      networkError: 'Network error. Please try again.',
      failedCreate: 'Failed to create room',
      failedJoin: 'Failed to join room',
      roundsRange: 'Rounds must be 5–50',
      poolAvailable: '{count} rivers available ✅',
      needEvents: 'Need at least {min} rivers to play ({count})',
      creating: 'Creating...',
      minValueLabel: 'Min Length (km)',
      maxValueLabel: 'Max Length (km)',
      groupLabel: 'Region',
      placeholderStartYear: 'e.g. 100',
      placeholderEndYear: 'e.g. 7000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Pick this river as longer',
      backToHomescreen: '🏠 Back to Games',
    },
    cs: {
      ...baseUiText.cs,
      title: 'Multiplayer',
      subtitle: 'Soutěž s až 9 přáteli v reálném čase',
      createGame: 'Vytvořit hru',
      joinGame: 'Připojit se ke hře',
      rounds: 'Počet kol (5–50)',
      createRoom: 'Vytvořit místnost',
      joinRoom: 'Připojit se',
      roomCode: 'Kód místnosti',
      loading: 'Načítání...',
      waiting: 'Čekací místnost',
      waitingOpp: 'Čeká se na ostatní hráče...',
      waitingHost: 'Čeká se na hostitele, aby spustil hru...',
      yourTurn: 'Jsi na tahu! Vyber delší řeku.',
      loadingEvents: 'Načítání řek...',
      you: 'Ty',
      opponent: 'Soupeř',
      leaderboard: 'Žebříček',
      round: 'Kolo',
      correct: 'Správně!',
      wrong: 'Špatně!',
      timedOut: 'Bez odpovědi',
      wasEarlier: 'je delší',
      didYouKnow: 'Věděl jsi?',
      roomClosedTitle: 'Místnost uzavřena',
      roomClosedMsg: 'Hostitel odešel. Tato místnost již není dostupná.',
      roomClosedSub: 'Vytvoř novou místnost nebo se připoj k jiné.',
      backToLobby: 'Zpět do lobby',
      playersConnected: '{count} / {max} hráčů připojeno',
      startGame: 'Spustit hru',
      nickname: 'Přezdívka',
      pickColor: 'Barva',
      save: 'Uložit',
      finalStandings: 'Konečné pořadí',
      rank: 'Pozice',
      returnToLobby: 'Zpět do lobby',
      restartGame: 'Restart hry',
      minPlayers: 'Ke startu jsou potřeba alespoň 2 hráči',
      roomFull: 'Místnost je plná',
      oppLabel: 'Soupeř:',
      nextRound: 'Další kolo začíná za chvíli...',
      sending: 'Odesílání...',
      networkError: 'Chyba sítě. Zkus to znovu.',
      failedCreate: 'Nepodařilo se vytvořit místnost',
      failedJoin: 'Nepodařilo se připojit do místnosti',
      roundsRange: 'Kol musí být 5–50',
      poolAvailable: '{count} řek k dispozici ✅',
      needEvents: 'Potřebuješ alespoň {min} řek ke hře ({count})',
      creating: 'Vytváření...',
      minValueLabel: 'Min. délka (km)',
      maxValueLabel: 'Max. délka (km)',
      groupLabel: 'Region',
      placeholderStartYear: 'např. 100',
      placeholderEndYear: 'např. 7000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Vyber tuto řeku jako delší',
      backToHomescreen: '🏠 Zpět na hry',
    },
    it: {
      ...baseUiText.it,
      title: 'Multiplayer',
      subtitle: 'Gareggia con fino a 9 amici in tempo reale',
      createGame: 'Crea partita',
      joinGame: 'Unisciti alla partita',
      rounds: 'Numero di round (5–50)',
      createRoom: 'Crea stanza',
      joinRoom: 'Unisciti',
      roomCode: 'Codice stanza',
      loading: 'Caricamento...',
      waiting: 'Sala d\'attesa',
      waitingOpp: 'In attesa degli altri giocatori...',
      waitingHost: 'In attesa che l\'host avvii la partita...',
      yourTurn: 'Tocca a te! Scegli il fiume più lungo.',
      loadingEvents: 'Caricamento fiumi...',
      you: 'Tu',
      opponent: 'Avversario',
      leaderboard: 'Classifica',
      round: 'Round',
      correct: 'Corretto!',
      wrong: 'Sbagliato!',
      timedOut: 'Nessuna risposta',
      wasEarlier: 'è più lungo',
      didYouKnow: 'Lo sapevi?',
      roomClosedTitle: 'Stanza chiusa',
      roomClosedMsg: 'L\'host è uscito. Questa stanza non è più disponibile.',
      roomClosedSub: 'Crea una nuova stanza o unisciti a un\'altra.',
      backToLobby: 'Torna alla lobby',
      playersConnected: '{count} / {max} giocatori connessi',
      startGame: 'Avvia partita',
      nickname: 'Nickname',
      pickColor: 'Colore',
      save: 'Salva',
      finalStandings: 'Classifica finale',
      rank: 'Posizione',
      returnToLobby: 'Torna alla lobby',
      restartGame: 'Ricomincia partita',
      minPlayers: 'Servono almeno 2 giocatori per iniziare',
      roomFull: 'Stanza piena',
      oppLabel: 'Avversario:',
      nextRound: 'Il prossimo round inizierà a breve...',
      sending: 'Invio in corso...',
      networkError: 'Errore di rete. Riprova.',
      failedCreate: 'Impossibile creare la stanza',
      failedJoin: 'Impossibile unirsi alla stanza',
      roundsRange: 'I round devono essere 5–50',
      poolAvailable: '{count} fiumi disponibili ✅',
      needEvents: 'Servono almeno {min} fiumi per giocare ({count})',
      creating: 'Creazione in corso...',
      minValueLabel: 'Lunghezza min (km)',
      maxValueLabel: 'Lunghezza max (km)',
      groupLabel: 'Regione',
      placeholderStartYear: 'es. 100',
      placeholderEndYear: 'es. 7000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Scegli questo fiume come più lungo',
      backToHomescreen: '🏠 Torna ai giochi',
    },
  },
};


  history: {
    en: {
      ...baseUiText.en,
      title: 'Multiplayer',
      subtitle: 'Compete with up to 9 friends in real time',
      createGame: 'Create Game',
      joinGame: 'Join Game',
      rounds: 'Number of Rounds (5–50)',
      createRoom: 'Create Room',
      joinRoom: 'Join Room',
      roomCode: 'Room Code',
      loading: 'Loading...',
      waiting: 'Waiting Room',
      waitingOpp: 'Waiting for other players...',
      waitingHost: 'Waiting for host to start the game...',
      yourTurn: 'Your turn! Pick the earlier event.',
      loadingEvents: 'Loading events...',
      you: 'You',
      opponent: 'Opponent',
      leaderboard: 'Leaderboard',
      round: 'Round',
      correct: 'Correct!',
      wrong: 'Wrong!',
      timedOut: 'No answer',
      wasEarlier: 'was earlier',
      didYouKnow: 'Did you know?',
      roomClosedTitle: 'Room Closed',
      roomClosedMsg: 'The host has left. This room is no longer available.',
      roomClosedSub: 'Create a new room or join another one.',
      backToLobby: 'Back to Lobby',
      playersConnected: '{count} / {max} players connected',
      startGame: 'Start Game',
      nickname: 'Nickname',
      pickColor: 'Color',
      save: 'Save',
      finalStandings: 'Final Standings',
      rank: 'Rank',
      returnToLobby: 'Return to lobby',
      restartGame: 'Restart game',
      minPlayers: 'Need at least 2 players to start',
      roomFull: 'Room is full',
      oppLabel: 'Opponent:',
      nextRound: 'Next round starting soon...',
      sending: 'Sending...',
      networkError: 'Network error. Please try again.',
      failedCreate: 'Failed to create room',
      failedJoin: 'Failed to join room',
      roundsRange: 'Rounds must be 5–50',
      poolAvailable: '{count} events available ✅',
      needEvents: 'Need at least {min} events to play ({count})',
      creating: 'Creating...',
      minValueLabel: 'Start Year',
      maxValueLabel: 'End Year',
      groupLabel: 'Region',
      placeholderStartYear: 'e.g. 1500',
      placeholderEndYear: 'e.g. 2000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Pick this event as earlier',
      backToHomescreen: '🏠 Back to Games',
    },
    cs: {
      ...baseUiText.cs,
      title: 'Multiplayer',
      subtitle: 'Soutěž s až 9 přáteli v reálném čase',
      createGame: 'Vytvořit hru',
      joinGame: 'Připojit se ke hře',
      rounds: 'Počet kol (5–50)',
      createRoom: 'Vytvořit místnost',
      joinRoom: 'Připojit se',
      roomCode: 'Kód místnosti',
      loading: 'Načítání...',
      waiting: 'Čekací místnost',
      waitingOpp: 'Čeká se na ostatní hráče...',
      waitingHost: 'Čeká se na hostitele, aby spustil hru...',
      yourTurn: 'Jsi na tahu! Vyber dřívější událost.',
      loadingEvents: 'Načítání událostí...',
      you: 'Ty',
      opponent: 'Soupeř',
      leaderboard: 'Žebříček',
      round: 'Kolo',
      correct: 'Správně!',
      wrong: 'Špatně!',
      timedOut: 'Bez odpovědi',
      wasEarlier: 'bylo dřív',
      didYouKnow: 'Věděl jsi?',
      roomClosedTitle: 'Místnost uzavřena',
      roomClosedMsg: 'Hostitel odešel. Tato místnost již není dostupná.',
      roomClosedSub: 'Vytvoř novou místnost nebo se připoj k jiné.',
      backToLobby: 'Zpět do lobby',
      playersConnected: '{count} / {max} hráčů připojeno',
      startGame: 'Spustit hru',
      nickname: 'Přezdívka',
      pickColor: 'Barva',
      save: 'Uložit',
      finalStandings: 'Konečné pořadí',
      rank: 'Pozice',
      returnToLobby: 'Zpět do lobby',
      restartGame: 'Restart hry',
      minPlayers: 'Ke startu jsou potřeba alespoň 2 hráči',
      roomFull: 'Místnost je plná',
      oppLabel: 'Soupeř:',
      nextRound: 'Další kolo začíná za chvíli...',
      sending: 'Odesílání...',
      networkError: 'Chyba sítě. Zkus to znovu.',
      failedCreate: 'Nepodařilo se vytvořit místnost',
      failedJoin: 'Nepodařilo se připojit do místnosti',
      roundsRange: 'Kol musí být 5–50',
      poolAvailable: '{count} událostí k dispozici ✅',
      needEvents: 'Potřebuješ alespoň {min} událostí ke hře ({count})',
      creating: 'Vytváření...',
      minValueLabel: 'Od roku',
      maxValueLabel: 'Do roku',
      groupLabel: 'Region',
      placeholderStartYear: 'např. 1500',
      placeholderEndYear: 'např. 2000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Vyber tuto událost jako dřívější',
      backToHomescreen: '🏠 Zpět na hry',
    },
    it: {
      ...baseUiText.it,
      title: 'Multiplayer',
      subtitle: 'Gareggia con fino a 9 amici in tempo reale',
      createGame: 'Crea partita',
      joinGame: 'Unisciti alla partita',
      rounds: 'Numero di round (5–50)',
      createRoom: 'Crea stanza',
      joinRoom: 'Unisciti',
      roomCode: 'Codice stanza',
      loading: 'Caricamento...',
      waiting: 'Sala d\'attesa',
      waitingOpp: 'In attesa degli altri giocatori...',
      waitingHost: 'In attesa che l\'host avvii la partita...',
      yourTurn: 'Tocca a te! Scegli l\'evento più antico.',
      loadingEvents: 'Caricamento eventi...',
      you: 'Tu',
      opponent: 'Avversario',
      leaderboard: 'Classifica',
      round: 'Round',
      correct: 'Corretto!',
      wrong: 'Sbagliato!',
      timedOut: 'Nessuna risposta',
      wasEarlier: 'era prima',
      didYouKnow: 'Lo sapevi?',
      roomClosedTitle: 'Stanza chiusa',
      roomClosedMsg: 'L\'host è uscito. Questa stanza non è più disponibile.',
      roomClosedSub: 'Crea una nuova stanza o unisciti a un\'altra.',
      backToLobby: 'Torna alla lobby',
      playersConnected: '{count} / {max} giocatori connessi',
      startGame: 'Avvia partita',
      nickname: 'Nickname',
      pickColor: 'Colore',
      save: 'Salva',
      finalStandings: 'Classifica finale',
      rank: 'Posizione',
      returnToLobby: 'Torna alla lobby',
      restartGame: 'Ricomincia partita',
      minPlayers: 'Servono almeno 2 giocatori per iniziare',
      roomFull: 'Stanza piena',
      oppLabel: 'Avversario:',
      nextRound: 'Il prossimo round inizierà a breve...',
      sending: 'Invio in corso...',
      networkError: 'Errore di rete. Riprova.',
      failedCreate: 'Impossibile creare la stanza',
      failedJoin: 'Impossibile unirsi alla stanza',
      roundsRange: 'I round devono essere 5–50',
      poolAvailable: '{count} eventi disponibili ✅',
      needEvents: 'Servono almeno {min} eventi per giocare ({count})',
      creating: 'Creazione in corso...',
      minValueLabel: 'Anno inizio',
      maxValueLabel: 'Anno fine',
      groupLabel: 'Regione',
      placeholderStartYear: 'es. 1500',
      placeholderEndYear: 'es. 2000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: "Scegli questo evento come più antico",
      backToHomescreen: '🏠 Torna ai giochi',
    },
  },

  mountains: {
    en: {
      ...baseUiText.en,
      title: 'Multiplayer',
      subtitle: 'Compete with up to 9 friends in real time',
      createGame: 'Create Game',
      joinGame: 'Join Game',
      rounds: 'Number of Rounds (5–50)',
      createRoom: 'Create Room',
      joinRoom: 'Join Room',
      roomCode: 'Room Code',
      loading: 'Loading...',
      waiting: 'Waiting Room',
      waitingOpp: 'Waiting for other players...',
      waitingHost: 'Waiting for host to start the game...',
      yourTurn: 'Your turn! Pick the higher mountain.',
      loadingEvents: 'Loading mountains...',
      you: 'You',
      opponent: 'Opponent',
      leaderboard: 'Leaderboard',
      round: 'Round',
      correct: 'Correct!',
      wrong: 'Wrong!',
      timedOut: 'No answer',
      wasEarlier: 'is higher',
      didYouKnow: 'Did you know?',
      roomClosedTitle: 'Room Closed',
      roomClosedMsg: 'The host has left. This room is no longer available.',
      roomClosedSub: 'Create a new room or join another one.',
      backToLobby: 'Back to Lobby',
      playersConnected: '{count} / {max} players connected',
      startGame: 'Start Game',
      nickname: 'Nickname',
      pickColor: 'Color',
      save: 'Save',
      finalStandings: 'Final Standings',
      rank: 'Rank',
      returnToLobby: 'Return to lobby',
      restartGame: 'Restart game',
      minPlayers: 'Need at least 2 players to start',
      roomFull: 'Room is full',
      oppLabel: 'Opponent:',
      nextRound: 'Next round starting soon...',
      sending: 'Sending...',
      networkError: 'Network error. Please try again.',
      failedCreate: 'Failed to create room',
      failedJoin: 'Failed to join room',
      roundsRange: 'Rounds must be 5–50',
      poolAvailable: '{count} mountains available ✅',
      needEvents: 'Need at least {min} mountains to play ({count})',
      creating: 'Creating...',
      minValueLabel: 'Min Elevation (m)',
      maxValueLabel: 'Max Elevation (m)',
      groupLabel: 'Range',
      placeholderStartYear: 'e.g. 2000',
      placeholderEndYear: 'e.g. 8000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Pick this mountain as higher',
      backToHomescreen: '🏠 Back to Games',
    },
    cs: {
      ...baseUiText.cs,
      title: 'Multiplayer',
      subtitle: 'Soutěž s až 9 přáteli v reálném čase',
      createGame: 'Vytvořit hru',
      joinGame: 'Připojit se ke hře',
      rounds: 'Počet kol (5–50)',
      createRoom: 'Vytvořit místnost',
      joinRoom: 'Připojit se',
      roomCode: 'Kód místnosti',
      loading: 'Načítání...',
      waiting: 'Čekací místnost',
      waitingOpp: 'Čeká se na ostatní hráče...',
      waitingHost: 'Čeká se na hostitele, aby spustil hru...',
      yourTurn: 'Jsi na tahu! Vyber vyšší horu.',
      loadingEvents: 'Načítání hor...',
      you: 'Ty',
      opponent: 'Soupeř',
      leaderboard: 'Žebříček',
      round: 'Kolo',
      correct: 'Správně!',
      wrong: 'Špatně!',
      timedOut: 'Bez odpovědi',
      wasEarlier: 'je vyšší',
      didYouKnow: 'Věděl jsi?',
      roomClosedTitle: 'Místnost uzavřena',
      roomClosedMsg: 'Hostitel odešel. Tato místnost již není dostupná.',
      roomClosedSub: 'Vytvoř novou místnost nebo se připoj k jiné.',
      backToLobby: 'Zpět do lobby',
      playersConnected: '{count} / {max} hráčů připojeno',
      startGame: 'Spustit hru',
      nickname: 'Přezdívka',
      pickColor: 'Barva',
      save: 'Uložit',
      finalStandings: 'Konečné pořadí',
      rank: 'Pozice',
      returnToLobby: 'Zpět do lobby',
      restartGame: 'Restart hry',
      minPlayers: 'Ke startu jsou potřeba alespoň 2 hráči',
      roomFull: 'Místnost je plná',
      oppLabel: 'Soupeř:',
      nextRound: 'Další kolo začíná za chvíli...',
      sending: 'Odesílání...',
      networkError: 'Chyba sítě. Zkus to znovu.',
      failedCreate: 'Nepodařilo se vytvořit místnost',
      failedJoin: 'Nepodařilo se připojit do místnosti',
      roundsRange: 'Kol musí být 5–50',
      poolAvailable: '{count} hor k dispozici ✅',
      needEvents: 'Potřebuješ alespoň {min} hor ke hře ({count})',
      creating: 'Vytváření...',
      minValueLabel: 'Min. nadmořská výška (m)',
      maxValueLabel: 'Max. nadmořská výška (m)',
      groupLabel: 'Pohoří',
      placeholderStartYear: 'např. 2000',
      placeholderEndYear: 'např. 8000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Vyber tuto horu jako vyšší',
      backToHomescreen: '🏠 Zpět na hry',
    },
    it: {
      ...baseUiText.it,
      title: 'Multiplayer',
      subtitle: 'Gareggia con fino a 9 amici in tempo reale',
      createGame: 'Crea partita',
      joinGame: 'Unisciti alla partita',
      rounds: 'Numero di round (5–50)',
      createRoom: 'Crea stanza',
      joinRoom: 'Unisciti',
      roomCode: 'Codice stanza',
      loading: 'Caricamento...',
      waiting: 'Sala d\'attesa',
      waitingOpp: 'In attesa degli altri giocatori...',
      waitingHost: 'In attesa che l\'host avvii la partita...',
      yourTurn: 'Tocca a te! Scegli la montagna più alta.',
      loadingEvents: 'Caricamento montagne...',
      you: 'Tu',
      opponent: 'Avversario',
      leaderboard: 'Classifica',
      round: 'Round',
      correct: 'Corretto!',
      wrong: 'Sbagliato!',
      timedOut: 'Nessuna risposta',
      wasEarlier: 'è più alta',
      didYouKnow: 'Lo sapevi?',
      roomClosedTitle: 'Stanza chiusa',
      roomClosedMsg: 'L\'host è uscito. Questa stanza non è più disponibile.',
      roomClosedSub: 'Crea una nuova stanza o unisciti a un\'altra.',
      backToLobby: 'Torna alla lobby',
      playersConnected: '{count} / {max} giocatori connessi',
      startGame: 'Avvia partita',
      nickname: 'Nickname',
      pickColor: 'Colore',
      save: 'Salva',
      finalStandings: 'Classifica finale',
      rank: 'Posizione',
      returnToLobby: 'Torna alla lobby',
      restartGame: 'Ricomincia partita',
      minPlayers: 'Servono almeno 2 giocatori per iniziare',
      roomFull: 'Stanza piena',
      oppLabel: 'Avversario:',
      nextRound: 'Il prossimo round inizierà a breve...',
      sending: 'Invio in corso...',
      networkError: 'Errore di rete. Riprova.',
      failedCreate: 'Impossibile creare la stanza',
      failedJoin: 'Impossibile unirsi alla stanza',
      roundsRange: 'I round devono essere 5–50',
      poolAvailable: '{count} montagne disponibili ✅',
      needEvents: 'Servono almeno {min} montagne per giocare ({count})',
      creating: 'Creazione in corso...',
      minValueLabel: 'Altitudine min (m)',
      maxValueLabel: 'Altitudine max (m)',
      groupLabel: 'Catena',
      placeholderStartYear: 'es. 2000',
      placeholderEndYear: 'es. 8000',
      placeholderRoomCode: 'abc',
      pickAriaLabel: 'Scegli questa montagna come più alta',
      backToHomescreen: '🏠 Torna ai giochi',
    },
  },
};